[package]
name = "oxidizer_time_tests"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
authors.workspace = true
license-file.workspace = true
homepage.workspace = true
repository.workspace = true
categories.workspace = true
readme.workspace = true
publish = false
keywords = [
    "Rust",
    "Oxidizer",
    "tests",
    "no-fakes",
]
description = "Tests for the `oxidizer_time` crate without the `fakes` feature enabled. These cannot be tested in the `oxidizer_time` crate itself."

[lib]
crate-type = ["lib"]

[lints]
workspace = true

[dependencies]
oxidizer_time = { workspace = true }
oxidizer_rt = { workspace = true }
futures = { workspace = true }


