# Copyright (c) Microsoft Corporation.
# Licensed under the MIT License.

[package]
name = "fakeable_impl"
description = "Implementation details for the fakeable procedural macros."
version = "0.2.0"
autotests = false
readme = "README.md"
keywords = ["oxidizer", "fake", "mock", "testing"]
categories = ["development-tools::testing", "rust-patterns"]

edition = { workspace = true }
rust-version = { workspace = true }
authors = { workspace = true }
license = { workspace = true }
homepage = { workspace = true }
include = { workspace = true }
repository = "https://github.com/microsoft/oxidizer/tree/main/crates/fakeable_impl"

[package.metadata.anvil.miri]
exclude = true

[package.metadata.cargo_check_external_types]
allowed_external_types = ["proc_macro2::*", "syn::error::*"]

[package.metadata.docs.rs]
all-features = true

[features]
default = []
mockall = []

[dependencies]
proc-macro2 = { workspace = true }
quote = { workspace = true }
syn = { workspace = true, features = ["clone-impls", "extra-traits", "full", "parsing", "printing", "proc-macro", "visit", "visit-mut"] }

[dev-dependencies]
insta = { workspace = true }
prettyplease = { workspace = true }

# >>> anvil-managed: anvil-lints
[lints]
workspace = true
# <<< anvil-managed: anvil-lints
