// Copyright (c) Microsoft Corporation.
// Licensed under the MIT License.

//! Static router code generation.
//!
//! The [`Generator`](crate::Generator) lowers a set of [`RouteRule`]s into a
//! `Route` enum whose inherent `resolve` associated function matches an HTTP
//! method + path against the routes. Because the route set is fully known at
//! build time, the routes are lowered into a **compile-time trie**: a nested `match` over the path's
//! `/`-separated segments. Unlike a general-purpose runtime trie, there are no
//! node structures, no bounds-checked node traversal, and no per-request
//! allocation — the segment offsets are scanned into stack buffers
//! ([`routerama::codegen_helpers::scan_segments`]) and the captured path variables are
//! returned inline in the matched `Route` variant's `&'p str` fields (borrowed
//! from the request path).
//!
//! At each trie node the branches are tried most-specific-first — literal
//! segments before intra-segment affix parameters before a single-segment
//! wildcard before a `**` catch-all, and a deeper (longer) match before a
//! shorter one — so overlapping templates resolve deterministically.
//!
//! [`routerama::codegen_helpers::scan_segments`]: https://docs.rs/routerama

use std::collections::BTreeMap;

use proc_macro2::{Ident, Literal, Span, TokenStream};
use quote::quote;

use crate::generator_builder::GeneratorBuilder;
use crate::route_rule::RouteRule;
use crate::trie::{Leaf, Node, VarPlan, affix_edges_in_match_order, build_trie, capture_field_names, field_name, is_valid_variant};

/// Generates a static router for `routes` with emission controlled by `builder`.
///
/// The single entry point behind [`Generator::generate`](crate::Generator::generate);
/// the customer-facing API is the [`Generator`](crate::Generator) type.
pub(crate) fn generate(routes: &[RouteRule], builder: &GeneratorBuilder) -> TokenStream {
    let runtime = builder.runtime_tokens();
    let visibility = builder.visibility_tokens();
    let route_enum = builder.route_type_ident();

    let trie = build_trie(routes);
    let root = trie.root;
    let any_verb = trie.any_verb;
    let cap = trie.max_segments;

    let body_bind = if any_verb {
        quote! { let (__body, __verb) = #runtime::split_verb(path); }
    } else {
        quote! { let __body: &str = path; }
    };

    let cap_lit = Literal::usize_unsuffixed(cap);
    let scan = quote! {
        let mut __starts = [0usize; #cap_lit];
        let mut __ends = [0usize; #cap_lit];
        let __count = #runtime::scan_segments(__body, &mut __starts, &mut __ends);
    };

    let match_tree = emit_node(&root, 0, any_verb, &route_enum);

    let mut conflicts = Vec::new();
    detect_conflicts(&root, "", &mut conflicts);
    let conflict_errors = conflicts.iter().map(|message| quote! { ::core::compile_error!(#message); });

    // The route enum callers `match` on (one field-carrying variant per route
    // name), plus any `compile_error!`s the route set requires.
    let (variants, variant_errors) = collect_variants(routes);
    // The enum is lifetime-parameterized only when at least one variant carries a
    // captured `&'p str` field; otherwise `'p` would be unused.
    let route_generic = variants.iter().any(|variant| !variant.fields.is_empty());
    let route_ty = if route_generic {
        quote! { #route_enum<'p> }
    } else {
        quote! { #route_enum }
    };

    // `resolve` is an inherent associated function of the route enum, so a
    // generated router is a single named symbol. When the enum is
    // lifetime-parameterized its inherent `impl` already binds `'p` (inferred at
    // the call site from `path`); otherwise `resolve` introduces `'p` itself.
    let resolve_generics = if route_generic {
        quote! { <__P> }
    } else {
        quote! { <'p, __P> }
    };
    let resolve_doc = format!(
        "Resolves an HTTP `method` + `path` to the matching `{route_enum}`, capturing any path variables in the matched variant's fields. Returns `None` if no route matches. Generated by `routerama_build`."
    );
    let resolve_method = quote! {
        #[doc = #resolve_doc]
        #[allow(
            clippy::all,
            clippy::pedantic,
            clippy::nursery,
            clippy::restriction,
            dead_code,
            unused,
            reason = "code generated by routerama_build"
        )]
        #[must_use]
        #visibility fn resolve #resolve_generics (
            method: impl ::core::convert::AsRef<str>,
            path: &'p __P,
        ) -> ::core::option::Option<#route_ty>
        where
            __P: ::core::convert::AsRef<str> + ?::core::marker::Sized,
        {
            let method: &str = ::core::convert::AsRef::<str>::as_ref(&method);
            let path: &'p str = ::core::convert::AsRef::<str>::as_ref(path);
            #(#conflict_errors)*
            #body_bind
            #scan
            #match_tree
            ::core::option::Option::None
        }
    };

    let route_enum_def = emit_route_enum(visibility, &route_enum, &variants, route_generic, &resolve_method);
    let router_trait_impl = emit_router_trait_impl(&route_enum, &route_ty, runtime);
    let dyn_trait_impls = match builder.router_spec() {
        Some((router_visibility, router_name)) => {
            emit_dyn_trait_impls(&route_enum, &route_ty, &variants, runtime, router_visibility, router_name)
        }
        None => quote! {},
    };

    quote! {
        #(#variant_errors)*

        #route_enum_def

        #router_trait_impl

        #dyn_trait_impls
    }
}

/// Emits a zero-sized [`Router`](routerama::Router) type plus a
/// [`RouteMatch`](routerama::RouteMatch) impl for the route enum, so the static
/// router plugs into the runtime routing-trait abstraction (and composes with a
/// dynamic router via `EitherRouter`).
///
/// - `struct #router_name;` — a ZST (with `router_visibility`) whose
///   `Router::resolve` forwards to the enum's inherent `resolve`, with
///   `type Match<'p> = #route_ty`.
/// - `impl RouteMatch for #route_ty` — `name` forwards to the inherent `name`;
///   `capture(field)` returns the matching variant field by its (field-name-form)
///   key, the same key the dynamic router uses.
fn emit_dyn_trait_impls(
    route_enum: &Ident,
    route_ty: &TokenStream,
    variants: &[VariantSpec],
    runtime: &TokenStream,
    router_visibility: &TokenStream,
    router_name: &str,
) -> TokenStream {
    let router_ident = Ident::new(router_name, Span::call_site());
    let router_doc = format!(
        "A zero-sized [`Router`](routerama::Router) for [`{route_enum}`], forwarding to its inherent `resolve`. Lets the static router compose through the runtime routing traits (e.g. an `EitherRouter` static core with a dynamic overlay). Generated by `routerama_build`."
    );
    // One capture arm per variant: a field-carrying variant matches its captured
    // field name to the requested key; a unit variant captures nothing.
    let capture_arms = variants.iter().map(|variant| {
        let ident = &variant.ident;
        if variant.fields.is_empty() {
            quote! { #route_enum::#ident => ::core::option::Option::None, }
        } else {
            let fields = &variant.fields;
            let key_arms = variant.fields.iter().map(|field| {
                let key = field.to_string();
                quote! { #key => ::core::option::Option::Some(*#field), }
            });
            quote! {
                #route_enum::#ident { #(#fields),* } => match name {
                    #(#key_arms)*
                    _ => ::core::option::Option::None,
                },
            }
        }
    });
    let allow = quote! {
        #[allow(
            clippy::all,
            clippy::pedantic,
            clippy::nursery,
            clippy::restriction,
            dead_code,
            unused,
            reason = "code generated by routerama_build"
        )]
    };
    quote! {
        #[doc = #router_doc]
        #[derive(::core::clone::Clone, ::core::marker::Copy, ::core::fmt::Debug, ::core::default::Default)]
        #allow
        #router_visibility struct #router_ident;

        #allow
        impl #runtime::Router for #router_ident {
            type Match<'p> = #route_ty;

            #[inline]
            fn resolve<'p>(&'p self, method: &str, path: &'p str) -> ::core::option::Option<#route_ty> {
                #route_enum::resolve(method, path)
            }
        }

        #allow
        impl<'p> #runtime::RouteMatch<'p> for #route_ty {
            #[inline]
            fn name(&self) -> &str {
                #route_enum::name(self)
            }

            #[inline]
            fn capture(&self, name: &str) -> ::core::option::Option<&'p str> {
                match self {
                    #(#capture_arms)*
                }
            }
        }
    }
}

/// Emits `impl #runtime::Route<'p>` for the generated route enum, forwarding to
/// its inherent `resolve`/`name` (inherent associated functions take
/// precedence, so `#route_enum::resolve` calls the inherent one, not this).
///
/// The trait is parameterized by the request-path lifetime `'p`: a capturing
/// enum is `Route<'p>` (`impl<'p> Route<'p> for Route<'p>`); a capture-less enum
/// is non-generic and implements the trait for every `'p`
/// (`impl<'p> Route<'p> for Route`). Either way `resolve` binds `'p` to `path`.
fn emit_router_trait_impl(route_enum: &Ident, route_ty: &TokenStream, runtime: &TokenStream) -> TokenStream {
    // `route_ty` is `Route<'p>` when generic and `Route` otherwise; the impl
    // always introduces `'p` (used by the trait ref and `resolve`'s `path`).
    quote! {
        #[allow(
            clippy::all,
            clippy::pedantic,
            clippy::nursery,
            clippy::restriction,
            dead_code,
            unused,
            reason = "code generated by routerama_build"
        )]
        impl<'p> #runtime::Route<'p> for #route_ty {
            #[inline]
            fn resolve<__P>(method: impl ::core::convert::AsRef<str>, path: &'p __P) -> ::core::option::Option<Self>
            where
                __P: ::core::convert::AsRef<str> + ?::core::marker::Sized,
            {
                #route_enum::resolve(method, path)
            }

            #[inline]
            fn name(&self) -> &'static str {
                #route_enum::name(self)
            }
        }
    }
}

/// Emits the `Route` enum (one variant per distinct route name, in
/// first-appearance order), its inherent impl (the `name` accessor plus the
/// `resolve_method`), and the `Display`/`AsRef<str>` impls that forward to
/// `name`. Callers `match` on the enum for `O(1)` jump-table dispatch, reading
/// captured path variables straight from each variant's named fields; `name`
/// (and the string traits) recover the declared name string.
///
/// A variant that captures path variables is a struct variant carrying them as
/// `&'p str` fields; a route with no variables is a unit variant. When any
/// variant carries a field the enum is lifetime-parameterized (`Route<'p>`),
/// signaled by `generic`.
fn emit_route_enum(
    visibility: &TokenStream,
    route_enum: &Ident,
    variants: &[VariantSpec],
    generic: bool,
    resolve_method: &TokenStream,
) -> TokenStream {
    let lt = if generic {
        quote! { <'p> }
    } else {
        quote! {}
    };
    let variant_defs = variants.iter().map(|variant| {
        let ident = &variant.ident;
        if variant.fields.is_empty() {
            quote! { #ident }
        } else {
            let fields = variant.fields.iter().map(|field| quote! { #field: &'p str });
            quote! { #ident { #(#fields),* } }
        }
    });
    let name_arms = variants.iter().map(|variant| {
        let ident = &variant.ident;
        let name = &variant.name;
        if variant.fields.is_empty() {
            quote! { #route_enum::#ident => #name, }
        } else {
            quote! { #route_enum::#ident { .. } => #name, }
        }
    });
    quote! {
        /// A resolved route, one variant per route name. Returned by the inherent
        /// [`resolve`](Self::resolve) associated function.
        ///
        /// A route that captures `{variable}` path segments is a struct variant
        /// carrying them as `&'p str` fields (borrowed from the request path); a
        /// route with no variables is a unit variant. Matching on it is an `O(1)`
        /// jump table. Generated by `routerama_build`.
        #[derive(
            ::core::clone::Clone,
            ::core::marker::Copy,
            ::core::fmt::Debug,
            ::core::cmp::PartialEq,
            ::core::cmp::Eq,
            ::core::cmp::PartialOrd,
            ::core::cmp::Ord,
            ::core::hash::Hash
        )]
        #[allow(
            non_camel_case_types,
            missing_docs,
            clippy::all,
            clippy::pedantic,
            clippy::nursery,
            clippy::restriction,
            dead_code,
            unused,
            reason = "code generated by routerama_build"
        )]
        #visibility enum #route_enum #lt {
            #(#variant_defs,)*
        }

        #[allow(
            clippy::all,
            clippy::pedantic,
            clippy::nursery,
            clippy::restriction,
            dead_code,
            unused,
            reason = "code generated by routerama_build"
        )]
        impl #lt #route_enum #lt {
            /// This route's name as the string it was declared with, independent
            /// of any captured variable values.
            #[must_use]
            #visibility const fn name(&self) -> &'static str {
                match *self {
                    #(#name_arms)*
                }
            }

            #resolve_method
        }

        #[allow(
            clippy::all,
            clippy::pedantic,
            clippy::nursery,
            clippy::restriction,
            dead_code,
            unused,
            reason = "code generated by routerama_build"
        )]
        impl #lt ::core::fmt::Display for #route_enum #lt {
            fn fmt(&self, f: &mut ::core::fmt::Formatter<'_>) -> ::core::fmt::Result {
                f.write_str(self.name())
            }
        }

        #[allow(
            clippy::all,
            clippy::pedantic,
            clippy::nursery,
            clippy::restriction,
            dead_code,
            unused,
            reason = "code generated by routerama_build"
        )]
        impl #lt ::core::convert::AsRef<str> for #route_enum #lt {
            fn as_ref(&self) -> &str {
                self.name()
            }
        }
    }
}

/// One `Route` enum variant: its identifier, the declared name string
/// ([`Route::name`] recovers it), and the ordered field identifiers for
/// the path variables it captures. `fields` is empty for a route with no
/// `{variable}` segments, which becomes a unit variant.
struct VariantSpec {
    ident: Ident,
    name: String,
    fields: Vec<Ident>,
}

/// Collects one [`VariantSpec`] per distinct route name (first-appearance order)
/// and any `compile_error!`s the route set requires: a name that cannot name a
/// variant, a name whose routes capture inconsistent variable sets (a name maps
/// to one variant with a fixed field list, so the captures must agree), or a
/// variant with two variables that collapse to the same field identifier.
fn collect_variants(routes: &[RouteRule]) -> (Vec<VariantSpec>, Vec<TokenStream>) {
    let mut specs: Vec<VariantSpec> = Vec::new();
    let mut errors: Vec<TokenStream> = Vec::new();
    for route in routes {
        let fields: Vec<Ident> = capture_field_names(route.template().segments())
            .iter()
            .map(|name| field_ident(name))
            .collect();

        if let Some(spec) = specs.iter().find(|spec| spec.name == route.name()) {
            let existing: Vec<String> = spec.fields.iter().map(ToString::to_string).collect();
            let incoming: Vec<String> = fields.iter().map(ToString::to_string).collect();
            if existing != incoming {
                let message = format!(
                    "route name `{}` is bound to routes that capture different path variables ({} vs {}); \
                     a route name maps to one enum variant with a fixed set of fields, so give the routes distinct names",
                    route.name(),
                    fmt_fields(&existing),
                    fmt_fields(&incoming),
                );
                errors.push(quote! { ::core::compile_error!(#message); });
            }
            continue;
        }

        if !is_valid_variant(route.name()) {
            let message = format!(
                "route name `{}` is not a valid Rust identifier; route names must be valid identifiers so they can name a route enum variant",
                route.name()
            );
            errors.push(quote! { ::core::compile_error!(#message); });
        }

        let mut seen: Vec<String> = Vec::new();
        for field in &fields {
            let field = field.to_string();
            if seen.contains(&field) {
                let message = format!(
                    "route name `{}` captures two path variables that map to the same field `{}`; rename one of them",
                    route.name(),
                    field
                );
                errors.push(quote! { ::core::compile_error!(#message); });
            } else {
                seen.push(field);
            }
        }

        specs.push(VariantSpec {
            ident: variant_ident(route.name()),
            name: route.name().to_owned(),
            fields,
        });
    }
    (specs, errors)
}

/// Formats a variant's field-name list for a diagnostic, e.g. `{shelf, book}` or
/// `none`.
fn fmt_fields(fields: &[String]) -> String {
    if fields.is_empty() {
        "none".to_owned()
    } else {
        format!("{{{}}}", fields.join(", "))
    }
}

/// The struct-variant field identifier for a captured variable, whose (possibly
/// dotted) name is given as its path segments — the token [`Ident`] form of
/// [`route_field_name`](crate::trie::route_field_name).
fn field_ident(name: &[String]) -> Ident {
    Ident::new(&field_name(&name.join("_")), Span::call_site())
}

/// The enum-variant identifier for a route `name`. Valid identifiers are used
/// verbatim; anything else is sanitized to a deterministic placeholder so the
/// output still tokenizes (a `compile_error!` reports the real problem).
fn variant_ident(name: &str) -> Ident {
    if is_valid_variant(name) {
        Ident::new(name, Span::call_site())
    } else {
        let sanitized: String = name
            .chars()
            .map(|c| if c == '_' || c.is_ascii_alphanumeric() { c } else { '_' })
            .collect();
        Ident::new(&format!("_R_{sanitized}"), Span::call_site())
    }
}

/// Walks the trie and records a human-readable message for every conflicting
/// route set: two or more routes that reach the same node with the same HTTP
/// method and custom verb, and so match an identical set of requests. Only the
/// first such route would ever be reached, so this is always a mistake.
fn detect_conflicts(node: &Node, prefix: &str, out: &mut Vec<String>) {
    check_bucket(&node.exact, prefix, false, out);
    check_bucket(&node.rest, prefix, true, out);
    for (literal, child) in &node.literals {
        detect_conflicts(child, &format!("{prefix}/{literal}"), out);
    }
    for ((affix_prefix, affix_suffix), child) in &node.affix {
        detect_conflicts(child, &format!("{prefix}/{affix_prefix}{{}}{affix_suffix}"), out);
    }
    if let Some(single) = &node.single {
        detect_conflicts(single, &format!("{prefix}/*"), out);
    }
}

/// Groups a node's leaves by `(method, verb)` and reports any group with more
/// than one route as a conflict.
fn check_bucket(leaves: &[Leaf], prefix: &str, is_rest: bool, out: &mut Vec<String>) {
    let mut groups: BTreeMap<(&str, Option<&str>), Vec<&str>> = BTreeMap::new();
    for leaf in leaves {
        groups
            .entry((leaf.method.as_str(), leaf.verb.as_deref()))
            .or_default()
            .push(leaf.name.as_str());
    }
    for ((method, verb), names) in groups {
        if names.len() > 1 {
            let path = if is_rest { format!("{prefix}/**") } else { prefix.to_owned() };
            let path = if path.is_empty() { "/".to_owned() } else { path };
            let verb = verb.map(|v| format!(":{v}")).unwrap_or_default();
            out.push(format!(
                "conflicting routes: `{method} {path}{verb}` maps to multiple names ({}); \
                 each HTTP method and path may resolve to only one route",
                names.join(", ")
            ));
        }
    }
}

/// Emits the matching code for a trie `node` reached after consuming `depth`
/// segments. On a match the code `return`s; otherwise it falls through.
fn emit_node(node: &Node, depth: usize, any_verb: bool, route_enum: &Ident) -> TokenStream {
    let depth_lit = Literal::usize_unsuffixed(depth);

    // Branch taken when a segment exists at `depth`: try literal edges, then any
    // intra-segment affix edges, then the single-segment wildcard, then any `**`
    // catch-all (most-specific-first).
    let has_literals = !node.literals.is_empty();
    let has_affix = !node.affix.is_empty();
    let needs_seg = has_literals || has_affix;
    let seg_bind = if needs_seg {
        quote! { let __seg: &[u8] = &__body.as_bytes()[__starts[#depth_lit]..__ends[#depth_lit]]; }
    } else {
        quote! {}
    };
    let literal_arms = node.literals.iter().map(|(lit, child)| {
        let child = emit_node(child, depth + 1, any_verb, route_enum);
        // Match the segment as *bytes* (`b"lit"`), not `&str`: a `&str` range index
        // runs a char-boundary check at every node, and the offsets are already
        // known-valid `/`-delimited boundaries. Capture *values* stay `&str`.
        let lit = Literal::byte_string(lit.as_bytes());
        quote! { #lit => { #child } }
    });
    let literal_match = if has_literals {
        quote! {
            match __seg {
                #(#literal_arms)*
                _ => {}
            }
        }
    } else {
        quote! {}
    };
    // An affix edge matches a segment shaped `prefix{var}suffix`: it must be long
    // enough to carry a non-empty capture and bound by the literal prefix/suffix.
    // Edges are tried longest-affix-first so the most specific one wins — the
    // same order the dynamic interpreter uses (a shared source of truth).
    let affix_code = affix_edges_in_match_order(node).into_iter().map(|((prefix, suffix), child)| {
        let child = emit_node(child, depth + 1, any_verb, route_enum);
        let total_lit = Literal::usize_unsuffixed(prefix.len() + suffix.len());
        let prefix_check = if prefix.is_empty() {
            quote! {}
        } else {
            let prefix = Literal::byte_string(prefix.as_bytes());
            quote! { && __seg.starts_with(#prefix) }
        };
        let suffix_check = if suffix.is_empty() {
            quote! {}
        } else {
            let suffix = Literal::byte_string(suffix.as_bytes());
            quote! { && __seg.ends_with(#suffix) }
        };
        quote! {
            if __seg.len() > #total_lit #prefix_check #suffix_check {
                #child
            }
        }
    });
    // A single-segment wildcard (`*` / `{var}`) matches exactly one non-empty
    // segment, so its subtree is guarded on a non-empty segment. Literal edges
    // need no guard; `**` captures the rest.
    let single_code = node
        .single
        .as_ref()
        .map(|child| {
            let child = emit_node(child, depth + 1, any_verb, route_enum);
            quote! {
                if __ends[#depth_lit] > __starts[#depth_lit] {
                    #child
                }
            }
        })
        .unwrap_or_default();
    let rest_dispatch = emit_leaves(&node.rest, any_verb, route_enum);

    let has_segment_branch = has_literals || has_affix || node.single.is_some();
    let segment_branch = if has_segment_branch {
        quote! {
            if __count > #depth_lit {
                #seg_bind
                #literal_match
                #(#affix_code)*
                #single_code
            }
        }
    } else {
        quote! {}
    };

    // Branch taken when the path ends here: exact leaves terminating at this node.
    let exact_dispatch = emit_leaves(&node.exact, any_verb, route_enum);
    let has_end_branch = !node.exact.is_empty();
    let end_branch = if has_end_branch {
        quote! {
            if __count == #depth_lit {
                #exact_dispatch
            }
        }
    } else {
        quote! {}
    };

    // A `**` catch-all matches any remainder length (including zero), so it is
    // emitted once here — after the more-specific literal/single/exact branches —
    // and its open-ended capture handles the empty remainder at runtime.
    let rest_branch = if node.rest.is_empty() {
        quote! {}
    } else {
        quote! {
            if __count >= #depth_lit {
                #rest_dispatch
            }
        }
    };

    quote! {
        #segment_branch
        #end_branch
        #rest_branch
    }
}

/// Emits `method` (and, when any route uses one, `:verb`) dispatch for a set of
/// leaves terminating at the same trie node, returning the matched `Route` on a hit.
fn emit_leaves(leaves: &[Leaf], any_verb: bool, route_enum: &Ident) -> TokenStream {
    if leaves.is_empty() {
        return quote! {};
    }

    // Group by method (preserving first-seen order), deduplicating (method, verb)
    // pairs so no two arms are emitted for the same case.
    let mut groups: Vec<(String, Vec<&Leaf>)> = Vec::new();
    for leaf in leaves {
        let group = if let Some((_, entries)) = groups.iter_mut().find(|(m, _)| *m == leaf.method) {
            entries
        } else {
            groups.push((leaf.method.clone(), Vec::new()));
            &mut groups.last_mut().expect("just pushed").1
        };
        if !group.iter().any(|existing| existing.verb == leaf.verb) {
            group.push(leaf);
        }
    }

    let arms = groups.iter().map(|(method, entries)| {
        let body = if any_verb {
            let verb_arms = entries.iter().map(|leaf| {
                let ret = emit_return(leaf, route_enum);
                if let Some(verb) = &leaf.verb {
                    quote! { ::core::option::Option::Some(#verb) => { #ret } }
                } else {
                    quote! { ::core::option::Option::None => { #ret } }
                }
            });
            quote! {
                match __verb {
                    #(#verb_arms)*
                    _ => {}
                }
            }
        } else {
            emit_return(entries.first().expect("each group has at least one leaf"), route_enum)
        };
        quote! { #method => { #body } }
    });

    quote! {
        match method {
            #(#arms)*
            _ => {}
        }
    }
}

/// Emits a `return Some(...)` of the matched leaf's route enum variant, with its
/// captured path variables filled into the variant's named fields.
fn emit_return(leaf: &Leaf, route_enum: &Ident) -> TokenStream {
    let variant = variant_ident(&leaf.name);
    let route_val = if leaf.vars.is_empty() {
        quote! { #route_enum::#variant }
    } else {
        let field_inits = leaf.vars.iter().map(|plan| {
            let field = Ident::new(plan.field(), Span::call_site());
            let value = var_slice_expr(plan);
            quote! { #field: #value }
        });
        quote! { #route_enum::#variant { #(#field_inits),* } }
    };
    quote! {
        return ::core::option::Option::Some(#route_val);
    }
}

/// Emits the expression that slices a captured path variable's value out of the
/// scanned request path (`&'p str`), used by [`emit_return`] to initialize the
/// matched variant's fields.
fn var_slice_expr(plan: &VarPlan) -> TokenStream {
    match plan {
        VarPlan::Span { a, b, .. } => {
            let a = Literal::usize_unsuffixed(*a);
            let b = Literal::usize_unsuffixed(*b);
            quote! { &__body[__starts[#a]..__ends[#b]] }
        }
        VarPlan::Rest { a, .. } => {
            let a = Literal::usize_unsuffixed(*a);
            quote! { if #a < __count { &__body[__starts[#a]..] } else { "" } }
        }
        VarPlan::Affix {
            a, prefix_len, suffix_len, ..
        } => {
            let a = Literal::usize_unsuffixed(*a);
            let prefix_lit = Literal::usize_unsuffixed(*prefix_len);
            let suffix_lit = Literal::usize_unsuffixed(*suffix_len);
            quote! { &__body[__starts[#a] + #prefix_lit .. __ends[#a] - #suffix_lit] }
        }
    }
}

#[cfg(test)]
mod tests {
    use http_path_template::{Grammar, PathTemplate};

    use super::*;
    use crate::generator::Generator;
    use crate::http_method::HttpMethod;

    fn rules(specs: &[(&str, HttpMethod, &str)]) -> Vec<RouteRule> {
        specs
            .iter()
            .map(|(name, method, pattern)| {
                RouteRule::new(
                    *name,
                    method.clone(),
                    PathTemplate::parse(pattern, Grammar::default()).expect("valid template"),
                )
            })
            .collect()
    }

    fn generated(specs: &[(&str, HttpMethod, &str)]) -> String {
        generate_code(rules(specs)).to_string()
    }

    /// Test helper: generate with the default options.
    fn generate_code(routes: impl IntoIterator<Item = RouteRule>) -> TokenStream {
        let mut generator = Generator::new();
        generator.add_all(routes);
        generator.generate()
    }

    /// Test helper: generate with a configured builder.
    fn generate_code_with(routes: impl IntoIterator<Item = RouteRule>, builder: GeneratorBuilder) -> TokenStream {
        let mut generator = builder.build();
        generator.add_all(routes);
        generator.generate()
    }

    fn ext_rules(specs: &[(&str, HttpMethod, &str)]) -> Vec<RouteRule> {
        specs
            .iter()
            .map(|(name, method, pattern)| {
                RouteRule::new(
                    *name,
                    method.clone(),
                    PathTemplate::parse(pattern, Grammar::default().with_segment_affixes()).expect("valid template"),
                )
            })
            .collect()
    }

    #[test]
    fn generates_a_resolve_function() {
        let code = generated(&[("GetShelf", HttpMethod::Get, "/v1/shelves/{shelf}")]);
        assert!(code.contains("fn resolve"));
        assert!(code.contains("GetShelf"));
        assert!(code.contains(":: routerama :: codegen_helpers :: scan_segments") || code.contains("scan_segments"));
    }

    #[test]
    fn router_type_emits_a_zst_router_and_route_match_impl() {
        // Opting in via `router_type` emits a ZST `Router` (under the given name)
        // + a `RouteMatch` impl, so the static router plugs into the runtime
        // routing-trait abstraction.
        let options = GeneratorBuilder::default().router_type(quote! { pub }, "ShelfRouter");
        let file: syn::File = syn::parse2(generate_code_with(
            rules(&[("GetShelf", HttpMethod::Get, "/v1/shelves/{shelf}")]),
            options,
        ))
        .expect("valid Rust");
        let code = prettyplease::unparse(&file).replace(' ', "");
        assert!(code.contains("structShelfRouter"), "ZST router uses the given name: {code}");
        assert!(
            code.contains("Router\nforShelfRouter") || code.contains("RouterforShelfRouter"),
            "Router impl: {code}"
        );
        assert!(code.contains("RouteMatch<'p>forRoute"), "RouteMatch impl: {code}");
        // `capture` maps the field-name key to the variant field.
        assert!(code.contains("\"shelf\"=>") && code.contains("Some(*shelf)"), "capture arm: {code}");
    }

    #[test]
    fn no_router_is_emitted_without_router_type() {
        // By default (as rest_over_grpc relies on for its embedded router) no ZST
        // router or `RouteMatch` impl is emitted. `RouteMatch` is emitted only
        // together with the ZST, so its absence pins the whole block off.
        let file: syn::File =
            syn::parse2(generate_code(rules(&[("GetShelf", HttpMethod::Get, "/v1/shelves/{shelf}")]))).expect("valid Rust");
        let code = prettyplease::unparse(&file).replace(' ', "");
        assert!(!code.contains("RouteMatch"), "no RouteMatch impl by default: {code}");
        assert!(!code.contains("::Router"), "no `Router` trait impl by default: {code}");
    }

    #[test]
    fn generates_a_route_enum_with_a_variant_per_name() {
        // The `Route` enum drives `O(1)` jump-table dispatch: one variant per
        // distinct name, deduplicated (a name bound to two routes with the same
        // captures yields one variant), plus a `name` accessor recovering the
        // declared string. A capturing route becomes a struct variant.
        let file: syn::File = syn::parse2(generate_code(rules(&[
            ("ListShelves", HttpMethod::Get, "/v1/shelves"),
            ("GetShelf", HttpMethod::Get, "/v1/shelves/{shelf}"),
            ("GetShelf", HttpMethod::Delete, "/v1/shelves/{shelf}"),
        ])))
        .expect("valid Rust");
        let pretty = prettyplease::unparse(&file);
        assert!(pretty.contains("enum Route"), "{pretty}");
        assert!(pretty.contains("fn name"), "{pretty}");
        // The enum body runs from the `enum` keyword to the following `impl`.
        let enum_src = {
            let start = pretty.find("enum Route").expect("enum is emitted");
            let rest = &pretty[start..];
            &rest[..rest.find("impl").expect("an impl follows the enum")]
        };
        // Two routes share the `GetShelf` name and captures, so it appears once
        // as a variant — a struct variant carrying its `{shelf}` capture.
        assert_eq!(enum_src.matches("GetShelf").count(), 1, "{enum_src}");
        assert_eq!(enum_src.matches("ListShelves").count(), 1, "{enum_src}");
        assert!(enum_src.contains("GetShelf { shelf"), "{enum_src}");
        // `resolve` returns the matched route directly.
        assert!(
            pretty.contains("-> Option<Route<'p>>") || pretty.contains("Option<Route<'p>>"),
            "{pretty}"
        );
    }

    #[test]
    fn resolve_is_an_inherent_method_and_the_enum_name_is_configurable() {
        // With a configured `route_type`, the enum is renamed and `resolve` is an
        // inherent associated function of it — a single generated symbol — so
        // several routers can coexist in one scope and be called as `Name::resolve`.
        let options = GeneratorBuilder::default().route_type("BookRoute");
        let file: syn::File =
            syn::parse2(generate_code_with(rules(&[("GetBook", HttpMethod::Get, "/books/{book}")]), options)).expect("valid Rust");
        let flat = prettyplease::unparse(&file).replace(' ', "");
        assert!(flat.contains("enumBookRoute<'p>"), "{flat}");
        // `resolve` lives inside the enum's inherent impl, not as a free fn.
        assert!(flat.contains("impl<'p>BookRoute<'p>{"), "{flat}");
        assert!(flat.contains("fnresolve<__P>"), "{flat}");
        assert!(flat.contains("::core::option::Option<BookRoute<'p>>"), "{flat}");
    }

    #[test]
    fn non_capturing_resolve_binds_its_own_lifetime() {
        // With no captures the enum is non-generic, so `resolve` introduces `'p`
        // itself rather than taking it from the inherent impl.
        let file: syn::File = syn::parse2(generate_code(rules(&[("Health", HttpMethod::Get, "/health")]))).expect("valid Rust");
        let flat = prettyplease::unparse(&file).replace(' ', "");
        assert!(flat.contains("implRoute{"), "{flat}");
        assert!(flat.contains("fnresolve<'p,__P>"), "{flat}");
        assert!(flat.contains("::core::option::Option<Route>"), "{flat}");
    }

    #[test]
    fn generated_enum_implements_the_route_trait() {
        // Every generated enum implements `routerama::codegen_helpers::Route<'p>`,
        // forwarding to its inherent methods — a documented contract for generic
        // consumers.
        // Capturing router: the enum is `Route<'p>`.
        let capturing =
            prettyplease::unparse(&syn::parse2(generate_code(rules(&[("GetBook", HttpMethod::Get, "/books/{book}")]))).expect("valid"))
                .replace(' ', "");
        assert!(
            capturing.contains("impl<'p>::routerama::codegen_helpers::Route<'p>forRoute<'p>{"),
            "{capturing}"
        );

        // Capture-less router: the enum is non-generic, implemented for every `'p`.
        let unit = prettyplease::unparse(&syn::parse2(generate_code(rules(&[("Health", HttpMethod::Get, "/health")]))).expect("valid"))
            .replace(' ', "");
        assert!(unit.contains("impl<'p>::routerama::codegen_helpers::Route<'p>forRoute{"), "{unit}");

        // The trait path honors a custom `runtime_path`.
        let rerouted = prettyplease::unparse(
            &syn::parse2(generate_code_with(
                rules(&[("GetBook", HttpMethod::Get, "/books/{book}")]),
                GeneratorBuilder::default().runtime_path(quote::quote! { ::rt }),
            ))
            .expect("valid"),
        )
        .replace(' ', "");
        assert!(rerouted.contains("impl<'p>::rt::Route<'p>forRoute<'p>{"), "{rerouted}");
    }

    #[test]
    fn capturing_routes_become_struct_variants_and_non_capturing_stay_unit() {
        // A route with `{variable}` segments carries them as named `&'p str`
        // fields; a route with none is a unit variant. The enum is
        // lifetime-parameterized because at least one variant carries a field.
        let file: syn::File = syn::parse2(generate_code(rules(&[
            ("ListShelves", HttpMethod::Get, "/v1/shelves"),
            ("GetReview", HttpMethod::Get, "/v1/shelves/{shelf}/reviews/{review}"),
        ])))
        .expect("valid Rust");
        let pretty = prettyplease::unparse(&file);
        assert!(pretty.contains("enum Route<'p>"), "{pretty}");
        let enum_src = {
            let start = pretty.find("enum Route").expect("enum is emitted");
            let rest = &pretty[start..];
            &rest[..rest.find("impl").expect("an impl follows the enum")]
        };
        assert!(
            enum_src.contains("ListShelves,") || enum_src.contains("ListShelves ,"),
            "{enum_src}"
        );
        assert!(enum_src.contains("GetReview { shelf: &'p str, review: &'p str }"), "{enum_src}");
        // The resolved variant is constructed with its captured fields.
        assert!(pretty.contains("Route::GetReview"), "{pretty}");
    }

    #[test]
    fn a_dotted_variable_becomes_an_underscored_field() {
        // A dotted capture like `{shelf.id}` maps to a `shelf_id` field.
        let file: syn::File =
            syn::parse2(generate_code(rules(&[("GetShelf", HttpMethod::Get, "/v1/shelves/{shelf.id}")]))).expect("valid Rust");
        let pretty = prettyplease::unparse(&file);
        assert!(pretty.contains("shelf_id: &'p str"), "{pretty}");
    }

    #[test]
    fn a_router_with_no_captures_has_a_non_generic_route_enum() {
        // With no route capturing a variable, `Route` needs no lifetime.
        let file: syn::File = syn::parse2(generate_code(rules(&[("ListShelves", HttpMethod::Get, "/v1/shelves")]))).expect("valid Rust");
        let pretty = prettyplease::unparse(&file);
        assert!(pretty.contains("enum Route {"), "{pretty}");
        assert!(!pretty.contains("enum Route<"), "{pretty}");
    }

    #[test]
    fn reusing_a_name_with_different_captures_is_a_compile_error() {
        let code = generated(&[
            ("GetShelf", HttpMethod::Get, "/v1/shelves/{shelf}"),
            ("GetShelf", HttpMethod::Get, "/v2/shelves/{shelf}/books/{book}"),
        ]);
        assert!(code.contains("compile_error"), "{code}");
        assert!(code.contains("capture different path variables"), "{code}");
    }

    #[test]
    fn reusing_a_name_with_a_fieldless_binding_renders_none_in_the_diagnostic() {
        // One binding captures nothing and the other captures `{book}`, so the
        // conflict diagnostic formats the empty field set as `none`.
        let code = generated(&[
            ("GetShelf", HttpMethod::Get, "/v1/shelves"),
            ("GetShelf", HttpMethod::Get, "/v1/shelves/{book}"),
        ]);
        assert!(code.contains("compile_error"), "{code}");
        assert!(code.contains("none vs"), "{code}");
    }

    #[test]
    fn a_route_capturing_the_same_field_twice_is_a_compile_error() {
        // A single route whose template binds two variables to the same field
        // cannot map them into one struct field, so it is rejected.
        let code = generated(&[("GetPair", HttpMethod::Get, "/{shelf}/x/{shelf}")]);
        assert!(code.contains("compile_error"), "{code}");
        assert!(code.contains("same field"), "{code}");
    }

    #[test]
    fn resolve_constructs_the_variant_with_the_captured_field_name() {
        // The `return Some(Route::Variant { field: ... })` in the generated
        // `resolve` names each field after its captured variable (`{book}` →
        // `book`), matching the enum variant's field, so the emitted code is
        // internally consistent.
        let file: syn::File = syn::parse2(generate_code(rules(&[("GetBook", HttpMethod::Get, "/books/{book}")]))).expect("valid Rust");
        let flat: String = prettyplease::unparse(&file).split_whitespace().collect();
        assert!(flat.contains("Route::GetBook{book:&__body"), "{flat}");
    }

    #[test]
    fn route_enum_derives_the_canonical_traits() {
        // The enum is `Copy` and derives the full canonical comparison/hashing
        // set, so callers can freely compare, order, hash, and store it (e.g. in
        // a `BTreeMap`/`HashMap` keyed by route).
        let file: syn::File =
            syn::parse2(generate_code(rules(&[("GetShelf", HttpMethod::Get, "/v1/shelves/{shelf}")]))).expect("valid Rust");
        let pretty = prettyplease::unparse(&file);
        for trait_name in ["Clone", "Copy", "Debug", "PartialEq", "Eq", "PartialOrd", "Ord", "Hash"] {
            assert!(pretty.contains(trait_name), "derive is missing `{trait_name}`: {pretty}");
        }
    }

    #[test]
    fn route_enum_implements_display_and_as_ref_str() {
        // `Display` and `AsRef<str>` forward to `name`, so a matched route
        // formats and borrows as its declared name string.
        let file: syn::File =
            syn::parse2(generate_code(rules(&[("GetShelf", HttpMethod::Get, "/v1/shelves/{shelf}")]))).expect("valid Rust");
        let pretty = prettyplease::unparse(&file);
        assert!(pretty.contains("Display for Route"), "{pretty}");
        assert!(pretty.contains("AsRef<str> for Route"), "{pretty}");
    }

    #[test]
    fn a_name_that_is_not_an_identifier_is_a_compile_error() {
        let code = generated(&[("0:GetShelf", HttpMethod::Get, "/v1/shelves/{shelf}")]);
        assert!(code.contains("compile_error"), "{code}");
        assert!(code.contains("not a valid Rust identifier"), "{code}");
    }

    #[test]
    fn is_valid_variant_accepts_only_non_keyword_identifiers() {
        // Valid identifiers (used verbatim as enum variants).
        assert!(is_valid_variant("GetShelf"));
        assert!(is_valid_variant("_private"));
        assert!(is_valid_variant("Route2"));

        // Empty, non-identifier-first, and non-identifier-rest are all rejected.
        assert!(!is_valid_variant(""));
        assert!(!is_valid_variant("0Route"));
        assert!(!is_valid_variant("Get-Shelf"));

        // Reserved words cannot name a variant.
        assert!(!is_valid_variant("match"));
        assert!(!is_valid_variant("_"));
    }

    #[test]
    fn variant_ident_sanitizes_non_identifier_names() {
        // A valid name is used verbatim; an invalid one is sanitized to a
        // deterministic placeholder (the real error is a `compile_error!`).
        assert_eq!(variant_ident("GetShelf").to_string(), "GetShelf");
        assert_eq!(variant_ident("0:Get").to_string(), "_R_0_Get");
    }

    #[test]
    fn generated_router_parses_as_valid_rust() {
        let tokens = generate_code(rules(&[
            ("ListShelves", HttpMethod::Get, "/v1/shelves"),
            ("CreateShelf", HttpMethod::Post, "/v1/shelves"),
            ("GetShelf", HttpMethod::Get, "/v1/shelves/{shelf}"),
            ("ArchiveShelf", HttpMethod::Post, "/v1/shelves/{shelf}:archive"),
            ("GetTree", HttpMethod::Get, "/v1/tree/{path=**}"),
        ]));
        let file: syn::File = syn::parse2(tokens).expect("generated router is valid Rust");
        let pretty = prettyplease::unparse(&file);
        assert!(pretty.contains("fn resolve"));
        assert!(pretty.contains("routerama"));
    }

    #[test]
    fn empty_router_is_valid_and_matches_nothing() {
        let file: syn::File = syn::parse2(generate_code(std::iter::empty())).expect("valid");
        let pretty = prettyplease::unparse(&file);
        assert!(pretty.contains("fn resolve"));
    }

    #[test]
    fn conflicting_routes_emit_a_compile_error() {
        // Two GET routes with the same path shape map to different names; only the
        // first could ever match.
        let code = generated(&[
            ("GetBookA", HttpMethod::Get, "/v1/books/{book}"),
            ("GetBookB", HttpMethod::Get, "/v1/books/{other}"),
        ]);
        assert!(code.contains("compile_error"), "{code}");
        assert!(code.contains("conflicting routes"), "{code}");
    }

    #[test]
    fn no_verb_split_when_no_route_uses_a_verb() {
        // Without any custom verb, the generated code binds `__body = path`
        // directly rather than calling `split_verb`.
        let code = generated(&[("GetShelf", HttpMethod::Get, "/v1/shelves/{shelf}")]);
        assert!(!code.contains("split_verb"), "{code}");

        let with_verb = generated(&[("ArchiveShelf", HttpMethod::Post, "/v1/shelves/{shelf}:archive")]);
        assert!(with_verb.contains("split_verb"), "{with_verb}");
    }

    #[test]
    fn rest_capture_emitted_once() {
        // The `**` capture is sliced once for the matched variant's field; the
        // underlying trie produces exactly one capture site.
        let code = generate_code(rules(&[("GetTree", HttpMethod::Get, "/v1/{path=**}")]))
            .to_string()
            .replace(' ', "");
        assert_eq!(
            code.matches("__starts[1]..]").count(),
            1,
            "rest capture emitted once for the variant field: {code}"
        );
    }

    #[test]
    fn affix_route_generates_valid_rust_with_guards() {
        let tokens = generate_code(ext_rules(&[("GetFile", HttpMethod::Get, "/files/{name}.json")]));
        let file: syn::File = syn::parse2(tokens).expect("generated router is valid Rust");
        let pretty = prettyplease::unparse(&file);
        assert!(pretty.contains("ends_with"), "{pretty}");
        assert!(pretty.contains("GetFile"), "{pretty}");
    }

    #[test]
    fn affix_prefix_and_suffix_emit_both_guards() {
        let code = generated_ext(&[("GetImg", HttpMethod::Get, "/img-{id}.png")]);
        assert!(code.contains("starts_with"), "{code}");
        assert!(code.contains("ends_with"), "{code}");
    }

    #[test]
    fn affix_binding_slices_the_segment_middle() {
        // The captured value is the segment minus its literal prefix/suffix.
        let code = generated_ext(&[("GetFile", HttpMethod::Get, "/files/{name}.json")]).replace(' ', "");
        assert!(code.contains("__starts[1]+0..__ends[1]-5"), "{code}");
    }

    #[test]
    fn literal_takes_priority_over_affix_at_same_depth() {
        let tokens = generate_code(ext_rules(&[
            ("GetLatest", HttpMethod::Get, "/files/latest.json"),
            ("GetFile", HttpMethod::Get, "/files/{name}.json"),
        ]));
        // Both coexist; the literal edge is matched before the affix guard.
        let file: syn::File = syn::parse2(tokens).expect("valid Rust");
        let pretty = prettyplease::unparse(&file);
        let literal_pos = pretty.find("latest.json").expect("literal arm emitted");
        let affix_pos = pretty.find("ends_with").expect("affix guard emitted");
        assert!(literal_pos < affix_pos, "literal must precede affix:\n{pretty}");
    }

    fn generated_ext(specs: &[(&str, HttpMethod, &str)]) -> String {
        generate_code(ext_rules(specs)).to_string()
    }

    // Whitespace-stripped generated source, for asserting exact segment indices,
    // count guards, and binding slices (which pin the trie's depth/offset
    // arithmetic and the flattening of each segment kind).
    fn flat(specs: &[(&str, HttpMethod, &str)]) -> String {
        generated(specs).replace(' ', "")
    }

    #[test]
    fn literal_and_span_variable_bind_at_the_right_depth() {
        // `/v1/shelves/{shelf}` — two literals then a bounded variable at index 2.
        let code = flat(&[("GetShelf", HttpMethod::Get, "/v1/shelves/{shelf}")]);
        assert!(code.contains("\"v1\"=>"), "literal `v1` arm: {code}");
        assert!(code.contains("\"shelves\"=>"), "literal `shelves` arm: {code}");
        // The leaf fires only at exactly three segments (depth arithmetic).
        assert!(code.contains("__count==3"), "leaf gated on count 3: {code}");
        // The bound variable is a span slice at index 2, not the open-ended rest form.
        assert!(code.contains("__starts[2]..__ends[2]"), "span slice at index 2: {code}");
        assert!(!code.contains("__starts[2]..]"), "must not use rest form for a bounded var: {code}");
    }

    #[test]
    fn single_wildcard_is_guarded_on_a_non_empty_segment() {
        // `/v1/*` — a top-level single wildcard at depth 1.
        let code = flat(&[("Any", HttpMethod::Get, "/v1/*")]);
        assert!(
            code.contains("__ends[1]>__starts[1]"),
            "single wildcard non-empty guard at depth 1: {code}"
        );
        assert!(code.contains("__count==2"), "leaf gated on count 2: {code}");
    }

    #[test]
    fn rest_capture_uses_open_ended_slice_from_its_depth() {
        // `/v1/tree/{path=**}` — the `**` capture starts at index 2.
        let code = flat(&[("GetTree", HttpMethod::Get, "/v1/tree/{path=**}")]);
        assert!(code.contains("__count>=2"), "rest catch-all guarded by `>= depth`: {code}");
        assert!(
            code.contains("__starts[2]..]"),
            "rest capture is an open-ended slice from index 2: {code}"
        );
    }

    #[test]
    fn affix_guard_pins_the_prefix_and_suffix_lengths() {
        // `/img-{id}.png` — prefix `img-` (4) + suffix `.png` (4) = 8.
        let code = generated_ext(&[("GetImg", HttpMethod::Get, "/img-{id}.png")]).replace(' ', "");
        assert!(code.contains("__seg.len()>8"), "affix length guard is prefix+suffix = 8: {code}");
        assert!(code.contains("starts_with(b\"img-\")"), "affix prefix guard: {code}");
        assert!(code.contains("ends_with(b\".png\")"), "affix suffix guard: {code}");
        // The capture is the segment middle: start + prefix_len .. end - suffix_len.
        assert!(
            code.contains("__starts[0]+4..__ends[0]-4"),
            "affix binding slices off prefix/suffix: {code}"
        );
    }

    #[test]
    fn distinct_methods_at_the_same_node_each_get_an_arm() {
        // Same path, two methods — the method grouping must emit both arms.
        let code = flat(&[("ListX", HttpMethod::Get, "/v1/x"), ("CreateX", HttpMethod::Post, "/v1/x")]);
        assert!(code.contains("\"GET\"=>"), "GET arm present: {code}");
        assert!(code.contains("\"POST\"=>"), "POST arm present: {code}");
        // Two different methods do not conflict.
        assert!(!code.contains("compile_error"), "distinct methods must not conflict: {code}");
    }

    #[test]
    fn distinct_verbs_on_one_method_each_get_an_arm() {
        // Same method + path, two custom verbs — both verb arms must be emitted.
        let code = flat(&[
            ("Inspect", HttpMethod::Get, "/v1/shelves/{shelf}:inspect"),
            ("Watch", HttpMethod::Get, "/v1/shelves/{shelf}:watch"),
        ]);
        assert!(code.contains("Some(\"inspect\")"), "inspect verb arm: {code}");
        assert!(code.contains("Some(\"watch\")"), "watch verb arm: {code}");
        assert!(!code.contains("compile_error"), "distinct verbs must not conflict: {code}");
    }

    #[test]
    fn a_single_route_per_bucket_is_not_reported_as_a_conflict() {
        // One route per (method, verb) at a node must not emit a conflict — this
        // pins the `> 1` threshold (a `>= 1` would flag every route).
        let code = generated(&[("GetShelf", HttpMethod::Get, "/v1/shelves/{shelf}")]);
        assert!(!code.contains("compile_error"), "a lone route must never conflict: {code}");
    }

    #[test]
    fn a_segment_reading_node_binds_the_segment_slice() {
        // A node with literal (or affix) edges must read `__seg` before matching.
        let code = flat(&[("GetShelf", HttpMethod::Get, "/v1/shelves/{shelf}")]);
        assert!(
            code.contains("let__seg:&[u8]=&__body.as_bytes()[__starts[0]..__ends[0]]"),
            "root binds __seg: {code}"
        );
    }

    #[test]
    fn a_segment_after_an_affix_is_matched_one_level_deeper() {
        // `/a-{id}.z/tail` — the affix occupies index 0, so `tail` sits at index 1
        // and the leaf fires at exactly two segments. Pins the affix child's depth.
        let code = generated_ext(&[("Tail", HttpMethod::Get, "/a-{id}.z/tail")]).replace(' ', "");
        assert!(code.contains("\"tail\"=>"), "affix child literal is emitted: {code}");
        assert!(
            code.contains("__count==2"),
            "leaf one level below the affix fires at count 2: {code}"
        );
    }

    #[test]
    fn top_level_double_star_captures_the_remainder() {
        // A bare top-level `**` (not wrapped in a `{var=**}`) still flattens to a
        // rest atom and emits the open-ended catch-all.
        let code = flat(&[("All", HttpMethod::Get, "/v1/**")]);
        assert!(code.contains("__count>=1"), "top-level `**` is a catch-all from index 1: {code}");
    }

    #[test]
    fn variable_subtemplate_literal_is_flattened_into_a_match() {
        // `{name=shelves/*}` expands to a literal `shelves` then a `*`, so the
        // literal from the sub-template must appear as its own segment match.
        let code = flat(&[("Search", HttpMethod::Get, "/v1/{name=shelves/*}")]);
        assert!(
            code.contains("\"shelves\"=>"),
            "sub-template literal is flattened into a match arm: {code}"
        );
    }

    #[test]
    fn multiple_affixes_at_one_node_are_ordered_and_prefix_only_needs_no_suffix_guard() {
        // Two affix edges at the root exercise the specificity sort, and a
        // prefix-only affix (empty suffix) exercises the no-suffix-guard path.
        let code = generated_ext(&[("Ver", HttpMethod::Get, "/v{version}"), ("Rev", HttpMethod::Get, "/rev-{id}")]).replace(' ', "");
        // Prefix-only affixes emit a prefix guard but no `ends_with` suffix guard.
        assert!(code.contains("starts_with(b\"v\")"), "prefix guard for `v{{version}}`: {code}");
        assert!(code.contains("starts_with(b\"rev-\")"), "prefix guard for `rev-{{id}}`: {code}");
        assert!(!code.contains("ends_with"), "prefix-only affixes need no suffix guard: {code}");
        // The longer prefix (`rev-`, specificity 4) is guarded before the shorter
        // (`v`, specificity 1).
        let rev = code.find("starts_with(b\"rev-\")").expect("rev- guard present");
        let ver = code.find("starts_with(b\"v\")").expect("v guard present");
        assert!(rev < ver, "more specific affix is tried first: {code}");
    }
}
