[package]
name = "oxidizer_macros_impl"
description = "This crate is a private dependency of the `oxidizer` crate. You should never add this as a direct dependency. The entire API surface is unstable."
version.workspace = true
edition.workspace = true
rust-version.workspace = true
authors.workspace = true
license-file.workspace = true
readme.workspace = true
homepage.workspace = true
repository.workspace = true
keywords.workspace = true
categories.workspace = true
publish.workspace = true

[lib]
crate-type = ["lib"]

[dependencies]
darling = { workspace = true }
proc-macro2 = { workspace = true }
quote = { workspace = true }
syn = { workspace = true, default-features = true, features = ["full", "extra-traits"] }
mutants = { workspace = true }

[dev-dependencies]
insta = { workspace = true }
prettyplease = { workspace = true }

[lints]
workspace = true
