# Copyright (c) Microsoft Corporation.
# Licensed under the MIT License.

header = """
Copyright (c) Microsoft Corporation.
Licensed under the MIT License."""

# Imported verbatim from microsoft/rust_msvc_spectre_libs.
exclude = ["crates/msvc_spectre_libs"]
