coverage:
  precision: 1
  round: down
  range: 100..100
  status:
    project:
      default:
        target: 100
        threshold: "0"
        base: auto
    fundle_macros:  # API still WIP for now
      target: auto
      informational: true  
