coverage:
  precision: 1
  round: down
  range: 100..100
  status:
    project:
      default:
        target: 100
        threshold: "0"
        base: auto
ignore:
- "crates/testing_aids/**/*"
# this is a temporary fix, for some reason codecov ignores cfg option in the file itself
- "crates/ohno/src/test_util.rs"
