trigger:
- main

parameters:
- name: validationOsList
  type: object
  default:
  - linux
- name: validationProfiles
  type: object
  default:
  - dev
  - release
- name: previousVersion
  type: string
  default: 'HEAD^'

resources:
  repositories:
  # Internal repository that hosts the publishing template
  - repository: ox-sdk
    type: git
    name: ox-sdk
    ref: refs/heads/u/makolnek/esrp-gh-publish

extends:
  template: .pipelines/templates/OxidizerGitHub.Publish.yml@ox-sdk
  parameters:
    validationOsList: ${{ parameters.validationOsList }}
    validationProfiles: ${{ parameters.validationProfiles }}
    previousVersion: ${{ parameters.previousVersion }}
    pipelineType: 'Testing'