trigger:
- main

parameters:
- name: validationOsList
  type: object
  default:
  - linux
  - windows
- name: validationProfiles
  type: object
  default:
  - dev
  - release
- name: previousVersion
  type: string
  default: 'HEAD^'

resources:
  repositories:
  # Internal repository that hosts the publishing template
  - repository: ox-sdk
    type: git
    name: ox-sdk
    # Override this ref to point at a feature branch in ox-sdk when iterating
    # on the publishing template from the unofficial pipeline.
    ref: refs/heads/master

extends:
  template: .pipelines/templates/OxidizerGitHub.Publish.yml@ox-sdk
  parameters:
    validationOsList: ${{ parameters.validationOsList }}
    validationProfiles: ${{ parameters.validationProfiles }}
    previousVersion: ${{ parameters.previousVersion }}
    pipelineType: 'Testing'