// Copyright (c) Microsoft Corporation.
// Licensed under the MIT License.

/// One parameter set used to prepare a benchmark fixture.
///
/// # Example
///
/// ```
/// struct Size(usize);
///
/// impl metabench::BenchmarkCase for Size {
///     fn name(&self) -> String {
///         format!("length={}", self.0)
///     }
/// }
/// ```
pub trait BenchmarkCase: 'static {
    /// Returns the stable name included in benchmark identity.
    fn name(&self) -> String;
}

impl BenchmarkCase for () {
    fn name(&self) -> String {
        String::new()
    }
}

/// Supplies parameter values to stateless data-driven benchmark methods.
///
/// # Example
///
/// ```
/// use metabench::{BenchmarkCase, BenchmarkCases};
///
/// struct Size(usize);
/// impl BenchmarkCase for Size {
///     fn name(&self) -> String {
///         self.0.to_string()
///     }
/// }
///
/// struct Searches;
/// impl BenchmarkCases for Searches {
///     type Case = Size;
///     fn cases() -> impl IntoIterator<Item = Self::Case> {
///         [Size(8), Size(64)]
///     }
/// }
/// ```
pub trait BenchmarkCases: Sized + 'static {
    /// Parameter value passed to each benchmark method.
    type Case: BenchmarkCase;

    /// Returns all parameter values measured for every benchmark method.
    fn cases() -> impl IntoIterator<Item = Self::Case>;
}

/// A data-driven benchmark fixture created fresh for every measured operation.
///
/// # Example
///
/// ```
/// use metabench::{BenchmarkCase, Fixture};
///
/// struct Size(usize);
/// impl BenchmarkCase for Size {
///     fn name(&self) -> String {
///         self.0.to_string()
///     }
/// }
///
/// struct Buffer(Vec<u8>);
/// impl Fixture for Buffer {
///     type Case = Size;
///     fn cases() -> impl IntoIterator<Item = Self::Case> {
///         [Size(16)]
///     }
///     fn setup(case: &Self::Case) -> Self {
///         Self(vec![0; case.0])
///     }
/// }
/// ```
pub trait Fixture: Sized + 'static {
    /// Parameter value used to construct this fixture.
    type Case: BenchmarkCase;

    /// Returns all parameter values measured for every benchmark method.
    fn cases() -> impl IntoIterator<Item = Self::Case>;

    /// Creates fresh benchmark state outside the measured region.
    fn setup(case: &Self::Case) -> Self;
}

/// A single-case benchmark fixture created fresh for every measured operation.
///
/// # Example
///
/// ```
/// struct Buffer(Vec<u8>);
///
/// impl metabench::SimpleFixture for Buffer {
///     fn setup() -> Self {
///         Self(vec![0; 16])
///     }
/// }
/// ```
pub trait SimpleFixture: Sized + 'static {
    /// Creates fresh benchmark state outside the measured region.
    fn setup() -> Self;
}

impl<T> Fixture for T
where
    T: SimpleFixture,
{
    type Case = ();

    fn cases() -> impl IntoIterator<Item = Self::Case> {
        [()]
    }

    fn setup(_case: &Self::Case) -> Self {
        <Self as SimpleFixture>::setup()
    }
}

/// Keeps fixture state and method output alive until measurement has stopped.
#[doc(hidden)]
pub struct PreparedOutput<Output, State> {
    _output: Output,
    _state: State,
}

impl<Output, State> PreparedOutput<Output, State> {
    /// Creates a value whose fields are destroyed outside measurement.
    pub const fn new(output: Output, state: State) -> Self {
        Self {
            _output: output,
            _state: state,
        }
    }
}

impl<Output, State> std::fmt::Debug for PreparedOutput<Output, State> {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        f.write_str("PreparedOutput { .. }")
    }
}

/// Registration contract generated by `#[metabench::benchmarks]`.
#[doc(hidden)]
pub trait BenchmarkGroupDefinition {
    /// Registers every generated method and case in the runtime suite.
    fn register(suite: &mut crate::BenchmarkSuite);
}
