// Copyright (c) Microsoft Corporation.
// Licensed under the MIT License.

use std::ffi::{OsStr, OsString};
use std::fmt::Write as _;
use std::io::{self, Write as _};
use std::path::{Path, PathBuf};
use std::process::{Command, ExitStatus, Stdio};
use std::time::{Duration, Instant};
use std::{env, fs, thread};

use command_group::{CommandGroup, GroupChild};

use crate::arguments::{Arguments, FailureMode, WORKER_MODE_ENV, WORKER_TOKEN_ENV, paths_alias};
use crate::artifact::{self, ArtifactDirectory};
use crate::error::Error;
use crate::identity::BenchmarkIdentity;
use crate::mode::Mode;
use crate::report::BenchmarkReport;
use crate::{allocation, perf, vtune};

const HELP: &str = "\
Usage: BENCHMARK [METABENCH OPTIONS] [ENGINE OPTIONS]

Engines:
  --criterion              Run Criterion benchmarks
  --gungraun               Run Gungraun benchmarks
  --perf                   Measure Linux hardware performance counters
  --vtune                  Measure hardware events with Intel VTune
  --allocations            Measure allocations with alloc_tracker
  --all-engines            Run every engine compiled into this target

Native engine options (repeat once per argument):
  --criterion-arg ARG
  --gungraun-arg ARG
  --perf-arg ARG
  --vtune-arg ARG

Metabench options:
  --export-md PATH          Override the default Markdown report path
  --export-json PATH        Override the default JSON report path
  --output PATH             Override both paths with PATH.md and PATH.json
  --no-output               Do not write report files
  --baseline PATH           Override the previous report used as the baseline
  --no-baseline             Do not compare against an existing report
  --list                    Use each selected engine's native listing mode
                            (cross-engine canonical filtering is unavailable)
  --timeout DURATION        Limit each engine worker (for example 30s or 5m)
  --fail-fast               Stop after the first engine failure
  --keep-going              Continue through engine failures (default)
  --regression-threshold PERCENT
  --show-engine-output      Show raw child-engine stdout and stderr
  -h, --help

Arguments after -- are forwarded when exactly one engine is selected.
BENCH_ENGINE may select criterion, gungraun, perf, vtune, or allocations when no selector is present.
CRITERION_HOME and GUNGRAUN_HOME retain the 20 most recent metabench runs
under each home's .metabench-runs directory.
";
const WORKER_POLL_INTERVAL: Duration = Duration::from_millis(25);
const TERMINATION_REAP_GRACE: Duration = Duration::from_secs(1);

/// Native engine entry points compiled into a benchmark target.
#[derive(Clone, Copy, Debug)]
pub struct EngineSet {
    criterion: fn(),
    criterion_unit: Option<&'static str>,
    gungraun: fn(),
}

impl EngineSet {
    /// Creates a target containing both native engines and Criterion unit metadata.
    #[must_use]
    pub const fn both_with_unit(criterion: fn(), gungraun: fn(), criterion_unit: Option<&'static str>) -> Self {
        Self {
            criterion,
            criterion_unit,
            gungraun,
        }
    }

    fn run(self, mode: Mode) {
        let entry = match mode {
            Mode::Criterion | Mode::Perf | Mode::Vtune | Mode::Allocations => self.criterion,
            Mode::Gungraun => self.gungraun,
        };
        entry();
    }
}

/// Runs a benchmark target generated by [`crate::main!`].
///
/// # Errors
///
/// Returns an error when orchestration, a native engine, artifact parsing, or
/// report generation fails.
#[doc(hidden)]
pub fn run(engines: EngineSet, identities: &'static [BenchmarkIdentity], benchmark_target: &'static str) -> Result<(), String> {
    run_inner(engines, identities, benchmark_target).map_err(|error| error.to_string())
}

fn run_inner(engines: EngineSet, identities: &'static [BenchmarkIdentity], benchmark_target: &'static str) -> Result<(), Error> {
    // Resolve the measurement gates before any engine starts collecting, so
    // their one-time setup is not charged to the first workload invocation.
    perf::prime();
    allocation::prime();
    vtune::prime();

    if env::args_os().nth(1).as_deref() == Some(OsStr::new("--gungraun-run")) {
        engines.run(Mode::Gungraun);
        return Ok(());
    }
    if let Some(worker_mode) = env::var_os(WORKER_MODE_ENV) {
        consume_worker_token()?;
        let mode = Mode::from_os_str(&worker_mode)?;
        engines.run(mode);
        if mode == Mode::Allocations {
            allocation::write_worker_artifact()?;
        } else if mode == Mode::Perf {
            perf::finish_worker()?;
        } else if mode == Mode::Vtune {
            vtune::finish_worker()?;
        }
        return Ok(());
    }

    let mut arguments = Arguments::parse()?;
    if arguments.help {
        io::stdout().write_all(HELP.as_bytes()).map_err(Error::HelpOutput)?;
        return Ok(());
    }
    run_parent(&mut arguments, engines, identities, benchmark_target)
}

/// Determines whether a `--list` invocation must add [`Mode::Criterion`] to the native modes so
/// that a non-native engine (allocations, perf, or vtune) has a Criterion instance to list
/// benchmark identities from.
fn needs_criterion_for_listing(list: bool, modes: &[Mode], native_modes: &[Mode]) -> bool {
    list && (modes.contains(&Mode::Allocations) || modes.contains(&Mode::Perf) || modes.contains(&Mode::Vtune))
        && !native_modes.contains(&Mode::Criterion)
}

fn run_parent(
    arguments: &mut Arguments,
    engines: EngineSet,
    identities: &[BenchmarkIdentity],
    benchmark_target: &str,
) -> Result<(), Error> {
    let modes = arguments.modes.clone();
    arguments.finalize_native_args(&modes)?;
    let executable = current_executable(env::current_exe)?;
    let report_root = default_target_directory_with(|name| env::var_os(name), env::current_dir)?
        .join("metabench")
        .join(benchmark_target);
    let artifacts = (!arguments.list).then(|| ArtifactDirectory::create(&report_root)).transpose()?;
    let mut native_modes = modes
        .iter()
        .copied()
        .filter(|mode| !matches!(mode, Mode::Allocations | Mode::Perf | Mode::Vtune))
        .collect::<Vec<_>>();
    if needs_criterion_for_listing(arguments.list, &modes, &native_modes) {
        native_modes.push(Mode::Criterion);
    }
    let mut summary = orchestrate_modes(&native_modes, arguments.failure_mode, |mode| {
        if !arguments.list {
            print_progress(mode)?;
        }
        let launched = launch_worker(
            mode,
            &executable,
            arguments.args_for(mode),
            artifacts.as_ref(),
            arguments.show_engine_output || arguments.list,
            arguments.timeout,
        );
        let manifest = if let Some(artifacts) = &artifacts {
            artifact::write_run_manifest(
                artifacts.path(),
                artifacts.root(),
                benchmark_target,
                mode.as_str(),
                arguments.args_for(mode),
                launched.as_ref().ok().copied(),
            )
        } else {
            Ok(())
        };
        combine_results(launched.and_then(|status| ensure_success(mode, status)), manifest)
    })?;
    let mut failures = std::mem::take(&mut summary.failures);

    if arguments.list {
        return finish_failures(failures);
    }

    let probe_results = run_probe_modes(
        &modes,
        &executable,
        arguments,
        artifacts.as_ref().expect("non-list runs always create an artifact directory"),
        identities,
        &mut summary,
        &mut failures,
    )?;

    if let Some(artifacts) = &artifacts
        && !summary.completed.is_empty()
    {
        let complete_run = failures.is_empty();
        let report = build_report(
            artifacts,
            &summary.completed,
            identities,
            arguments,
            benchmark_target,
            engines.criterion_unit,
            probe_results,
            complete_run,
        )
        .and_then(|(report, json_path, markdown_path)| write_console_report(&report, json_path.as_deref(), markdown_path.as_deref()));
        if let Err(error) = report {
            append_failure(&mut failures, error);
        }
    }
    finish_failures(failures)
}

fn run_probe_modes(
    modes: &[Mode],
    executable: &Path,
    arguments: &Arguments,
    artifacts: &ArtifactDirectory,
    identities: &[BenchmarkIdentity],
    summary: &mut EngineRunSummary,
    failures: &mut Vec<String>,
) -> Result<Vec<crate::report::NativeResult>, Error> {
    let mut results = Vec::new();
    for &mode in modes {
        if !matches!(mode, Mode::Allocations | Mode::Perf | Mode::Vtune) {
            continue;
        }
        print_progress(mode)?;
        let measured = match mode {
            Mode::Allocations => run_allocations(
                executable,
                arguments,
                artifacts,
                identities,
                summary.completed.contains(&Mode::Criterion),
            ),
            Mode::Perf => run_perf(
                executable,
                arguments,
                artifacts,
                identities,
                summary.completed.contains(&Mode::Criterion),
            ),
            Mode::Vtune => run_vtune(
                executable,
                arguments,
                artifacts,
                identities,
                summary.completed.contains(&Mode::Criterion),
            ),
            Mode::Criterion | Mode::Gungraun => unreachable!("the probe mode list is fixed above"),
        };
        match measured {
            Ok(measured) => {
                summary.completed.push(mode);
                results.extend(measured);
            }
            Err(error) if arguments.failure_mode == FailureMode::KeepGoing => append_failure(failures, error),
            Err(error) => return Err(error),
        }
    }
    Ok(results)
}

#[derive(Debug)]
struct EngineRunSummary {
    completed: Vec<Mode>,
    failures: Vec<String>,
}

fn orchestrate_modes(
    modes: &[Mode],
    failure_mode: FailureMode,
    mut execute: impl FnMut(Mode) -> Result<(), Error>,
) -> Result<EngineRunSummary, Error> {
    let mut completed = Vec::new();
    let mut failures = Vec::new();
    for &mode in modes {
        match execute(mode) {
            Ok(()) => completed.push(mode),
            Err(error) if failure_mode == FailureMode::KeepGoing => append_failure(&mut failures, error),
            Err(error) => return Err(error),
        }
    }
    Ok(EngineRunSummary { completed, failures })
}

fn append_failure(failures: &mut Vec<String>, error: Error) {
    match error {
        Error::MultipleModeFailures(nested) => failures.extend(nested),
        error => failures.push(error.to_string()),
    }
}

fn combine_results<T>(primary: Result<T, Error>, secondary: Result<(), Error>) -> Result<T, Error> {
    match (primary, secondary) {
        (Ok(value), Ok(())) => Ok(value),
        (Err(error), Ok(())) | (Ok(_), Err(error)) => Err(error),
        (Err(primary), Err(secondary)) => Err(multiple_failures([primary, secondary])),
    }
}

fn finish_failures(failures: Vec<String>) -> Result<(), Error> {
    if failures.is_empty() {
        Ok(())
    } else {
        Err(Error::MultipleModeFailures(failures))
    }
}

fn multiple_failures<const N: usize>(errors: [Error; N]) -> Error {
    let mut failures = Vec::new();
    for error in errors {
        match error {
            Error::MultipleModeFailures(nested) => failures.extend(nested),
            error => failures.push(error.to_string()),
        }
    }
    Error::MultipleModeFailures(failures)
}

#[expect(
    clippy::too_many_arguments,
    reason = "report assembly is explicit about every input that shapes the final report"
)]
fn build_report(
    artifacts: &ArtifactDirectory,
    completed: &[Mode],
    identities: &[BenchmarkIdentity],
    arguments: &Arguments,
    benchmark_target: &str,
    criterion_unit: Option<&str>,
    probe_results: Vec<crate::report::NativeResult>,
    complete_run: bool,
) -> Result<(BenchmarkReport, Option<PathBuf>, Option<PathBuf>), Error> {
    let mut results = probe_results;
    if completed.contains(&Mode::Criterion) {
        let criterion = artifact::parse_criterion(&artifacts.criterion_path(), artifacts.root(), identities, criterion_unit)?;
        artifact::record_discovered_identities(artifacts.path(), Mode::Criterion.as_str(), &criterion)?;
        results.extend(criterion);
    }
    if completed.contains(&Mode::Gungraun) {
        let gungraun = artifact::parse_gungraun(&artifacts.gungraun_path(), artifacts.root(), identities)?;
        artifact::record_discovered_identities(artifacts.path(), Mode::Gungraun.as_str(), &gungraun)?;
        results.extend(gungraun);
    }
    let mut report = BenchmarkReport::from_results(
        results,
        completed.iter().map(|mode| mode.as_str().to_owned()).collect(),
        artifacts.root().to_string_lossy().into_owned(),
    )?;
    let (json_path, markdown_path) = report_paths(arguments, benchmark_target)?;
    let baseline = if let Some(path) = arguments.baseline.as_deref() {
        Some((path, false))
    } else if arguments.automatic_baseline {
        json_path
            .as_deref()
            .filter(|path| path.is_file() && !BenchmarkReport::publication_incomplete(path))
            .map(|path| (path, true))
    } else {
        None
    };
    if let Some((path, automatic)) = baseline
        && let Some(baseline) = read_baseline(path, automatic)?
    {
        report.apply_baseline(&baseline, arguments.regression_threshold)?;
    }
    // A `--keep-going` run where some selected engine failed must not overwrite the
    // rolling automatic-baseline file with results from only the engines that
    // completed: a later, fully successful run would then read that partial file
    // back as its baseline and silently lose comparisons for the engine that failed
    // here. Route such partial runs to sibling `.partial` paths instead, so the
    // diagnostics remain visible without corrupting the rolling baseline; only a
    // run where every selected engine succeeded is allowed to promote the baseline.
    let (json_path, markdown_path) = if complete_run {
        (json_path, markdown_path)
    } else {
        (
            json_path.as_deref().map(partial_report_path),
            markdown_path.as_deref().map(partial_report_path),
        )
    };
    report.write_reports(json_path.as_deref(), markdown_path.as_deref())?;
    Ok((report, json_path, markdown_path))
}

/// Derives a sibling path for partial-run diagnostics, e.g. `report.json` becomes
/// `report.partial.json`, keeping such output clearly separate from the rolling
/// baseline file at the original path.
fn partial_report_path(path: &Path) -> PathBuf {
    match path.extension().and_then(OsStr::to_str) {
        Some(extension) => path.with_extension(format!("partial.{extension}")),
        None => path.with_extension("partial"),
    }
}

fn read_baseline(path: &Path, automatic: bool) -> Result<Option<BenchmarkReport>, Error> {
    match BenchmarkReport::read_json(path) {
        Ok(report) => Ok(Some(report)),
        Err(Error::UnsupportedReportSchema { .. }) if automatic => Ok(None),
        Err(error) => Err(error),
    }
}

#[derive(Debug)]
struct CriterionProbeTarget {
    identity: String,
    native_identity: String,
}

fn criterion_probe_arguments(criterion_arguments: &[OsString], native_identity: &str) -> Vec<OsString> {
    let mut probe_arguments = criterion_arguments.to_vec();
    probe_arguments.push(native_identity.into());
    if !probe_arguments.iter().any(|argument| argument == "--exact") {
        probe_arguments.push("--exact".into());
    }
    probe_arguments
}

fn run_allocations(
    executable: &Path,
    arguments: &Arguments,
    artifacts: &ArtifactDirectory,
    identities: &[BenchmarkIdentity],
    criterion_completed: bool,
) -> Result<Vec<crate::report::NativeResult>, Error> {
    let targets = if criterion_completed {
        artifact::parse_criterion(&artifacts.criterion_path(), artifacts.root(), identities, None)?
            .into_iter()
            .filter_map(|result| {
                artifact::allocation_criterion_identity(&result.native_identity, identities).map(|identity| CriterionProbeTarget {
                    identity,
                    native_identity: result.native_identity,
                })
            })
            .collect()
    } else {
        discover_criterion_probe_targets(
            executable,
            artifacts,
            identities,
            arguments.args_for(Mode::Criterion),
            arguments.timeout,
        )?
    };
    if targets.is_empty() {
        return Err(Error::ArtifactFormat {
            path: artifacts.path().to_owned(),
            message: "contains no registered Criterion benchmarks for allocation tracking".to_owned(),
        });
    }

    let mut results = Vec::with_capacity(targets.len());
    for (index, target) in targets.into_iter().enumerate() {
        let artifact_path = artifacts.path().join("allocations").join(format!("{index}.json"));
        let criterion_home = artifacts.path().join("allocation-probes").join(index.to_string());
        let native_arguments = criterion_probe_arguments(arguments.criterion_args(), &target.native_identity);
        let status = launch_worker_with(
            Mode::Allocations,
            executable,
            &native_arguments,
            Some(artifacts),
            arguments.show_engine_output,
            arguments.timeout,
            Some(&criterion_home),
            None,
            Some((&target.identity, &artifact_path)),
        )?;
        ensure_success(Mode::Allocations, status)?;
        let relative_path = artifact_path
            .strip_prefix(artifacts.root())
            .unwrap_or(&artifact_path)
            .to_string_lossy()
            .replace(std::path::MAIN_SEPARATOR, "/");
        results.push(allocation::read_artifact(&artifact_path, target.native_identity, relative_path)?);
    }
    Ok(results)
}

fn discover_criterion_probe_targets(
    executable: &Path,
    artifacts: &ArtifactDirectory,
    identities: &[BenchmarkIdentity],
    criterion_arguments: &[OsString],
    timeout: Option<Duration>,
) -> Result<Vec<CriterionProbeTarget>, Error> {
    let output_path = artifacts.path().join("criterion-probe-discovery.txt");
    let criterion_home = artifacts.path().join("criterion-probe-discovery");
    let mut discovery_arguments = criterion_arguments
        .iter()
        .filter(|argument| {
            ![
                OsStr::new("--bench"),
                OsStr::new("--test"),
                OsStr::new("--list"),
                OsStr::new("--exact"),
            ]
            .contains(&argument.as_os_str())
        })
        .cloned()
        .collect::<Vec<_>>();
    discovery_arguments.push("--list".into());
    let status = launch_worker_with(
        Mode::Criterion,
        executable,
        &discovery_arguments,
        Some(artifacts),
        false,
        timeout,
        Some(&criterion_home),
        Some(&output_path),
        None,
    )?;
    ensure_success(Mode::Criterion, status)?;
    let output = fs::read_to_string(&output_path).map_err(|source| Error::ArtifactIo {
        path: output_path.clone(),
        source,
    })?;
    let targets = output
        .lines()
        .filter_map(|line| line.strip_suffix(": benchmark"))
        .filter_map(|native_identity| {
            artifact::allocation_criterion_identity(native_identity, identities).map(|identity| CriterionProbeTarget {
                identity,
                native_identity: native_identity.to_owned(),
            })
        })
        .collect::<Vec<_>>();
    if targets.is_empty() {
        return Err(Error::ArtifactFormat {
            path: output_path,
            message: "Criterion listing contained no benchmarks".to_owned(),
        });
    }
    Ok(targets)
}

fn run_perf(
    executable: &Path,
    arguments: &Arguments,
    artifacts: &ArtifactDirectory,
    identities: &[BenchmarkIdentity],
    criterion_completed: bool,
) -> Result<Vec<crate::report::NativeResult>, Error> {
    if !cfg!(target_os = "linux") {
        return Err(Error::UnsupportedMode {
            mode: Mode::Perf.as_str(),
            reason: "Linux perf is supported only on Linux",
        });
    }
    let targets = if criterion_completed {
        artifact::parse_criterion(&artifacts.criterion_path(), artifacts.root(), identities, None)?
            .into_iter()
            .filter_map(|result| {
                artifact::allocation_criterion_identity(&result.native_identity, identities).map(|identity| CriterionProbeTarget {
                    identity,
                    native_identity: result.native_identity,
                })
            })
            .collect()
    } else {
        discover_criterion_probe_targets(executable, artifacts, identities, arguments.criterion_args(), arguments.timeout)?
    };
    if targets.is_empty() {
        return Err(Error::ArtifactFormat {
            path: artifacts.path().to_owned(),
            message: "contains no registered Criterion benchmarks for perf measurement".to_owned(),
        });
    }

    let mut results = Vec::with_capacity(targets.len());
    for (index, target) in targets.into_iter().enumerate() {
        let artifact_path = artifacts.perf_path(index);
        let criterion_home = artifacts.path().join("perf-probes").join(index.to_string());
        let native_arguments = criterion_probe_arguments(arguments.criterion_args(), &target.native_identity);
        let status = launch_perf_worker(
            executable,
            &native_arguments,
            arguments.args_for(Mode::Perf),
            &artifact_path,
            &criterion_home,
            arguments.show_engine_output,
            arguments.timeout,
        )?;
        ensure_success(Mode::Perf, status)?;
        results.push(artifact::parse_perf(
            &artifact_path,
            artifacts.root(),
            target.identity,
            target.native_identity,
        )?);
    }
    Ok(results)
}

#[cfg(target_os = "linux")]
fn launch_perf_worker(
    executable: &Path,
    native_arguments: &[OsString],
    perf_arguments: &[OsString],
    artifact_path: &Path,
    criterion_home: &Path,
    show_output: bool,
    timeout: Option<Duration>,
) -> Result<ExitStatus, Error> {
    use nix::sys::stat::Mode as FileMode;
    use nix::unistd::mkfifo;

    validate_perf_arguments(perf_arguments)?;
    let fifo_directory = tempfile::Builder::new()
        .prefix("metabench-perf-")
        .tempdir()
        .map_err(Error::PerfControl)?;
    let control = fifo_directory.path().join("control");
    let acknowledgement = fifo_directory.path().join("ack");
    let control_text = control
        .to_str()
        .ok_or_else(|| Error::PerfControl(io::Error::new(io::ErrorKind::InvalidInput, "perf control FIFO path is not UTF-8")))?;
    let acknowledgement_text = acknowledgement.to_str().ok_or_else(|| {
        Error::PerfControl(io::Error::new(
            io::ErrorKind::InvalidInput,
            "perf acknowledgement FIFO path is not UTF-8",
        ))
    })?;
    if control_text.contains(',') || acknowledgement_text.contains(',') {
        return Err(Error::PerfControl(io::Error::new(
            io::ErrorKind::InvalidInput,
            "perf control FIFO paths cannot contain commas",
        )));
    }
    mkfifo(&control, FileMode::S_IRUSR | FileMode::S_IWUSR).map_err(|error| Error::PerfControl(error.into()))?;
    mkfifo(&acknowledgement, FileMode::S_IRUSR | FileMode::S_IWUSR).map_err(|error| Error::PerfControl(error.into()))?;
    let control_guard = fs::OpenOptions::new()
        .read(true)
        .write(true)
        .open(&control)
        .map_err(Error::PerfControl)?;
    let acknowledgement_guard = fs::OpenOptions::new()
        .read(true)
        .write(true)
        .open(&acknowledgement)
        .map_err(Error::PerfControl)?;
    if let Some(parent) = artifact_path.parent() {
        fs::create_dir_all(parent).map_err(|source| Error::ArtifactIo {
            path: parent.to_owned(),
            source,
        })?;
    }

    let control_argument = format!("fifo:{control_text},{acknowledgement_text}");
    let mut command = Command::new("perf");
    command
        .arg("stat")
        .args(perf_arguments)
        .args([
            "--event=instructions:u",
            "--event=cycles:u",
            "--event=branches:u",
            "--event=branch-misses:u",
            "--event=cache-references:u",
            "--event=cache-misses:u",
            "--delay=-1",
            "--json-output",
            "--output",
        ])
        .arg(artifact_path)
        .arg("--control")
        .arg(control_argument)
        .arg("--")
        .arg(executable)
        .args(native_arguments)
        .env(WORKER_MODE_ENV, Mode::Perf.as_str())
        .env("CRITERION_HOME", criterion_home)
        .env_remove("CARGO_CRITERION_PORT")
        .env(perf::CONTROL_ENV, &control)
        .env(perf::ACK_ENV, &acknowledgement);
    if !show_output {
        command.stdout(Stdio::null()).stderr(Stdio::null());
    }

    let token = create_worker_token()?;
    command.env(WORKER_TOKEN_ENV, token.path());
    let status = wait_for_worker(Mode::Perf, &mut command, timeout);
    drop(control_guard);
    drop(acknowledgement_guard);
    let cleanup = match token.path().try_exists() {
        Ok(true) => fs::remove_dir(token.path()).map_err(Error::ConsumeWorkerToken),
        Ok(false) => Ok(()),
        Err(error) => Err(Error::ConsumeWorkerToken(error)),
    };
    combine_results(status, cleanup)
}

#[cfg(not(target_os = "linux"))]
fn launch_perf_worker(
    _executable: &Path,
    _native_arguments: &[OsString],
    _perf_arguments: &[OsString],
    _artifact_path: &Path,
    _criterion_home: &Path,
    _show_output: bool,
    _timeout: Option<Duration>,
) -> Result<ExitStatus, Error> {
    Err(Error::UnsupportedMode {
        mode: Mode::Perf.as_str(),
        reason: "Linux perf is supported only on Linux",
    })
}

#[cfg(any(target_os = "linux", test))]
fn validate_perf_arguments(arguments: &[OsString]) -> Result<(), Error> {
    for argument in arguments {
        let value = argument.to_string_lossy();
        if [
            "--",
            "-o",
            "-r",
            "-I",
            "--output",
            "--json-output",
            "--control",
            "--delay",
            "--repeat",
            "--interval-print",
        ]
        .iter()
        .any(|reserved| value == *reserved || value.starts_with(&format!("{reserved}=")))
            || value.starts_with("-o") && value.len() > 2
            || value.starts_with("-r") && value.len() > 2
            || value.starts_with("-I") && value.len() > 2
        {
            return Err(Error::UnsupportedPerfArgument(argument.clone()));
        }
    }
    Ok(())
}

fn run_vtune(
    executable: &Path,
    arguments: &Arguments,
    artifacts: &ArtifactDirectory,
    identities: &[BenchmarkIdentity],
    criterion_completed: bool,
) -> Result<Vec<crate::report::NativeResult>, Error> {
    let targets = if criterion_completed {
        artifact::parse_criterion(&artifacts.criterion_path(), artifacts.root(), identities, None)?
            .into_iter()
            .filter_map(|result| {
                artifact::allocation_criterion_identity(&result.native_identity, identities).map(|identity| CriterionProbeTarget {
                    identity,
                    native_identity: result.native_identity,
                })
            })
            .collect()
    } else {
        discover_criterion_probe_targets(executable, artifacts, identities, arguments.criterion_args(), arguments.timeout)?
    };
    if targets.is_empty() {
        return Err(Error::ArtifactFormat {
            path: artifacts.path().to_owned(),
            message: "contains no registered Criterion benchmarks for vtune measurement".to_owned(),
        });
    }

    let mut results = Vec::with_capacity(targets.len());
    for (index, target) in targets.into_iter().enumerate() {
        let artifact_path = artifacts.vtune_path(index);
        let result_dir = artifacts.vtune_result_path(index);
        let criterion_home = artifacts.path().join("vtune-probes").join(index.to_string());
        let native_arguments = criterion_probe_arguments(arguments.criterion_args(), &target.native_identity);
        let status = launch_vtune_worker(
            executable,
            &native_arguments,
            arguments.args_for(Mode::Vtune),
            &artifact_path,
            &result_dir,
            &criterion_home,
            arguments.show_engine_output,
            arguments.timeout,
        )?;
        ensure_success(Mode::Vtune, status)?;
        results.push(artifact::parse_vtune(
            &artifact_path,
            artifacts.root(),
            target.identity,
            target.native_identity,
        )?);
    }
    Ok(results)
}

/// Launches a benchmark worker under a paused `VTune` collection and, once it
/// exits, extracts a CSV hardware-event report from the collection result.
///
/// This mirrors `launch_perf_worker`'s shape, but `VTune`'s own CLI takes the
/// place of the FIFO-based `perf --control` protocol: the collection starts
/// paused (`--start-paused`) and is resumed/paused around the annotated
/// workload by [`crate::vtune::begin`]/[`crate::vtune::Guard::drop`] via
/// `vtune -command resume|pause -r <result-dir>`, run from inside the worker
/// process. The exact `vtune` invocation below (analysis type, knobs, and
/// report format) is our best documented understanding of the `VTune`
/// command-line interface and has not been verified against a live
/// installation in this repository's environment; adjust it here if a real
/// `VTune` version's CLI differs. See [`crate::vtune`] for the control-protocol
/// references.
#[expect(
    clippy::too_many_arguments,
    reason = "worker process configuration is explicit at the process boundary"
)]
fn launch_vtune_worker(
    executable: &Path,
    native_arguments: &[OsString],
    vtune_arguments: &[OsString],
    artifact_path: &Path,
    result_dir: &Path,
    criterion_home: &Path,
    show_output: bool,
    timeout: Option<Duration>,
) -> Result<ExitStatus, Error> {
    validate_vtune_arguments(vtune_arguments)?;
    if let Some(parent) = result_dir.parent() {
        fs::create_dir_all(parent).map_err(|source| Error::ArtifactIo {
            path: parent.to_owned(),
            source,
        })?;
    }
    if let Some(parent) = artifact_path.parent() {
        fs::create_dir_all(parent).map_err(|source| Error::ArtifactIo {
            path: parent.to_owned(),
            source,
        })?;
    }

    let mut command = Command::new("vtune");
    command
        .arg("-collect-with")
        .arg("runsa")
        .args(vtune_arguments)
        .arg("--start-paused")
        .arg("-result-dir")
        .arg(result_dir)
        .env(WORKER_MODE_ENV, Mode::Vtune.as_str())
        .env("CRITERION_HOME", criterion_home)
        .env_remove("CARGO_CRITERION_PORT")
        .env(vtune::RESULT_DIR_ENV, result_dir)
        .arg("--")
        .arg(executable)
        .args(native_arguments);
    if !show_output {
        command.stdout(Stdio::null()).stderr(Stdio::null());
    }

    let token = create_worker_token()?;
    command.env(WORKER_TOKEN_ENV, token.path());
    let status = wait_for_worker(Mode::Vtune, &mut command, timeout);
    let cleanup = match token.path().try_exists() {
        Ok(true) => fs::remove_dir(token.path()).map_err(Error::ConsumeWorkerToken),
        Ok(false) => Ok(()),
        Err(error) => Err(Error::ConsumeWorkerToken(error)),
    };
    let status = combine_results(status, cleanup)?;
    if !status.success() {
        return Ok(status);
    }

    let mut report_command = Command::new("vtune");
    report_command
        .args(["-report", "hw-events", "-r"])
        .arg(result_dir)
        .args(["-format", "csv", "-report-output"])
        .arg(artifact_path);
    if !show_output {
        report_command.stdout(Stdio::null()).stderr(Stdio::null());
    }
    wait_for_worker(Mode::Vtune, &mut report_command, timeout)
}

fn validate_vtune_arguments(arguments: &[OsString]) -> Result<(), Error> {
    for argument in arguments {
        let value = argument.to_string_lossy();
        if [
            "--",
            "-r",
            "-collect",
            "-c",
            "-collect-with",
            "-result-dir",
            "-start-paused",
            "--start-paused",
            "-report",
            "-R",
            "-report-output",
            "-format",
            "-command",
            "-C",
        ]
        .iter()
        .any(|reserved| value == *reserved || value.starts_with(&format!("{reserved}=")))
        {
            return Err(Error::UnsupportedVtuneArgument(argument.clone()));
        }
    }
    Ok(())
}

fn launch_worker(
    mode: Mode,
    executable: &Path,
    native_arguments: &[OsString],
    artifacts: Option<&ArtifactDirectory>,
    show_output: bool,
    timeout: Option<Duration>,
) -> Result<ExitStatus, Error> {
    // Gungraun measures via Valgrind/Callgrind, which is only available on Linux. An
    // explicit `--gungraun` request off Linux must fail clearly here rather than
    // spawning a worker that cannot actually measure anything.
    if mode == Mode::Gungraun && !cfg!(target_os = "linux") {
        return Err(Error::UnsupportedMode {
            mode: Mode::Gungraun.as_str(),
            reason: "Gungraun is supported only on Linux",
        });
    }
    launch_worker_with(
        mode,
        executable,
        native_arguments,
        artifacts,
        show_output,
        timeout,
        None,
        None,
        None,
    )
}

#[expect(
    clippy::too_many_arguments,
    reason = "worker process configuration is explicit at the process boundary"
)]
fn launch_worker_with(
    mode: Mode,
    executable: &Path,
    native_arguments: &[OsString],
    artifacts: Option<&ArtifactDirectory>,
    show_output: bool,
    timeout: Option<Duration>,
    criterion_home: Option<&Path>,
    captured_stdout: Option<&Path>,
    allocation_target: Option<(&str, &Path)>,
) -> Result<ExitStatus, Error> {
    let mut command = Command::new(executable);
    command.args(native_arguments).env(WORKER_MODE_ENV, mode.as_str());
    if let Some(artifacts) = artifacts {
        match mode {
            Mode::Criterion | Mode::Allocations => {
                command
                    .env(
                        "CRITERION_HOME",
                        criterion_home.map_or_else(|| artifacts.criterion_path(), Path::to_owned),
                    )
                    .env_remove("CARGO_CRITERION_PORT");
            }
            Mode::Gungraun => {
                command
                    .env("GUNGRAUN_HOME", artifacts.gungraun_path())
                    .env("GUNGRAUN_SAVE_SUMMARY", "json");
            }
            Mode::Perf => unreachable!("perf workers use launch_perf_worker"),
            Mode::Vtune => unreachable!("vtune workers use launch_vtune_worker"),
        }
    }
    if let Some((identity, path)) = allocation_target {
        command.env(allocation::IDENTITY_ENV, identity).env(allocation::ARTIFACT_ENV, path);
    }
    if let Some(path) = captured_stdout {
        if let Some(parent) = path.parent() {
            fs::create_dir_all(parent).map_err(|source| Error::ArtifactIo {
                path: parent.to_owned(),
                source,
            })?;
        }
        let output = fs::File::create(path).map_err(|source| Error::ArtifactIo {
            path: path.to_owned(),
            source,
        })?;
        command.stdout(output);
        if !show_output {
            command.stderr(Stdio::null());
        }
    } else if !show_output {
        command.stdout(Stdio::null()).stderr(Stdio::null());
    }
    let token = create_worker_token()?;
    command.env(WORKER_TOKEN_ENV, token.path());
    let status = wait_for_worker(mode, &mut command, timeout);
    let cleanup = match token.path().try_exists() {
        Ok(true) => fs::remove_dir(token.path()).map_err(Error::ConsumeWorkerToken),
        Ok(false) => Ok(()),
        Err(error) => Err(Error::ConsumeWorkerToken(error)),
    };
    match (status, cleanup) {
        (Ok(status), Ok(())) => Ok(status),
        (Err(error), Ok(())) | (Ok(_), Err(error)) => Err(error),
        (Err(worker), Err(cleanup)) => Err(multiple_failures([worker, cleanup])),
    }
}

fn wait_for_worker(mode: Mode, command: &mut Command, timeout: Option<Duration>) -> Result<ExitStatus, Error> {
    let mut child = command.group_spawn().map_err(|source| Error::Spawn {
        mode: mode.as_str(),
        source,
    })?;
    wait_for_process(mode, &mut child, timeout, &SystemClock)
}

trait WorkerProcess {
    fn try_wait(&mut self) -> io::Result<Option<ExitStatus>>;
    fn kill(&mut self) -> io::Result<()>;
    fn wait(&mut self) -> io::Result<ExitStatus>;
}

impl WorkerProcess for GroupChild {
    fn try_wait(&mut self) -> io::Result<Option<ExitStatus>> {
        self.try_wait()
    }

    fn kill(&mut self) -> io::Result<()> {
        self.kill()
    }

    fn wait(&mut self) -> io::Result<ExitStatus> {
        self.wait()
    }
}

trait Clock {
    type Mark;

    fn mark(&self) -> Self::Mark;
    fn elapsed(&self, mark: &Self::Mark) -> Duration;
    fn sleep(&self, duration: Duration);
}

struct SystemClock;

impl Clock for SystemClock {
    type Mark = Instant;

    fn mark(&self) -> Self::Mark {
        Instant::now()
    }

    fn elapsed(&self, mark: &Self::Mark) -> Duration {
        mark.elapsed()
    }

    fn sleep(&self, duration: Duration) {
        thread::sleep(duration);
    }
}

fn wait_for_process(
    mode: Mode,
    child: &mut impl WorkerProcess,
    timeout: Option<Duration>,
    clock: &impl Clock,
) -> Result<ExitStatus, Error> {
    let Some(timeout) = timeout else {
        return child.wait().map_err(|source| spawn_error(mode, source));
    };
    let started = clock.mark();
    loop {
        if let Some(status) = child.try_wait().map_err(|source| spawn_error(mode, source))? {
            return Ok(status);
        }
        if clock.elapsed(&started) >= timeout {
            return terminate_timed_out_worker(mode, child, timeout, clock);
        }
        clock.sleep(WORKER_POLL_INTERVAL);
    }
}

fn terminate_timed_out_worker(
    mode: Mode,
    child: &mut impl WorkerProcess,
    timeout: Duration,
    clock: &impl Clock,
) -> Result<ExitStatus, Error> {
    let timed_out = || Error::WorkerTimedOut {
        mode: mode.as_str(),
        timeout,
    };
    if let Err(kill) = child.kill() {
        return match child.try_wait() {
            Ok(Some(status)) => Ok(status),
            Ok(None) => Err(termination_error(mode, kill)),
            Err(wait) => Err(multiple_failures([termination_error(mode, kill), termination_error(mode, wait)])),
        };
    }

    let termination_started = clock.mark();
    loop {
        match child.try_wait() {
            Ok(Some(_status)) => return Err(timed_out()),
            Ok(None) if clock.elapsed(&termination_started) < TERMINATION_REAP_GRACE => {
                clock.sleep(WORKER_POLL_INTERVAL);
            }
            Ok(None) => return Err(timed_out()),
            Err(wait) => return Err(multiple_failures([timed_out(), termination_error(mode, wait)])),
        }
    }
}

fn spawn_error(mode: Mode, source: io::Error) -> Error {
    Error::Spawn {
        mode: mode.as_str(),
        source,
    }
}

fn termination_error(mode: Mode, source: io::Error) -> Error {
    Error::WorkerTermination {
        mode: mode.as_str(),
        source,
    }
}

fn ensure_success(mode: Mode, status: ExitStatus) -> Result<(), Error> {
    if status.success() {
        Ok(())
    } else {
        Err(Error::WorkerFailed {
            mode: mode.as_str(),
            code: status.code(),
        })
    }
}

fn print_progress(mode: Mode) -> Result<(), Error> {
    let mut stdout = io::stdout().lock();
    write_progress(&mut stdout, mode)
}

fn write_progress(mut output: impl io::Write, mode: Mode) -> Result<(), Error> {
    writeln!(output, "Running {} benchmarks...", mode.as_str()).map_err(Error::ConsoleOutput)?;
    output.flush().map_err(Error::ConsoleOutput)
}

fn write_console_report(report: &BenchmarkReport, json_path: Option<&Path>, markdown_path: Option<&Path>) -> Result<(), Error> {
    let mut output = String::from("\n");
    output.push_str(&report.render_console_table());
    output.push('\n');
    if let (Some(json_path), Some(markdown_path)) = (json_path, markdown_path) {
        let _ = writeln!(output, "Generated {}", json_path.display());
        let _ = writeln!(output, "Generated {}", markdown_path.display());
    }
    write_console_output(io::stdout(), &output)
}

fn write_console_output(mut destination: impl io::Write, output: &str) -> Result<(), Error> {
    destination.write_all(output.as_bytes()).map_err(Error::ConsoleOutput)
}

fn report_paths(arguments: &Arguments, benchmark_target: &str) -> Result<(Option<PathBuf>, Option<PathBuf>), Error> {
    let root = default_target_directory_with(|name| env::var_os(name), env::current_dir)?
        .join("metabench")
        .join(benchmark_target);
    report_paths_with_root(arguments, &root)
}

fn report_paths_with_root(arguments: &Arguments, root: &Path) -> Result<(Option<PathBuf>, Option<PathBuf>), Error> {
    if arguments.no_output {
        return Ok((None, None));
    }
    let paths = (
        arguments.export_json.clone().or_else(|| Some(root.join("report.json"))),
        arguments.export_markdown.clone().or_else(|| Some(root.join("report.md"))),
    );
    if let (Some(json), Some(markdown)) = &paths
        && paths_alias(json, markdown)
    {
        return Err(Error::ConflictingOutputOptions);
    }
    Ok(paths)
}

fn default_target_directory_with(
    var_os: impl Fn(&str) -> Option<OsString>,
    current_dir: impl FnOnce() -> io::Result<PathBuf>,
) -> Result<PathBuf, Error> {
    if let Some(directory) = var_os("CARGO_TARGET_DIR") {
        return Ok(directory.into());
    }
    let current = current_dir().map_err(Error::CurrentDirectory)?;
    let workspace = current
        .ancestors()
        .find(|directory| is_workspace_manifest(&directory.join("Cargo.toml")))
        .unwrap_or(&current);
    Ok(workspace.join("target"))
}

fn current_executable(current_exe: impl FnOnce() -> io::Result<PathBuf>) -> Result<PathBuf, Error> {
    current_exe().map_err(Error::CurrentExecutable)
}

fn is_workspace_manifest(path: &Path) -> bool {
    fs::read_to_string(path).is_ok_and(|manifest| manifest.lines().any(|line| line.trim() == "[workspace]"))
}

struct WorkerToken {
    directory: tempfile::TempDir,
}

impl WorkerToken {
    fn path(&self) -> &Path {
        self.directory.path()
    }
}

fn create_worker_token() -> Result<WorkerToken, Error> {
    tempfile::Builder::new()
        .prefix("metabench-worker-")
        .tempdir()
        .map(|directory| WorkerToken { directory })
        .map_err(Error::CreateWorkerToken)
}

fn consume_worker_token() -> Result<(), Error> {
    let token = env::var_os(WORKER_TOKEN_ENV);
    consume_worker_token_from(token.as_deref(), &env::temp_dir())
}

fn consume_worker_token_from(token: Option<&OsStr>, temporary_directory: &Path) -> Result<(), Error> {
    let Some(token) = token else {
        return Err(Error::StaleWorkerMarker);
    };
    let token = PathBuf::from(token);
    if token.parent() != Some(temporary_directory)
        || token
            .file_name()
            .and_then(OsStr::to_str)
            .and_then(|name| name.strip_prefix("metabench-worker-"))
            .is_none_or(str::is_empty)
    {
        return Err(Error::StaleWorkerMarker);
    }
    fs::remove_dir(token).map_err(Error::ConsumeWorkerToken)
}

#[cfg_attr(coverage_nightly, coverage(off))]
#[cfg(test)]
mod tests {
    use std::cell::Cell;
    use std::collections::VecDeque;

    use super::*;

    #[test]
    fn criterion_probe_arguments_preserve_configuration_and_select_one_target() {
        let configured = [OsString::from("--sample-size"), OsString::from("20"), OsString::from("--bench")];

        assert_eq!(
            criterion_probe_arguments(&configured, "group/benchmark"),
            ["--sample-size", "20", "--bench", "group/benchmark", "--exact"]
        );
    }

    #[test]
    fn needs_criterion_for_listing_requires_list_a_native_only_engine_and_absence_of_criterion() {
        // Not listing: never inject Criterion, regardless of the other modes.
        assert!(!needs_criterion_for_listing(false, &[Mode::Vtune], &[]));
        // Listing, but only native (non-Perf/Allocations/Vtune) modes selected: nothing to inject for.
        assert!(!needs_criterion_for_listing(true, &[Mode::Criterion], &[Mode::Criterion]));
        // Listing with Criterion already present among the native modes: no duplicate injection.
        assert!(!needs_criterion_for_listing(true, &[Mode::Vtune], &[Mode::Criterion]));
        // Listing with each non-native engine selected and no Criterion present yet: inject it.
        assert!(needs_criterion_for_listing(true, &[Mode::Allocations], &[]));
        assert!(needs_criterion_for_listing(true, &[Mode::Perf], &[]));
        assert!(needs_criterion_for_listing(true, &[Mode::Vtune], &[]));
    }

    #[cfg(unix)]
    fn exit_status(code: i32) -> ExitStatus {
        use std::os::unix::process::ExitStatusExt as _;

        ExitStatus::from_raw(code << 8)
    }

    #[cfg(windows)]
    fn exit_status(code: i32) -> ExitStatus {
        use std::os::windows::process::ExitStatusExt as _;

        ExitStatus::from_raw(u32::try_from(code).unwrap())
    }

    struct FakeClock {
        elapsed: Cell<Duration>,
    }

    impl FakeClock {
        fn new() -> Self {
            Self {
                elapsed: Cell::new(Duration::ZERO),
            }
        }
    }

    impl Clock for FakeClock {
        type Mark = Duration;

        fn mark(&self) -> Self::Mark {
            self.elapsed.get()
        }

        fn elapsed(&self, mark: &Self::Mark) -> Duration {
            self.elapsed.get().saturating_sub(*mark)
        }

        fn sleep(&self, duration: Duration) {
            self.elapsed.set(self.elapsed.get() + duration);
        }
    }

    struct FakeProcess {
        try_wait: VecDeque<io::Result<Option<ExitStatus>>>,
        kill: Option<io::Result<()>>,
        wait: Option<io::Result<ExitStatus>>,
        kill_calls: usize,
        wait_calls: usize,
    }

    impl FakeProcess {
        fn new(try_wait: impl IntoIterator<Item = io::Result<Option<ExitStatus>>>) -> Self {
            Self {
                try_wait: try_wait.into_iter().collect(),
                kill: Some(Ok(())),
                wait: Some(Ok(exit_status(0))),
                kill_calls: 0,
                wait_calls: 0,
            }
        }
    }

    impl WorkerProcess for FakeProcess {
        fn try_wait(&mut self) -> io::Result<Option<ExitStatus>> {
            self.try_wait.pop_front().unwrap_or(Ok(None))
        }

        fn kill(&mut self) -> io::Result<()> {
            self.kill_calls += 1;
            self.kill.take().unwrap_or_else(|| Err(io::Error::other("kill called twice")))
        }

        fn wait(&mut self) -> io::Result<ExitStatus> {
            self.wait_calls += 1;
            self.wait.take().unwrap_or_else(|| Err(io::Error::other("wait called twice")))
        }
    }

    struct FailingOutput;

    impl io::Write for FailingOutput {
        fn write(&mut self, _buffer: &[u8]) -> io::Result<usize> {
            Err(io::Error::other("output unavailable"))
        }

        fn flush(&mut self) -> io::Result<()> {
            Ok(())
        }
    }

    #[test]
    fn incompatible_automatic_baselines_are_ignored() {
        let directory = tempfile::tempdir().unwrap();
        let path = directory.path().join("report.json");
        fs::write(
            &path,
            r#"{
                "schema_version": 7,
                "metadata": {
                    "timestamp_utc": "",
                    "target_triple": "",
                    "rustc_version": "",
                    "host_cpu": "",
                    "profile": "",
                    "compiler_flags": null,
                    "measured_backends": [],
                    "artifact_root": ""
                },
                "entries": []
            }"#,
        )
        .unwrap();

        assert!(read_baseline(&path, true).unwrap().is_none());
        assert!(matches!(
            read_baseline(&path, false),
            Err(Error::UnsupportedReportSchema { found: 7, expected: 8, .. })
        ));
    }

    #[test]
    fn perf_arguments_cannot_override_measurement_protocol() {
        for argument in [
            "--",
            "-o",
            "-oresult.json",
            "--output=result.json",
            "--json-output",
            "--control=fifo:a,b",
            "--delay=1",
            "-r5",
            "--repeat=5",
            "-I100",
            "--interval-print=100",
        ] {
            assert!(matches!(
                validate_perf_arguments(&[argument.into()]),
                Err(Error::UnsupportedPerfArgument(_))
            ));
        }
        validate_perf_arguments(&["--event=cpu-clock".into(), "--no-scale".into()]).unwrap();
    }

    #[test]
    fn vtune_arguments_cannot_override_measurement_protocol() {
        for argument in [
            "--",
            "-r",
            "-r=result",
            "-collect",
            "-c",
            "-c=pause",
            "-collect-with",
            "-result-dir",
            "-result-dir=result",
            "-start-paused",
            "--start-paused",
            "-report",
            "-R",
            "-R=hw-events",
            "-report-output",
            "-format",
            "-command",
            "-C",
            "-C=pause",
        ] {
            assert!(matches!(
                validate_vtune_arguments(&[argument.into()]),
                Err(Error::UnsupportedVtuneArgument(_))
            ));
        }
        validate_vtune_arguments(&["-knob".into(), "event-config=INST_RETIRED.ANY".into()]).unwrap();
    }

    #[test]
    fn timeout_kills_reaps_and_reports_timeout() {
        let mut process = FakeProcess::new([Ok(None), Ok(None), Ok(Some(exit_status(9)))]);
        let clock = FakeClock::new();

        let error = wait_for_process(Mode::Criterion, &mut process, Some(Duration::from_millis(25)), &clock).unwrap_err();

        assert!(matches!(error, Error::WorkerTimedOut { .. }));
        assert_eq!(process.kill_calls, 1);
        assert_eq!(process.wait_calls, 0);
        assert_eq!(clock.elapsed.get(), Duration::from_millis(25));
    }

    #[test]
    fn worker_exit_before_deadline_is_returned_without_termination() {
        let mut process = FakeProcess::new([Ok(Some(exit_status(3)))]);
        let clock = FakeClock::new();

        let status = wait_for_process(Mode::Criterion, &mut process, Some(Duration::from_secs(1)), &clock).unwrap();

        assert_eq!(status.code(), Some(3));
        assert_eq!(process.kill_calls, 0);
        assert_eq!(process.wait_calls, 0);
    }

    #[test]
    fn timeout_distinguishes_exit_race_after_failed_kill() {
        let mut process = FakeProcess::new([Ok(None), Ok(None), Ok(Some(exit_status(0)))]);
        process.kill = Some(Err(io::Error::new(io::ErrorKind::InvalidInput, "already exited")));
        let clock = FakeClock::new();

        let status = wait_for_process(Mode::Gungraun, &mut process, Some(Duration::from_millis(25)), &clock).unwrap();

        assert!(status.success());
        assert_eq!(process.kill_calls, 1);
        assert_eq!(process.wait_calls, 0);
    }

    #[test]
    fn failed_termination_is_bounded_without_blocking_wait() {
        let mut process = FakeProcess::new([Ok(None), Ok(None), Ok(None)]);
        process.kill = Some(Err(io::Error::new(io::ErrorKind::PermissionDenied, "kill denied")));
        let clock = FakeClock::new();

        let error = wait_for_process(Mode::Criterion, &mut process, Some(Duration::from_millis(25)), &clock).unwrap_err();

        assert!(matches!(error, Error::WorkerTermination { .. }));
        assert_eq!(process.wait_calls, 0);
        assert_eq!(clock.elapsed.get(), Duration::from_millis(25));
    }

    #[test]
    fn failed_kill_and_reap_preserve_both_errors() {
        let mut process = FakeProcess::new([Ok(None), Ok(None), Err(io::Error::other("race check failed"))]);
        process.kill = Some(Err(io::Error::other("kill failed")));
        let clock = FakeClock::new();

        let error = wait_for_process(Mode::Criterion, &mut process, Some(Duration::from_millis(25)), &clock)
            .unwrap_err()
            .to_string();

        assert!(error.contains("kill failed"));
        assert!(error.contains("race check failed"));
        assert_eq!(process.wait_calls, 0);
    }

    #[test]
    fn successful_kill_has_bounded_reap_grace() {
        let mut process = FakeProcess::new([Ok(None), Ok(None)]);
        let clock = FakeClock::new();

        let error = wait_for_process(Mode::Criterion, &mut process, Some(Duration::from_millis(25)), &clock).unwrap_err();

        assert!(matches!(error, Error::WorkerTimedOut { .. }));
        assert_eq!(clock.elapsed.get(), Duration::from_millis(25) + TERMINATION_REAP_GRACE);
        assert_eq!(process.wait_calls, 0);
    }

    #[test]
    fn timeout_preserves_reap_error_alongside_timeout() {
        let mut process = FakeProcess::new([Ok(None), Ok(None), Err(io::Error::other("reap failed"))]);
        let clock = FakeClock::new();

        let error = wait_for_process(Mode::Criterion, &mut process, Some(Duration::from_millis(25)), &clock)
            .unwrap_err()
            .to_string();

        assert!(error.contains("criterion worker exceeded"));
        assert!(error.contains("reap failed"));
    }

    #[test]
    fn blocking_wait_is_used_only_without_timeout() {
        let mut process = FakeProcess::new([]);
        let clock = FakeClock::new();

        assert!(wait_for_process(Mode::Criterion, &mut process, None, &clock).unwrap().success());
        assert_eq!(process.wait_calls, 1);
        assert_eq!(process.kill_calls, 0);
    }

    #[test]
    fn orchestration_routes_modes_and_flattens_all_failures() {
        let mut routed = Vec::new();
        let summary = orchestrate_modes(&Mode::ALL, FailureMode::KeepGoing, |mode| {
            routed.push(mode);
            if mode == Mode::Criterion {
                combine_results::<()>(
                    Err(Error::WorkerFailed {
                        mode: "criterion",
                        code: Some(7),
                    }),
                    Err(Error::ArtifactIo {
                        path: "criterion-manifest.json".into(),
                        source: io::Error::other("manifest failed"),
                    }),
                )
            } else {
                Ok(())
            }
        })
        .unwrap();

        assert_eq!(routed, Mode::ALL);
        assert_eq!(summary.completed, [Mode::Gungraun, Mode::Perf, Mode::Vtune, Mode::Allocations]);
        assert_eq!(summary.failures.len(), 2);
        assert!(summary.failures[0].contains("status 7"));
        assert!(summary.failures[1].contains("manifest failed"));
    }

    #[test]
    fn fail_fast_preserves_launch_and_manifest_failures_and_stops() {
        let mut calls = 0;
        let error = orchestrate_modes(&Mode::ALL, FailureMode::FailFast, |_mode| {
            calls += 1;
            combine_results::<()>(
                Err(Error::Spawn {
                    mode: "criterion",
                    source: io::Error::other("launch failed"),
                }),
                Err(Error::ArtifactIo {
                    path: "manifest.json".into(),
                    source: io::Error::other("manifest failed"),
                }),
            )
        })
        .unwrap_err()
        .to_string();

        assert_eq!(calls, 1);
        assert!(error.contains("launch failed"));
        assert!(error.contains("manifest failed"));
    }

    #[test]
    fn cleanup_failure_is_retained_with_existing_aggregates() {
        let mut failures = vec!["earlier engine failure".to_owned()];
        append_failure(
            &mut failures,
            multiple_failures([
                Error::ConsumeWorkerToken(io::Error::other("token cleanup failed")),
                Error::ConsoleOutput(io::Error::other("console failed")),
            ]),
        );

        assert_eq!(failures.len(), 3);
        assert!(failures[1].contains("token cleanup failed"));
        assert!(failures[2].contains("console failed"));
    }

    #[test]
    fn worker_token_validation_is_deterministic_and_single_use() {
        let root = tempfile::tempdir().unwrap();
        let valid = root.path().join("metabench-worker-valid");
        fs::create_dir(&valid).unwrap();

        consume_worker_token_from(Some(valid.as_os_str()), root.path()).unwrap();
        assert!(matches!(
            consume_worker_token_from(Some(valid.as_os_str()), root.path()),
            Err(Error::ConsumeWorkerToken(_))
        ));
        assert!(matches!(
            consume_worker_token_from(None, root.path()),
            Err(Error::StaleWorkerMarker)
        ));

        let malformed = root.path().join("worker-invalid");
        fs::create_dir(&malformed).unwrap();
        assert!(matches!(
            consume_worker_token_from(Some(malformed.as_os_str()), root.path()),
            Err(Error::StaleWorkerMarker)
        ));
        let empty_suffix = root.path().join("metabench-worker-");
        fs::create_dir(&empty_suffix).unwrap();
        assert!(matches!(
            consume_worker_token_from(Some(empty_suffix.as_os_str()), root.path()),
            Err(Error::StaleWorkerMarker)
        ));

        let foreign_root = tempfile::tempdir().unwrap();
        let foreign = foreign_root.path().join("metabench-worker-foreign");
        fs::create_dir(&foreign).unwrap();
        assert!(matches!(
            consume_worker_token_from(Some(foreign.as_os_str()), root.path()),
            Err(Error::StaleWorkerMarker)
        ));
    }

    #[test]
    fn report_paths_reject_explicit_alias_of_derived_default() {
        let root = tempfile::tempdir().unwrap();
        let mut arguments = Arguments::parse_from(["--export-json".into(), root.path().join("report.md").into()], None).unwrap();

        assert!(matches!(
            report_paths_with_root(&arguments, root.path()),
            Err(Error::ConflictingOutputOptions)
        ));

        arguments.no_output = true;
        assert_eq!(report_paths_with_root(&arguments, root.path()).unwrap(), (None, None));
    }

    #[test]
    fn environment_and_output_boundaries_map_exact_errors() {
        assert_eq!(
            default_target_directory_with(
                |name| (name == "CARGO_TARGET_DIR").then(|| OsString::from("custom-target")),
                || Err(io::Error::other("must not be called")),
            )
            .unwrap(),
            PathBuf::from("custom-target")
        );
        assert!(matches!(
            current_executable(|| Err(io::Error::other("no executable"))),
            Err(Error::CurrentExecutable(_))
        ));
        assert!(matches!(
            default_target_directory_with(|_| None, || Err(io::Error::other("no directory"))),
            Err(Error::CurrentDirectory(_))
        ));

        let mut progress = Vec::new();
        write_progress(&mut progress, Mode::Criterion).unwrap();
        assert_eq!(progress, b"Running criterion benchmarks...\n");

        assert!(matches!(
            write_console_output(FailingOutput, "report"),
            Err(Error::ConsoleOutput(_))
        ));
    }
}
