// Copyright (c) Microsoft Corporation.
// Licensed under the MIT License.

/// `(rpc, method, path template)` triples describing the benchmarked service's
/// routes, shared by the build script and the `grs_router_vs_matchit` benchmark.
pub static ROUTES: &[(&str, &str, &str)] = &[
    ("ListUsers", "GET", "/v1/users"),
    ("CreateUser", "POST", "/v1/users"),
    ("GetUser", "GET", "/v1/users/{user}"),
    ("UpdateUser", "PATCH", "/v1/users/{user}"),
    ("DeleteUser", "DELETE", "/v1/users/{user}"),
    ("ListUserRepos", "GET", "/v1/users/{user}/repos"),
    ("ListUserFollowers", "GET", "/v1/users/{user}/followers"),
    ("ListUserFollowing", "GET", "/v1/users/{user}/following"),
    ("ListUserGists", "GET", "/v1/users/{user}/gists"),
    ("ListUserStarred", "GET", "/v1/users/{user}/starred"),
    ("GetRepo", "GET", "/v1/repos/{owner}/{repo}"),
    ("UpdateRepo", "PATCH", "/v1/repos/{owner}/{repo}"),
    ("DeleteRepo", "DELETE", "/v1/repos/{owner}/{repo}"),
    ("ListBranches", "GET", "/v1/repos/{owner}/{repo}/branches"),
    ("GetBranch", "GET", "/v1/repos/{owner}/{repo}/branches/{branch}"),
    ("ListCommits", "GET", "/v1/repos/{owner}/{repo}/commits"),
    ("GetCommit", "GET", "/v1/repos/{owner}/{repo}/commits/{sha}"),
    ("GetContents", "GET", "/v1/repos/{owner}/{repo}/contents/{path=**}"),
    ("ListTags", "GET", "/v1/repos/{owner}/{repo}/tags"),
    ("ListLanguages", "GET", "/v1/repos/{owner}/{repo}/languages"),
    ("ListIssues", "GET", "/v1/repos/{owner}/{repo}/issues"),
    ("CreateIssue", "POST", "/v1/repos/{owner}/{repo}/issues"),
    ("GetIssue", "GET", "/v1/repos/{owner}/{repo}/issues/{issue}"),
    ("UpdateIssue", "PATCH", "/v1/repos/{owner}/{repo}/issues/{issue}"),
    ("ListIssueComments", "GET", "/v1/repos/{owner}/{repo}/issues/{issue}/comments"),
    ("CreateIssueComment", "POST", "/v1/repos/{owner}/{repo}/issues/{issue}/comments"),
    ("GetIssueComment", "GET", "/v1/repos/{owner}/{repo}/issues/{issue}/comments/{comment}"),
    ("ListIssueLabels", "GET", "/v1/repos/{owner}/{repo}/issues/{issue}/labels"),
    ("ListPulls", "GET", "/v1/repos/{owner}/{repo}/pulls"),
    ("CreatePull", "POST", "/v1/repos/{owner}/{repo}/pulls"),
    ("GetPull", "GET", "/v1/repos/{owner}/{repo}/pulls/{pull}"),
    ("UpdatePull", "PATCH", "/v1/repos/{owner}/{repo}/pulls/{pull}"),
    ("ListPullCommits", "GET", "/v1/repos/{owner}/{repo}/pulls/{pull}/commits"),
    ("ListPullFiles", "GET", "/v1/repos/{owner}/{repo}/pulls/{pull}/files"),
    ("MergePull", "PUT", "/v1/repos/{owner}/{repo}/pulls/{pull}/merge"),
    ("GetOrg", "GET", "/v1/orgs/{org}"),
    ("ListOrgMembers", "GET", "/v1/orgs/{org}/members"),
    ("GetOrgMember", "GET", "/v1/orgs/{org}/members/{user}"),
    ("ListOrgRepos", "GET", "/v1/orgs/{org}/repos"),
    ("ListOrgTeams", "GET", "/v1/orgs/{org}/teams"),
    ("GetOrgTeam", "GET", "/v1/orgs/{org}/teams/{team}"),
    ("ListGists", "GET", "/v1/gists"),
    ("CreateGist", "POST", "/v1/gists"),
    ("GetGist", "GET", "/v1/gists/{gist}"),
    ("UpdateGist", "PATCH", "/v1/gists/{gist}"),
    ("ListGistComments", "GET", "/v1/gists/{gist}/comments"),
    ("SearchRepositories", "GET", "/v1/search/repositories"),
    ("SearchIssues", "GET", "/v1/search/issues"),
    ("SearchUsers", "GET", "/v1/search/users"),
    ("GetStatic", "GET", "/v1/static/{path=**}"),
    ("ListFeeds", "GET", "/v1/feeds"),
];
