[package]
name = "oxidizer_rt"
description = "This crate is a private dependency of the `oxidizer` crate. You should never add this as a direct dependency. The entire API surface is unstable."
version.workspace = true
edition.workspace = true
rust-version.workspace = true
authors.workspace = true
license-file.workspace = true
readme.workspace = true
homepage.workspace = true
repository.workspace = true
keywords.workspace = true
categories.workspace = true
publish.workspace = true

[features]
default = ["macros"]
macros = ["oxidizer_macros"]

[dependencies]
# internal
oxidizer_time = { workspace = true }
oxidizer_io = { workspace = true }
isolated_domains = { workspace = true }

# external
async-channel = { workspace = true }
async-lock = { workspace = true }
futures = { workspace = true, default-features = false, features = [
    "executor",
] }
many_cpus = { workspace = true }
mutants = { workspace = true }
negative-impl = { workspace = true }
nonempty = { workspace = true }
oneshot = { workspace = true }
oxidizer_macros = { workspace = true, optional = true }
pin-project = { workspace = true }
scopeguard = { workspace = true }
threadpool = { workspace = true }
thiserror = { workspace = true }
tracing = { workspace = true }

[target.'cfg(windows)'.dependencies]
windows = { workspace = true, features = ["Win32_Networking_WinSock"] }

[dev-dependencies]
# internal
oxidizer_time = { path = "../../crates/oxidizer_time", features = ["fakes"] }
oxidizer_rt_testing = { path = "../../crates_internal/oxidizer_rt_testing" }
oxidizer_testing = { path = "../../crates/oxidizer_testing" }

# external
static_assertions = { workspace = true }
anyhow = { workspace = true }
mockall = { workspace = true }
futures = { workspace = true, default-features = false, features = [
    "async-await",
] }
criterion = { workspace = true, features = ["html_reports"] }
tokio = { workspace = true, features = ["full"] }

[lints]
workspace = true

[[example]]
name = "rt_minimal_return_result"
path = "examples/rt_minimal_return_result.rs"
required-features = ["macros"]

[[example]]
name = "rt_minimal"
path = "examples/rt_minimal.rs"
required-features = ["macros"]

[[example]]
name = "rt_panic"
path = "examples/rt_panic.rs"
required-features = ["macros"]

[[example]]
name = "rt_placement_spawn"
path = "examples/rt_placement_spawn.rs"
required-features = ["macros"]

[[example]]
name = "rt_single_threaded_type"
path = "examples/rt_single_threaded_type.rs"
required-features = ["macros"]

[[example]]
name = "rt_task_spawn_verbosity"
path = "examples/rt_task_spawn_verbosity.rs"
required-features = ["macros"]

[[example]]
name = "rt_time"
path = "examples/rt_time.rs"
required-features = ["macros"]

[[bench]]
name = "task_benches"
harness = false
