[package]
name = "oxidizer_macros"
description = "This crate is a private dependency of the `oxidizer` crate. You should never add this as a direct dependency. The entire API surface is unstable."
version.workspace = true
edition.workspace = true
rust-version.workspace = true
authors.workspace = true
license-file.workspace = true
readme.workspace = true
homepage.workspace = true
repository.workspace = true
keywords.workspace = true
categories.workspace = true
publish.workspace = true

[lib]
proc-macro = true

[dependencies]
oxidizer_macros_impl = { workspace = true }

[dev-dependencies]

[lints]
workspace = true
