// Copyright (c) Microsoft Corporation.
// Licensed under the MIT License.

#![allow(unknown_lints, reason = "the pinned and latest Clippy versions expose different async-trait lints")]
#![expect(
    clippy::unused_async_trait_impl,
    reason = "synchronous examples implement the generated async service trait"
)]

//! The "custom handler" modality: wiring a hand-written (`prost`) gRPC service
//! into a REST API.
//!
//! Here you implement the generated service trait yourself (see
//! [`InMemoryLibrary`]) rather than bridging a `tonic`-generated server (for that
//! path, see the [`tonic_bridge`](crate::tonic_bridge) module).
//!
//! [`pb`] holds the `prost`-generated message types, their `pbjson`
//! proto3-canonical serde implementations, and the build-time generated REST
//! service trait (from `rest_over_grpc::build`) — all `include!`d into one
//! module, exactly as `pbjson` output is co-located with `prost` output
//! (generated from `proto/library.proto`). The top-level [`Transcoder`] that
//! routes requests to that trait is generated separately and re-exported here.

/// The `prost` + `pbjson` message types and the generated REST service trait.
pub mod pb {
    #![allow(
        clippy::all,
        clippy::pedantic,
        clippy::nursery,
        clippy::restriction,
        missing_docs,
        rustdoc::all,
        reason = "code generated by prost + pbjson + rest_over_grpc::build"
    )]

    include!(concat!(env!("OUT_DIR"), "/custom/library.rs"));
    include!(concat!(env!("OUT_DIR"), "/custom/library.serde.rs"));
    include!(concat!(env!("OUT_DIR"), "/custom/library.rest.rs"));
}

// The generated top-level `Transcoder` refers to each service by its
// module-qualified path (`{proto package}::Trait` / `::RequestType`). This proto
// package is `library`, so we alias the `pb` module accordingly and `include!`
// the transcoder at the enclosing scope where `library` is a sibling module.
use pb as library;

#[allow(
    clippy::all,
    clippy::pedantic,
    clippy::nursery,
    clippy::restriction,
    missing_docs,
    rustdoc::all,
    reason = "code generated by rest_over_grpc::build"
)]
mod transcoder {
    use super::library;
    include!(concat!(env!("OUT_DIR"), "/custom/transcoder.rest.rs"));
}

use http::{HeaderName, HeaderValue};
use pb::{CreateShelfRequest, Genre, GetShelfRequest, ListShelvesByGenreRequest, ListShelvesRequest, ListShelvesResponse, Shelf};
use rest_over_grpc::handling::{Context, ResponseStream, Status};
pub use transcoder::Transcoder;

/// A tiny in-memory implementation of the generated [`pb::Library`] trait,
/// shared by the integration tests.
///
/// Beyond the core transcoding, it exercises request/response metadata and
/// status details: `get_shelf` echoes an `x-trace-id` request header, sets an
/// `ETag`, and attaches a `google.rpc.ResourceInfo`-style detail on a miss;
/// `create_shelf` sets a `Location` header for the created resource.
#[derive(Debug, Default, Clone)]
pub struct InMemoryLibrary;

impl pb::Library for InMemoryLibrary {
    async fn get_shelf(&self, request: GetShelfRequest, cx: &mut Context) -> Result<Shelf, Status> {
        if request.shelf == "missing" {
            return Err(Status::not_found("no such shelf").with_detail(serde_json::json!({
                "@type": "type.googleapis.com/google.rpc.ResourceInfo",
                "resourceType": "library.Shelf",
                "resourceName": format!("shelves/{}", request.shelf),
            })));
        }

        // Propagate a caller-supplied trace id back to the response, and set a
        // cache validator — both request- and response-side metadata.
        if let Some(trace) = cx.request_headers().get("x-trace-id").cloned() {
            _ = cx.response_headers_mut().insert(HeaderName::from_static("x-trace-id"), trace);
        }
        cx.insert_response_header(HeaderName::from_static("etag"), HeaderValue::from_static("\"shelf-v1\""));

        Ok(Shelf {
            name: format!("shelves/{}", request.shelf),
            theme: "history".to_owned(),
        })
    }

    async fn create_shelf(&self, request: CreateShelfRequest, cx: &mut Context) -> Result<Shelf, Status> {
        let mut created = request.shelf.ok_or_else(|| Status::invalid_argument("shelf is required"))?;
        "shelves/created".clone_into(&mut created.name);
        // Point the client at the freshly created resource.
        _ = cx.insert_response_header(HeaderName::from_static("location"), HeaderValue::from_static("/v1/shelves/created"));
        Ok(created)
    }

    async fn list_shelves(&self, request: ListShelvesRequest, _cx: &mut Context) -> Result<ListShelvesResponse, Status> {
        let all = [
            Shelf {
                name: "shelves/1".to_owned(),
                theme: "history".to_owned(),
            },
            Shelf {
                name: "shelves/2".to_owned(),
                theme: "science".to_owned(),
            },
        ];
        let shelves = all
            .into_iter()
            .filter(|s| request.filter.is_empty() || s.theme == request.filter)
            .collect();
        Ok(ListShelvesResponse { shelves })
    }

    async fn list_shelves_by_genre(&self, request: ListShelvesByGenreRequest, _cx: &mut Context) -> Result<ListShelvesResponse, Status> {
        // The enum path variable arrives as its `i32` value, decoded from either
        // the value name (`SCIENCE`) or its number (`2`).
        let theme = match request.genre() {
            Genre::History => "history",
            Genre::Science => "science",
            Genre::Unspecified => return Err(Status::invalid_argument("genre is required")),
        };
        let shelves = vec![Shelf {
            name: format!("shelves/{theme}"),
            theme: theme.to_owned(),
        }];
        Ok(ListShelvesResponse { shelves })
    }

    async fn stream_shelves(&self, request: ListShelvesRequest, _cx: &mut Context) -> Result<ResponseStream<Shelf>, Status> {
        let shelves: Vec<Result<Shelf, Status>> = [
            Shelf {
                name: "shelves/1".to_owned(),
                theme: "history".to_owned(),
            },
            Shelf {
                name: "shelves/2".to_owned(),
                theme: "science".to_owned(),
            },
        ]
        .into_iter()
        .filter(|s| request.filter.is_empty() || s.theme == request.filter)
        .map(Ok)
        .collect();
        Ok(Box::pin(futures_util::stream::iter(shelves)))
    }
}
