// Copyright (c) Microsoft Corporation.
// Licensed under the MIT License.

//! The "tonic bridge" modality: wiring a `tonic`-generated gRPC server into a
//! REST API.
//!
//! This is the common case: you implement your service only against `tonic`'s
//! generated server trait, and `rest_over_grpc::build` emits a blanket `impl`
//! that makes it a `rest_over_grpc` service too, so one implementation serves
//! both gRPC and REST. (To hand-write the service trait instead, see the
//! [`custom`](crate::custom) module — it serves the *same* `library.proto`
//! service the other way, so the two modules are an apples-to-apples comparison.)
//!
//! [`LibraryService`] is the tonic-only handler shared by the runnable examples
//! that exercise this modality.

/// The generated library service: tonic messages + server trait, pbjson serde,
/// and the `rest_over_grpc` REST trait + transcoder + tonic bridge.
pub mod library {
    #![allow(
        clippy::all,
        clippy::pedantic,
        clippy::nursery,
        clippy::restriction,
        missing_docs,
        rustdoc::all,
        reason = "code generated by tonic + pbjson + rest_over_grpc::build"
    )]

    include!(concat!(env!("OUT_DIR"), "/tonic_bridge/library.rs"));
    include!(concat!(env!("OUT_DIR"), "/tonic_bridge/library.serde.rs"));
    include!(concat!(env!("OUT_DIR"), "/tonic_bridge/library.rest.rs"));
}

// The generated top-level `Transcoder` refers to the service by its proto
// package path (`library::Library`), so it is `include!`d at the enclosing scope
// where `library` is a sibling module.
#[allow(
    clippy::all,
    clippy::pedantic,
    clippy::nursery,
    clippy::restriction,
    missing_docs,
    rustdoc::all,
    reason = "code generated by rest_over_grpc::build"
)]
mod transcoder {
    use super::library;
    include!(concat!(env!("OUT_DIR"), "/tonic_bridge/transcoder.rest.rs"));
}

use std::pin::Pin;

use futures_util::stream::{self, Stream};
use library::{
    CreateShelfRequest, Genre, GetShelfRequest, ListShelvesByGenreRequest, ListShelvesRequest, ListShelvesResponse, Shelf, library_server,
};
pub use transcoder::Transcoder;

/// A library implemented purely against `tonic`'s generated `library_server::Library`
/// trait — it never mentions `rest_over_grpc`.
///
/// The generated blanket `impl` bridges it to the REST service trait, so a
/// [`Transcoder::new(LibraryService)`](Transcoder) transcodes REST/JSON requests
/// without any extra code.
#[derive(Debug, Default, Clone, Copy)]
pub struct LibraryService;

#[tonic::async_trait]
impl library_server::Library for LibraryService {
    async fn get_shelf(&self, request: tonic::Request<GetShelfRequest>) -> Result<tonic::Response<Shelf>, tonic::Status> {
        let request = request.into_inner();
        // A failable handler so examples can contrast a handler-returned status
        // with a routing miss.
        if request.shelf == "missing" {
            return Err(tonic::Status::not_found("no such shelf"));
        }
        Ok(tonic::Response::new(Shelf {
            name: format!("shelves/{}", request.shelf),
            theme: "history".to_owned(),
        }))
    }

    async fn create_shelf(&self, request: tonic::Request<CreateShelfRequest>) -> Result<tonic::Response<Shelf>, tonic::Status> {
        let mut created = request
            .into_inner()
            .shelf
            .ok_or_else(|| tonic::Status::invalid_argument("shelf is required"))?;
        "shelves/created".clone_into(&mut created.name);
        Ok(tonic::Response::new(created))
    }

    async fn list_shelves(
        &self,
        request: tonic::Request<ListShelvesRequest>,
    ) -> Result<tonic::Response<ListShelvesResponse>, tonic::Status> {
        let filter = request.into_inner().filter;
        Ok(tonic::Response::new(ListShelvesResponse { shelves: shelves(&filter) }))
    }

    async fn list_shelves_by_genre(
        &self,
        request: tonic::Request<ListShelvesByGenreRequest>,
    ) -> Result<tonic::Response<ListShelvesResponse>, tonic::Status> {
        // The enum path variable arrives as its `i32` value, decoded from either
        // the value name (`SCIENCE`) or its number (`2`).
        let theme = match request.into_inner().genre() {
            Genre::History => "history",
            Genre::Science => "science",
            Genre::Unspecified => return Err(tonic::Status::invalid_argument("genre is required")),
        };
        Ok(tonic::Response::new(ListShelvesResponse {
            shelves: vec![Shelf {
                name: format!("shelves/{theme}"),
                theme: theme.to_owned(),
            }],
        }))
    }

    type StreamShelvesStream = Pin<Box<dyn Stream<Item = Result<Shelf, tonic::Status>> + Send + 'static>>;

    async fn stream_shelves(
        &self,
        request: tonic::Request<ListShelvesRequest>,
    ) -> Result<tonic::Response<Self::StreamShelvesStream>, tonic::Status> {
        let filter = request.into_inner().filter;
        let items: Vec<Result<Shelf, tonic::Status>> = shelves(&filter).into_iter().map(Ok).collect();
        Ok(tonic::Response::new(Box::pin(stream::iter(items))))
    }
}

/// The demo shelf set, optionally filtered by theme.
fn shelves(filter: &str) -> Vec<Shelf> {
    [("shelves/1", "history"), ("shelves/2", "science")]
        .into_iter()
        .filter(|(_, theme)| filter.is_empty() || *theme == filter)
        .map(|(name, theme)| Shelf {
            name: name.to_owned(),
            theme: theme.to_owned(),
        })
        .collect()
}
