// Copyright (c) Microsoft Corporation.
// Licensed under the MIT License.

use super::parser::Parser;
use super::{DecodeFields, Error, QueryDecoder as _, QueryLimits};

// Callgrind favors fused scalar parsing below 40 bytes while longer values
// recover the setup cost of vectorized scanning.
const INPUT_SIMD_THRESHOLD: usize = 40;

/// Parses a typed value from an `application/x-www-form-urlencoded` query.
///
/// Implementations are generated by [`FromQuery`](macro@super::FromQuery).
///
/// # Examples
///
/// ```
/// use routerama::query::FromQuery;
///
/// #[derive(FromQuery)]
/// struct Paging {
///     page: usize,
/// }
///
/// # fn main() -> Result<(), Box<dyn std::error::Error>> {
/// let paging = Paging::from_query("page=3")?;
/// assert_eq!(paging.page, 3);
/// # Ok(())
/// # }
/// ```
pub trait FromQuery<'q>: DecodeFields<'q> {
    /// Parses with [`QueryLimits::default`].
    ///
    /// # Errors
    ///
    /// Returns a structured error for malformed input, schema violations, or
    /// resource-limit exhaustion.
    fn from_query(input: &'q str) -> Result<Self, Error> {
        Self::from_query_with(input, QueryLimits::default())
    }

    /// Parses with explicit resource limits.
    ///
    /// # Errors
    ///
    /// Returns a structured error for malformed input, schema violations, or
    /// resource-limit exhaustion.
    // Wide/scalar selection changes performance only; scan implementations are
    // checked differentially at their threshold.
    #[cfg_attr(test, mutants::skip)]
    fn from_query_with(input: &'q str, limits: QueryLimits) -> Result<Self, Error> {
        if input.len() >= INPUT_SIMD_THRESHOLD {
            parse::<Self, true>(input, limits)
        } else {
            parse::<Self, false>(input, limits)
        }
    }
}

impl<'q, T> FromQuery<'q> for T where T: DecodeFields<'q> {}

#[inline]
fn parse<'q, T: DecodeFields<'q>, const WIDE: bool>(input: &'q str, limits: QueryLimits) -> Result<T, Error> {
    let mut parser = Parser::<WIDE>::new(input, limits)?;
    let mut decoder = T::decoder();
    while let Some(pair) = parser.next_pair()? {
        let claimed = decoder.decode_field(pair.key.as_ref(), pair.value, pair.offset, limits)?;
        if !claimed && T::DENY_UNKNOWN_FIELDS {
            return Err(Error::unknown(pair.offset));
        }
    }
    decoder.finish(input.len())
}
