// Copyright (c) Microsoft Corporation.
// Licensed under the MIT License.

use alloc::string::String;
use core::fmt;

use super::{EncodeFields, Encoder, Error, QueryLimits};

/// Produces an `application/x-www-form-urlencoded` query string.
///
/// Implementations are generated by [`ToQuery`](macro@super::ToQuery).
///
/// # Examples
///
/// ```
/// use routerama::query::ToQuery;
///
/// #[derive(ToQuery)]
/// struct Paging {
///     page: usize,
/// }
///
/// # fn main() -> Result<(), Box<dyn std::error::Error>> {
/// let query = Paging { page: 3 }.to_query_string()?;
/// assert_eq!(query, "page=3");
/// # Ok(())
/// # }
/// ```
pub trait ToQuery: EncodeFields {
    /// Writes with [`QueryLimits::default`].
    ///
    /// # Errors
    ///
    /// Returns an error when formatting, limits, or the destination writer
    /// reject output.
    fn write_query<W: fmt::Write>(&self, output: &mut W) -> Result<(), Error> {
        self.write_query_with(output, QueryLimits::default())
    }

    /// Writes with explicit resource limits.
    ///
    /// # Errors
    ///
    /// Returns an error when formatting, limits, or the destination writer
    /// reject output.
    fn write_query_with<W: fmt::Write>(&self, output: &mut W, limits: QueryLimits) -> Result<(), Error> {
        let mut encoder = Encoder::new(output, limits);
        self.encode_fields(&mut encoder)
    }

    /// Produces an owned query string with default limits.
    ///
    /// # Errors
    ///
    /// Returns an error when formatting or the output limit fails.
    fn to_query_string(&self) -> Result<String, Error> {
        self.to_query_string_with(QueryLimits::default())
    }

    /// Produces an owned query string with explicit resource limits.
    ///
    /// # Errors
    ///
    /// Returns an error when formatting or the output limit fails.
    fn to_query_string_with(&self, limits: QueryLimits) -> Result<String, Error> {
        let mut output = String::new();
        self.write_query_with(&mut output, limits)?;
        Ok(output)
    }
}

impl<T: EncodeFields + ?Sized> ToQuery for T {}
