[package]
name = "oxidizer_testing"
description = "This crate is a private dependency of various Oxidizer crates. You should never add this as a direct dependency. The entire API surface is unstable."
version.workspace = true
edition.workspace = true
rust-version.workspace = true
authors.workspace = true
license-file.workspace = true
readme.workspace = true
homepage.workspace = true
repository.workspace = true
keywords.workspace = true
categories.workspace = true
publish.workspace = true

[features]

[dependencies]
rand = { workspace = true }
tracing = { workspace = true }
tracing-appender = { workspace = true }
tracing-subscriber = { workspace = true }

[dev-dependencies]
mockall = { workspace = true }
mutants = { workspace = true }

[lints]
workspace = true
