// Copyright (c) Microsoft Corporation.
// Licensed under the MIT License.

//! Serving REST/JSON through the `layered` adapter.
//!
//! The repository's `layered::Service` is an `async fn`-with-`&self` alternative
//! to `tower`. [`RestService`] implements it over the same `Transcode`
//! implementation, so the same wrapper plugs into either ecosystem. In a real
//! deployment the transcoder is the `Transcoder` generated by
//! `rest_over_grpc::build`; here it is a hand-written health endpoint so the
//! example is self-contained.
//!
//! Run with:
//!
//! ```text
//! cargo run -p rest_over_grpc --example layered_service --features layered
//! ```

use bytes::Bytes;
use http::{Method, Request};
use http_body_util::{BodyExt as _, Full};
use layered::Service as _;
use rest_over_grpc::handling::Status;
use rest_over_grpc::serving::RestService;
use rest_over_grpc::transcoding::{HttpResponse, Transcode, TranscodeResponse};

/// A hand-written transcoder — the same shape as the `tower` example.
#[derive(Clone)]
struct HealthApi;

impl Transcode for HealthApi {
    fn try_transcode(
        &self,
        method: &str,
        target: &str,
        _headers: http::HeaderMap,
        _body: &[u8],
    ) -> impl core::future::Future<Output = Option<TranscodeResponse>> + Send {
        let response = if method == "GET" && target == "/v1/health" {
            HttpResponse::ok_json(br#"{"status":"ok"}"#.to_vec())
        } else {
            HttpResponse::from_status(&Status::not_found("no such route"))
        };
        async move { Some(response.into()) }
    }
}

#[tokio::main(flavor = "current_thread")]
async fn main() {
    // `layered::Service` needs no `Clone` and takes `&self`, so the service is
    // not `mut`.
    let service = RestService::new(HealthApi);

    for target in ["/v1/health", "/v1/missing"] {
        let request = Request::builder()
            .method(Method::GET)
            .uri(target)
            .body(Full::new(Bytes::new()))
            .expect("request builds");

        // `layered::Service::execute` returns the response directly (no `Result`).
        let response = service.execute(request).await;

        let status = response.status();
        let body = response.into_body().collect().await.expect("body collects").to_bytes();
        println!("GET {target} -> {status} {}", String::from_utf8_lossy(&body));
    }
}
