// Copyright (c) Microsoft Corporation.
// Licensed under the MIT License.

//! Serving REST/JSON through the `layered` adapter.
//!
//! The repository's `layered::Service` is an `async fn`-with-`&self` alternative
//! to `tower`. [`RestService`] implements it over the same neutral dispatcher —
//! `(method, uri, body) -> HttpResponse` — so the same wrapper plugs into either
//! ecosystem. In a real deployment the dispatcher is the `dispatch` function
//! generated by `rest_over_grpc_build`; here it is a hand-written health endpoint
//! so the example is self-contained.
//!
//! Run with:
//!
//! ```text
//! cargo run -p rest_over_grpc --example layered_service --features layered
//! ```

use bytes::Bytes;
use http::{Method, Request, Uri};
use http_body_util::Full;
use layered::Service as _;
use rest_over_grpc::adapter::RestService;
use rest_over_grpc::{HttpResponse, Status};

#[tokio::main(flavor = "current_thread")]
async fn main() {
    // The same dispatcher shape as the `tower` example — `layered::Service` needs
    // no `Clone` and takes `&self`, so the service is not `mut`.
    let service = RestService::new(|method: Method, uri: Uri, _body: bytes::Bytes| async move {
        if method == Method::GET && uri.path() == "/v1/health" {
            HttpResponse::ok_json(br#"{"status":"ok"}"#.to_vec())
        } else {
            rest_over_grpc::transcode::status_response(&Status::not_found("no such route"))
        }
    });

    for target in ["/v1/health", "/v1/missing"] {
        let request = Request::builder()
            .method(Method::GET)
            .uri(target)
            .body(Full::new(Bytes::new()))
            .expect("request builds");

        // `layered::Service::execute` returns the response directly (no `Result`).
        let response = service.execute(request).await;

        println!("GET {target} -> {} {}", response.status(), String::from_utf8_lossy(response.body()));
    }
}
