// Copyright (c) Microsoft Corporation.
// Licensed under the MIT License.

//! Calling [`serve_http_fn`] directly, without the [`RestService`] wrapper.
//!
//! [`RestService`] exists to plug into the `tower` / `layered` `Service`
//! ecosystems. When you already hold an [`http::Request`] but aren't building a
//! `Service` stack — a raw `hyper` `service_fn`, one arm of an ad-hoc router, a
//! test — call [`serve_http_fn`] directly instead: it collects the body and
//! headers, invokes your transcoder, and returns an [`http::Response`], with no
//! `Service`, `Clone`, or boxed future.
//!
//! Run with:
//!
//! ```text
//! cargo run -p rest_over_grpc --example serve_http_fn --features serving
//! ```

use bytes::Bytes;
use http::{Method, Request, Response, Uri};
use http_body_util::{BodyExt as _, Full};
use rest_over_grpc::handling::Status;
use rest_over_grpc::serving::{RestBody, serve_http_fn};
use rest_over_grpc::transcoding::HttpResponse;

/// A framework-neutral transcoder. In a real service this is the `transcode`
/// function generated by `rest_over_grpc::build`; here it is hand-written so the
/// example is self-contained.
async fn transcode(method: Method, uri: Uri, _headers: http::HeaderMap, body: Bytes) -> HttpResponse {
    match (method, uri.path()) {
        (Method::POST, "/v1/echo") => HttpResponse::ok_json(body.to_vec()),
        _ => HttpResponse::from_status(&Status::not_found("no such route")),
    }
}

/// A plain async handler — the body of a `hyper` `service_fn`, or one arm of a
/// larger router. It delegates the API subtree to the transcoder and serves
/// everything else by hand, composing `serve_http_fn` with ordinary responses
/// without ever constructing a `Service`.
async fn handle(request: Request<Full<Bytes>>) -> Response<RestBody> {
    if request.uri().path().starts_with("/v1/") {
        serve_http_fn(request, transcode).await
    } else {
        Response::builder()
            .status(http::StatusCode::NOT_FOUND)
            .body(RestBody::buffered(Bytes::from_static(b"not found")))
            .expect("response builds")
    }
}

#[tokio::main(flavor = "current_thread")]
async fn main() {
    let requests = [
        (Method::POST, "/v1/echo", &br#"{"hello":"world"}"#[..]),
        (Method::GET, "/v1/echo", &b""[..]),
        (Method::GET, "/", &b""[..]),
    ];

    for (method, target, body) in requests {
        let request = Request::builder()
            .method(method.clone())
            .uri(target)
            .body(Full::new(Bytes::copy_from_slice(body)))
            .expect("request builds");

        let response = handle(request).await;

        let status = response.status();
        let body = response.into_body().collect().await.expect("body collects").to_bytes();
        println!("{method} {target} -> {status} {}", String::from_utf8_lossy(&body));
    }
}
