// Copyright (c) Microsoft Corporation.
// Licensed under the MIT License.

//! Serving REST/JSON through the `tower` adapter.
//!
//! Wraps a framework-neutral dispatcher — `(method, uri, body) -> HttpResponse`
//! — as a [`RestService`], then drives it with [`http::Request`]s the way a
//! `hyper` / `axum` / `tower` server would. In a real deployment the dispatcher
//! is the `dispatch` function generated by `rest_over_grpc_build`; here it is a
//! hand-written health endpoint so the example is self-contained.
//!
//! Run with:
//!
//! ```text
//! cargo run -p rest_over_grpc --example tower_service --features tower
//! ```

use bytes::Bytes;
use http::{Method, Request, Uri};
use http_body_util::Full;
use rest_over_grpc::adapter::RestService;
use rest_over_grpc::{HttpResponse, Status};
use tower_service::Service as _;

#[tokio::main(flavor = "current_thread")]
async fn main() {
    // The dispatcher receives the request's method, URI, and collected body and
    // returns a neutral `HttpResponse`. A generated dispatcher would resolve the
    // route and transcode JSON <-> protobuf; this one hand-routes one path.
    let mut service = RestService::new(|method: Method, uri: Uri, _body: bytes::Bytes| async move {
        if method == Method::GET && uri.path() == "/v1/health" {
            HttpResponse::ok_json(br#"{"status":"ok"}"#.to_vec())
        } else {
            // gRPC `NOT_FOUND` maps to HTTP 404 with a JSON status body.
            rest_over_grpc::transcode::status_response(&Status::not_found("no such route"))
        }
    });

    for target in ["/v1/health", "/v1/missing"] {
        let request = Request::builder()
            .method(Method::GET)
            .uri(target)
            .body(Full::new(Bytes::new()))
            .expect("request builds");

        let response = service.call(request).await.expect("the dispatcher is infallible");

        println!("GET {target} -> {} {}", response.status(), String::from_utf8_lossy(response.body()));
    }
}
