// Copyright (c) Microsoft Corporation.
// Licensed under the MIT License.

//! Serving REST/JSON through the `tower` adapter.
//!
//! Wraps a `Transcode` implementation as a [`RestService`], then drives it with
//! [`http::Request`]s the way a `hyper` / `axum` / `tower` server would. In a
//! real deployment the transcoder is the `Transcoder` generated by
//! `rest_over_grpc::build`; here it is a hand-written health endpoint so the
//! example is self-contained.
//!
//! Run with:
//!
//! ```text
//! cargo run -p rest_over_grpc --example tower_service --features tower
//! ```

use bytes::Bytes;
use http::{Method, Request};
use http_body_util::{BodyExt as _, Full};
use rest_over_grpc::handling::Status;
use rest_over_grpc::serving::RestService;
use rest_over_grpc::transcoding::{HttpResponse, Transcode, TranscodeResponse};
use tower_service::Service as _;

/// A hand-written transcoder. A generated `Transcoder` would resolve the route
/// and transcode JSON <-> protobuf; this one hand-routes a single path.
#[derive(Clone)]
struct HealthApi;

impl Transcode for HealthApi {
    fn try_transcode(
        &self,
        method: &str,
        target: &str,
        _headers: http::HeaderMap,
        _body: &[u8],
    ) -> impl core::future::Future<Output = Option<TranscodeResponse>> + Send {
        let response = if method == "GET" && target == "/v1/health" {
            HttpResponse::ok_json(br#"{"status":"ok"}"#.to_vec())
        } else {
            HttpResponse::from_status(&Status::not_found("no such route"))
        };
        async move { Some(response.into()) }
    }
}

#[tokio::main(flavor = "current_thread")]
async fn main() {
    let mut service = RestService::new(HealthApi);

    for target in ["/v1/health", "/v1/missing"] {
        let request = Request::builder()
            .method(Method::GET)
            .uri(target)
            .body(Full::new(Bytes::new()))
            .expect("request builds");

        let response = service.call(request).await.expect("the transcoder is infallible");

        let status = response.status();
        let body = response.into_body().collect().await.expect("body collects").to_bytes();
        println!("GET {target} -> {status} {}", String::from_utf8_lossy(&body));
    }
}
