[package]
name = "oxidizer_mem"
description = "Oxidizer SDK components for working with memory"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
authors.workspace = true
license-file.workspace = true
readme.workspace = true
homepage.workspace = true
repository.workspace = true
keywords.workspace = true
categories.workspace = true
publish.workspace = true

[features]
default = []
fakes = []

[dependencies]
bytes = { workspace = true }
derive_more = { workspace = true, features = ["debug", "display"] }

[dev-dependencies]
mutants = { workspace = true }
static_assertions = { workspace = true }
negative-impl = { workspace = true }

[lints]
workspace = true
