// Copyright (c) Microsoft Corporation.
// Licensed under the MIT License.

//! WebSocket decode shapes across HTTP/custom sources and ownership modes.

use http_headers::DecodeErrorKind;
use http_headers::headers::{SecWebSocketAccept, SecWebSocketExtensions, SecWebSocketKey, SecWebSocketProtocol, SecWebSocketVersion};

#[path = "http_headers_shapes_common.rs"]
mod shapes;

use shapes::{Expectations, Expected};

shapes::define_shapes!(
    "http_headers_websocket_shapes/parse";
    (websocket_accept_standard, SecWebSocketAccept, &["s3pPLMBiTxaQ9kYGzzhZRbK+xOo="], Strict, Expected::Valid),
    (websocket_accept_zero, SecWebSocketAccept, &["AAAAAAAAAAAAAAAAAAAAAAAAAAA="], Strict, Expected::Valid),
    (websocket_accept_padding, SecWebSocketAccept, &["s3pPLMBiTxaQ9kYGzzhZRbK+xOp="], Strict, Expected::Error(DecodeErrorKind::InvalidSyntax)),
    (websocket_accept_alphabet, SecWebSocketAccept, &["!3pPLMBiTxaQ9kYGzzhZRbK+xOo="], Strict, Expected::Error(DecodeErrorKind::InvalidSyntax)),
    (websocket_accept_alphabet_tail, SecWebSocketAccept, &["s3pPLMBiTxaQ9kYGzzhZRbK+xO!="], Strict, Expected::Error(DecodeErrorKind::InvalidSyntax)),
    (websocket_accept_missing_pad, SecWebSocketAccept, &["s3pPLMBiTxaQ9kYGzzhZRbK+xOo!"], Strict, Expected::Error(DecodeErrorKind::InvalidSyntax)),
    (websocket_accept_short, SecWebSocketAccept, &["s3pPLMBiTxaQ9kYG"], Strict, Expected::Error(DecodeErrorKind::InvalidSyntax)),
    (websocket_accept_repeated, SecWebSocketAccept, &["s3pPLMBiTxaQ9kYGzzhZRbK+xOo=", "s3pPLMBiTxaQ9kYGzzhZRbK+xOo="], Strict, Expected::Error(DecodeErrorKind::UnexpectedMultipleValues)),
    (websocket_accept_absent, SecWebSocketAccept, &[], Strict, Expected::Absent),
    (websocket_key_standard, SecWebSocketKey, &["dGhlIHNhbXBsZSBub25jZQ=="], Strict, Expected::Valid),
    (websocket_key_zero, SecWebSocketKey, &["AAAAAAAAAAAAAAAAAAAAAA=="], Strict, Expected::Valid),
    (websocket_key_padding, SecWebSocketKey, &["dGhlIHNhbXBsZSBub25jZR=="], Strict, Expected::Error(DecodeErrorKind::InvalidSyntax)),
    (websocket_key_alphabet, SecWebSocketKey, &["!GhlIHNhbXBsZSBub25jZQ=="], Strict, Expected::Error(DecodeErrorKind::InvalidSyntax)),
    (websocket_key_alphabet_tail, SecWebSocketKey, &["dGhlIHNhbXBsZSBub25jZ!=="], Strict, Expected::Error(DecodeErrorKind::InvalidSyntax)),
    (websocket_key_missing_first_pad, SecWebSocketKey, &["dGhlIHNhbXBsZSBub25jZQ!="], Strict, Expected::Error(DecodeErrorKind::InvalidSyntax)),
    (websocket_key_missing_last_pad, SecWebSocketKey, &["dGhlIHNhbXBsZSBub25jZQ=!"], Strict, Expected::Error(DecodeErrorKind::InvalidSyntax)),
    (websocket_key_short, SecWebSocketKey, &["dGhlIHNhbXBsZQ=="], Strict, Expected::Error(DecodeErrorKind::InvalidSyntax)),
    (websocket_key_repeated, SecWebSocketKey, &["dGhlIHNhbXBsZSBub25jZQ==", "dGhlIHNhbXBsZSBub25jZQ=="], Strict, Expected::Error(DecodeErrorKind::UnexpectedMultipleValues)),
    (websocket_key_absent, SecWebSocketKey, &[], Strict, Expected::Absent),
    (websocket_protocol_standard, SecWebSocketProtocol, &["graphql-transport-ws"], Strict, Expected::Valid),
    (websocket_protocol_graphql, SecWebSocketProtocol, &["graphql-ws"], Strict, Expected::Valid),
    (websocket_protocol_graphql_advertisement, SecWebSocketProtocol, &["graphql-transport-ws, graphql-ws"], Strict, Expected::Valid),
    (websocket_protocol_graphql_near_first, SecWebSocketProtocol, &["Xraphql-ws"], Strict, Expected::Valid),
    (websocket_protocol_graphql_near_second, SecWebSocketProtocol, &["gRaphql-ws"], Strict, Expected::Valid),
    (websocket_protocol_graphql_near_middle, SecWebSocketProtocol, &["grapHql-ws"], Strict, Expected::Valid),
    (websocket_protocol_graphql_near_last, SecWebSocketProtocol, &["graphql-wS"], Strict, Expected::Valid),
    (websocket_protocol_graphql_invalid_last, SecWebSocketProtocol, &["graphql-w/"], Strict, Expected::Error(DecodeErrorKind::InvalidToken)),
    (websocket_protocol_list_near_first, SecWebSocketProtocol, &["Chat, superchat"], Strict, Expected::Valid),
    (websocket_protocol_list_near_second, SecWebSocketProtocol, &["cHat, superchat"], Strict, Expected::Valid),
    (websocket_protocol_list_near_middle, SecWebSocketProtocol, &["chat, suPerchat"], Strict, Expected::Valid),
    (websocket_protocol_list_near_last, SecWebSocketProtocol, &["chat, superchaT"], Strict, Expected::Valid),
    (websocket_protocol_list_invalid_first, SecWebSocketProtocol, &["/hat, superchat"], Strict, Expected::Error(DecodeErrorKind::InvalidToken)),
    (websocket_protocol_list_invalid_last, SecWebSocketProtocol, &["chat, supercha/"], Strict, Expected::Error(DecodeErrorKind::InvalidToken)),
    (websocket_protocol_transport_near_first, SecWebSocketProtocol, &["Graphql-transport-ws"], Strict, Expected::Valid),
    (websocket_protocol_transport_near_second, SecWebSocketProtocol, &["gRaphql-transport-ws"], Strict, Expected::Valid),
    (websocket_protocol_transport_near_middle, SecWebSocketProtocol, &["graphql-transPort-ws"], Strict, Expected::Valid),
    (websocket_protocol_transport_near_last, SecWebSocketProtocol, &["graphql-transport-wS"], Strict, Expected::Valid),
    (websocket_protocol_transport_invalid_first, SecWebSocketProtocol, &["/raphql-transport-ws"], Strict, Expected::Error(DecodeErrorKind::InvalidToken)),
    (websocket_protocol_transport_invalid_last, SecWebSocketProtocol, &["graphql-transport-w/"], Strict, Expected::Error(DecodeErrorKind::InvalidToken)),
    (websocket_protocol_advertisement_near_first, SecWebSocketProtocol, &["Graphql-transport-ws, graphql-ws"], Strict, Expected::Valid),
    (websocket_protocol_advertisement_near_second, SecWebSocketProtocol, &["gRaphql-transport-ws, graphql-ws"], Strict, Expected::Valid),
    (websocket_protocol_advertisement_near_middle, SecWebSocketProtocol, &["graphql-transport-wS, graphql-ws"], Strict, Expected::Valid),
    (websocket_protocol_advertisement_near_last, SecWebSocketProtocol, &["graphql-transport-ws, graphql-wS"], Strict, Expected::Valid),
    (websocket_protocol_advertisement_invalid_first, SecWebSocketProtocol, &["/raphql-transport-ws, graphql-ws"], Strict, Expected::Error(DecodeErrorKind::InvalidToken)),
    (websocket_protocol_advertisement_invalid_last, SecWebSocketProtocol, &["graphql-transport-ws, graphql-w/"], Strict, Expected::Error(DecodeErrorKind::InvalidToken)),
    (websocket_protocol_invalid_first, SecWebSocketProtocol, &["/raphql-ws"], Strict, Expected::Error(DecodeErrorKind::InvalidToken)),
    (websocket_protocol_token, SecWebSocketProtocol, &["binary.protocol-v2"], Strict, Expected::Valid),
    (websocket_protocol_list, SecWebSocketProtocol, &["chat, superchat"], Strict, Expected::Valid),
    (websocket_protocol_ows, SecWebSocketProtocol, &[" \tchat , binary.protocol-v2\t"], Strict, Expected::Valid),
    (websocket_protocol_repeated, SecWebSocketProtocol, &["chat", "superchat", "binary.protocol-v2"], Strict, Expected::Valid),
    (websocket_protocol_quote, SecWebSocketProtocol, &["chat, \"quoted\""], Strict, Expected::Error(DecodeErrorKind::InvalidToken)),
    (websocket_protocol_empty, SecWebSocketProtocol, &[""], Strict, Expectations {
        http_owned: Expected::Error(DecodeErrorKind::InvalidSyntax),
        http_borrowed: Expected::Error(DecodeErrorKind::MissingValue),
        raw_owned: Expected::Error(DecodeErrorKind::InvalidSyntax),
        raw_borrowed: Expected::Error(DecodeErrorKind::MissingValue),
    }),
    (websocket_protocol_empty_members, SecWebSocketProtocol, &[" , , \t"], Strict, Expectations {
        http_owned: Expected::Error(DecodeErrorKind::InvalidSyntax),
        http_borrowed: Expected::Error(DecodeErrorKind::MissingValue),
        raw_owned: Expected::Error(DecodeErrorKind::InvalidSyntax),
        raw_borrowed: Expected::Error(DecodeErrorKind::MissingValue),
    }),
    (websocket_protocol_unterminated, SecWebSocketProtocol, &["chat", "\"quoted"], Strict, Expectations {
        http_owned: Expected::Error(DecodeErrorKind::InvalidToken),
        http_borrowed: Expected::Error(DecodeErrorKind::UnterminatedQuote),
        raw_owned: Expected::Error(DecodeErrorKind::InvalidToken),
        raw_borrowed: Expected::Error(DecodeErrorKind::UnterminatedQuote),
    }),
    (websocket_protocol_absent, SecWebSocketProtocol, &[], Strict, Expected::Absent),
    (websocket_extensions_standard, SecWebSocketExtensions, &["permessage-deflate"], Strict, Expected::Valid),
    (websocket_extensions_window, SecWebSocketExtensions, &["permessage-deflate; client_max_window_bits"], Strict, Expected::Valid),
    (websocket_extensions_takeover, SecWebSocketExtensions, &["permessage-deflate; server_no_context_takeover; client_no_context_takeover"], Strict, Expected::Valid),
    (websocket_extensions_near_first, SecWebSocketExtensions, &["Permessage-deflate"], Strict, Expected::Valid),
    (websocket_extensions_near_second, SecWebSocketExtensions, &["pErmessage-deflate"], Strict, Expected::Valid),
    (websocket_extensions_near_middle, SecWebSocketExtensions, &["permessAge-deflate"], Strict, Expected::Valid),
    (websocket_extensions_near_last, SecWebSocketExtensions, &["permessage-deflatE"], Strict, Expected::Valid),
    (websocket_extensions_window_near_first, SecWebSocketExtensions, &["Permessage-deflate; client_max_window_bits"], Strict, Expected::Valid),
    (websocket_extensions_window_near_second, SecWebSocketExtensions, &["pErmessage-deflate; client_max_window_bits"], Strict, Expected::Valid),
    (websocket_extensions_window_invalid_first, SecWebSocketExtensions, &["/ermessage-deflate; client_max_window_bits"], Strict, Expected::Error(DecodeErrorKind::InvalidToken)),
    (websocket_extensions_window_near_middle, SecWebSocketExtensions, &["permessage-deflate; clieNt_max_window_bits"], Strict, Expected::Valid),
    (websocket_extensions_window_near_last, SecWebSocketExtensions, &["permessage-deflate; client_max_window_bitS"], Strict, Expected::Valid),
    (websocket_extensions_takeover_near_first, SecWebSocketExtensions, &["Permessage-deflate; server_no_context_takeover; client_no_context_takeover"], Strict, Expected::Valid),
    (websocket_extensions_takeover_near_second, SecWebSocketExtensions, &["pErmessage-deflate; server_no_context_takeover; client_no_context_takeover"], Strict, Expected::Valid),
    (websocket_extensions_takeover_invalid_first, SecWebSocketExtensions, &["/ermessage-deflate; server_no_context_takeover; client_no_context_takeover"], Strict, Expected::Error(DecodeErrorKind::InvalidToken)),
    (websocket_extensions_takeover_near_middle, SecWebSocketExtensions, &["permessage-deflate; server_no_context_Takeover; client_no_context_takeover"], Strict, Expected::Valid),
    (websocket_extensions_takeover_near_last, SecWebSocketExtensions, &["permessage-deflate; server_no_context_takeover; client_no_context_takeoveR"], Strict, Expected::Valid),
    (websocket_extensions_invalid_first, SecWebSocketExtensions, &["/ermessage-deflate"], Strict, Expected::Error(DecodeErrorKind::InvalidToken)),
    (websocket_extensions_invalid_last, SecWebSocketExtensions, &["permessage-deflat/"], Strict, Expected::Error(DecodeErrorKind::InvalidSyntax)),
    (websocket_extensions_window_invalid_last, SecWebSocketExtensions, &["permessage-deflate; client_max_window_bit/"], Strict, Expected::Error(DecodeErrorKind::InvalidSyntax)),
    (websocket_extensions_takeover_invalid_last, SecWebSocketExtensions, &["permessage-deflate; server_no_context_takeover; client_no_context_takeove/"], Strict, Expected::Error(DecodeErrorKind::InvalidSyntax)),
    (websocket_extensions_numbers, SecWebSocketExtensions, &["permessage-deflate; server_max_window_bits=15; client_max_window_bits=15"], Strict, Expected::Valid),
    (websocket_extensions_token_15, SecWebSocketExtensions, &["xxxxxxxxxxxxxxx"], Strict, Expected::Valid),
    (websocket_extensions_token_16, SecWebSocketExtensions, &["xxxxxxxxxxxxxxxx"], Strict, Expected::Valid),
    (websocket_extensions_token_17, SecWebSocketExtensions, &["xxxxxxxxxxxxxxxxx"], Strict, Expected::Valid),
    (websocket_extensions_token_31, SecWebSocketExtensions, &["xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"], Strict, Expected::Valid),
    (websocket_extensions_token_32, SecWebSocketExtensions, &["xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"], Strict, Expected::Valid),
    (websocket_extensions_token_33, SecWebSocketExtensions, &["xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"], Strict, Expected::Valid),
    (websocket_extensions_quoted_name, SecWebSocketExtensions, &["\"x\""], Strict, Expected::Error(DecodeErrorKind::InvalidToken)),
    (websocket_extensions_unterminated_name, SecWebSocketExtensions, &["\"x"], Strict, Expectations {
        http_owned: Expected::Error(DecodeErrorKind::InvalidToken),
        http_borrowed: Expected::Error(DecodeErrorKind::UnterminatedQuote),
        raw_owned: Expected::Error(DecodeErrorKind::InvalidToken),
        raw_borrowed: Expected::Error(DecodeErrorKind::UnterminatedQuote),
    }),
    (websocket_extensions_backslash_value, SecWebSocketExtensions, &["x; mode=\\bad"], Strict, Expected::Error(DecodeErrorKind::InvalidToken)),
    (websocket_extensions_quoted, SecWebSocketExtensions, &["permessage-deflate; client_max_window_bits=\"15\""], Strict, Expected::Valid),
    (websocket_extensions_repeated, SecWebSocketExtensions, &["permessage-deflate; client_max_window_bits", "x-custom; mode=fast"], Strict, Expected::Valid),
    (websocket_extensions_invalid, SecWebSocketExtensions, &["permessage-deflate; =15"], Strict, Expected::Error(DecodeErrorKind::InvalidToken)),
    (websocket_extensions_empty, SecWebSocketExtensions, &[""], Strict, Expectations {
        http_owned: Expected::Error(DecodeErrorKind::InvalidSyntax),
        http_borrowed: Expected::Error(DecodeErrorKind::MissingValue),
        raw_owned: Expected::Error(DecodeErrorKind::InvalidSyntax),
        raw_borrowed: Expected::Error(DecodeErrorKind::MissingValue),
    }),
    (websocket_extensions_absent, SecWebSocketExtensions, &[], Strict, Expected::Absent),
    (websocket_version_standard, SecWebSocketVersion, &["13"], Strict, Expected::Valid),
    (websocket_version_draft, SecWebSocketVersion, &["8"], Strict, Expected::Valid),
    (websocket_version_zero, SecWebSocketVersion, &["0"], Strict, Expected::Valid),
    (websocket_version_two_digits, SecWebSocketVersion, &["17"], Strict, Expected::Valid),
    (websocket_version_maximum, SecWebSocketVersion, &["255"], Strict, Expected::Valid),
    (websocket_version_ows, SecWebSocketVersion, &[" \t13\t "], Strict, Expected::Valid),
    (websocket_version_advertisement, SecWebSocketVersion, &["7, 8, 13"], Strict, Expected::Valid),
    (websocket_version_repeated, SecWebSocketVersion, &["13", "8", "255"], Strict, Expected::Valid),
    (websocket_version_duplicate, SecWebSocketVersion, &["13", "13"], Strict, Expected::Valid),
    (websocket_version_late_invalid, SecWebSocketVersion, &["13", "256"], Strict, Expected::Error(DecodeErrorKind::InvalidSyntax)),
    (websocket_version_quote, SecWebSocketVersion, &["13", "\"13"], Strict, Expected::Error(DecodeErrorKind::UnterminatedQuote)),
    (websocket_version_quote_only, SecWebSocketVersion, &["\"13"], Strict, Expected::Error(DecodeErrorKind::UnterminatedQuote)),
    (websocket_version_quoted_member, SecWebSocketVersion, &["\"13\""], Strict, Expected::Error(DecodeErrorKind::InvalidSyntax)),
    (websocket_version_invalid_before_quote, SecWebSocketVersion, &["256, \"13"], Strict, Expected::Error(DecodeErrorKind::InvalidSyntax)),
    (websocket_version_quote_after_member, SecWebSocketVersion, &["13, \"13"], Strict, Expected::Error(DecodeErrorKind::UnterminatedQuote)),
    (websocket_version_empty, SecWebSocketVersion, &[""], Strict, Expected::Error(DecodeErrorKind::MissingValue)),
    (websocket_version_empty_members, SecWebSocketVersion, &[" , , \t"], Strict, Expected::Error(DecodeErrorKind::MissingValue)),
    (websocket_version_leading_zero, SecWebSocketVersion, &["013"], Strict, Expected::Error(DecodeErrorKind::InvalidSyntax)),
    (websocket_version_relaxed, SecWebSocketVersion, &["13, 8"], Relaxed, Expected::Valid),
    (websocket_version_custom_line_limit, SecWebSocketVersion, &["13"; 129], Strict, Expectations {
        http_owned: Expected::Valid,
        http_borrowed: Expected::Valid,
        raw_owned: Expected::Error(DecodeErrorKind::InvalidSyntax),
        raw_borrowed: Expected::Error(DecodeErrorKind::InvalidSyntax),
    }),
    (websocket_version_absent, SecWebSocketVersion, &[], Strict, Expected::Absent),
);
