[package]
name = "oxidizer_time"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
authors.workspace = true
license-file.workspace = true
description.workspace = true
readme.workspace = true
homepage.workspace = true
repository.workspace = true
keywords.workspace = true
categories.workspace = true
publish.workspace = true

[lib]
crate-type = ["lib"]

[lints]
workspace = true

[features]
default = ["serde"]
# Enables additional functionality intended for testing services based on Oxidizer.
# Partners may choose to enable this in dev-dependencies.
fakes = []
serde = ["dep:serde"]
tokio = ["dep:tokio"]

[dependencies]
# external
futures = { workspace = true }
jiff = { workspace = true, default-features = false, features = ["std"] }
mutants = { workspace = true }
pin-project = { workspace = true }
serde = { workspace = true, features = ["derive", "std"], default-features = false, optional = true }
thiserror = { workspace = true }
tokio = { workspace = true, optional = true, features = ["time", "rt"] }

[dev-dependencies]
#external
anyhow = { workspace = true }
chrono = { workspace = true }
chrono-tz = { workspace = true }
criterion = { workspace = true, features = ["html_reports"] }
futures = { workspace = true, features = ["default", "executor", "futures-executor"] }
jiff = { workspace = true, default-features = true }
serde_json = { workspace = true }
static_assertions = { workspace = true }
time = { workspace = true, features = ["formatting", "local-offset", "macros"] }
time-tz = { workspace = true, features = ["system"] }
tokio = { workspace = true, features = ["time", "rt", "macros", "rt-multi-thread"] }

[[example]]
name = "basic"

[[example]]
name = "clock"

[[example]]
name = "clock_control"
required-features = ["fakes"]

[[example]]
name = "data"
required-features = ["fakes", "serde"]

[[example]]
name = "interop_chrono"
required-features = ["fakes"]

[[example]]
name = "interop_time"
required-features = ["fakes"]

[[example]]
name = "interop_jiff"
required-features = ["fakes"]

[[example]]
name = "timestamp"
required-features = ["fakes"]

[[example]]
name = "basic_tokio"
required-features = ["tokio"]

[[bench]]
name = "clock_bench"
harness = false
