use crate::resolver_store::ResolverStore;

/// Trait for base structs that provide root types for a resolver.
///
/// `T` is the resolver's type parameter (the application base type).
///
/// - `#[base]` on `MyBase` generates `impl BaseType<MyBase> for MyBase` — roots for the
///   primary [`Resolver`](crate::Resolver).
/// - `#[base(scoped(Parent))]` on `ScopedRoots` generates `impl BaseType<ScopedRoots> for
///   ScopedRoots` — roots for a [`ScopedResolver`](crate::ScopedResolver).
///
/// This trait is generated by the `#[base]` proc macro and should not be implemented manually.
pub trait BaseType<T: 'static>: Sized + Send + Sync + 'static {
    /// Destructures this base struct, inserting each field as a root type into the store.
    fn insert_into(self, store: &mut impl ResolverStore<T>);
}

/// Associates a scoped base type with its parent base type.
///
/// Generated by `#[base(scoped(Parent))]`. Ensures that a scoped resolver can only
/// be created from a shared resolver of the correct parent scope.
pub trait ScopedUnder: Sized + Send + Sync + 'static {
    /// The parent base type under which this scope is nested.
    type Parent: Send + Sync + 'static;
}
