use crate::resolver_store::ResolverStore;

/// Trait for base structs that provide root types for a resolver.
///
/// - `#[base]` on `MyBase` generates `impl BaseType for MyBase` with `Parent = ()`,
///   indicating a root base for [`Resolver::new()`](crate::Resolver::new).
/// - `#[base(scoped(Parent))]` on `ScopedRoots` generates `impl BaseType for ScopedRoots`
///   with `Parent = ParentBase`, indicating a scoped base for
///   [`Resolver::scoped()`](crate::Resolver::scoped).
///
/// This trait is generated by the `#[base]` proc macro and should not be implemented manually.
pub trait BaseType: Sized + Send + Sync + 'static {
    /// `()` for root bases, the parent base type for scoped bases.
    type Parent: Send + Sync + 'static;

    /// Destructures this base struct, inserting each field as a root type into the store.
    fn insert_into(self, store: &mut impl ResolverStore<Self>);
}
