/// A trait that maps a const index to a field type within a composite struct.
///
/// This is generated by the `#[composite]` proc macro — one impl per field. It enables
/// the `resolver!` macro to reference field types through associated-type projections
/// (`<Composite as CompositePart<N>>::Part`), avoiding the need to name individual field
/// types directly.
pub trait CompositePart<const N: usize> {
    type Part: Send + Sync + 'static;
}
