use crate::resolve_deps::ResolutionDeps;

/// A type that can be lazily constructed from its dependencies within a resolver.
///
/// Implementations are generated by the [`#[resolvable]`](crate::resolvable) proc macro.
pub trait ResolveFrom<T: Send + Sync + 'static>: Send + Sync + 'static {
    /// The heterogeneous list of dependency types needed to construct this type.
    type Inputs: ResolutionDeps<T>;

    /// Constructs this type from resolved handles to its dependencies.
    fn new(inputs: <Self::Inputs as ResolutionDeps<T>>::Resolved) -> Self;
}
