/// Creates a [`Resolver`] with multiple base types.
///
/// The first argument is the name used for the resolver's base type (a local zero-sized struct
/// generated by the macro). The remaining arguments are entries of two kinds:
///
/// - `name: Type` — a direct base type. The variable `name` of type `Type` is pre-inserted into
///   the resolver.
/// - `..name: Type` — a composite type (annotated with `#[composite]`). Each field of `Type` is
///   extracted and pre-inserted individually.
///
/// Both kinds can be freely mixed.
///
/// # Example
///
/// ```ignore
/// let builtins = Builtins { scheduler: Scheduler, clock: Clock };
/// let telemetry = Telemetry::new();
///
/// let mut resolver = autoresolve::resolver!(MyBase,
///     ..builtins: Builtins,
///     telemetry: Telemetry,
/// );
///
/// let client = resolver.get::<Client>();
/// ```
#[macro_export]
macro_rules! resolver {
    // Entry point.
    ( $base:ident, $( $rest:tt )+ ) => {
        {
            struct $base;
            let mut r = $crate::Resolver::<$base>::new_empty();
            $crate::resolver!(@__entry $base r $( $rest )+ );
            r
        }
    };

    // Composite entry with more entries following.
    (@__entry $base:ident $r:ident .. $name:ident : $ty:ident , $( $rest:tt )+ ) => {
        $ty!(@impls $base);
        $ty!(@insert $r, $name);
        $crate::resolver!(@__entry $base $r $( $rest )+ );
    };

    // Composite entry, last (optional trailing comma).
    (@__entry $base:ident $r:ident .. $name:ident : $ty:ident $(,)? ) => {
        $ty!(@impls $base);
        $ty!(@insert $r, $name);
    };

    // Regular entry with more entries following.
    (@__entry $base:ident $r:ident $name:ident : $ty:ty , $( $rest:tt )+ ) => {
        impl $crate::ResolveFrom<$base> for $ty {
            type Inputs = $crate::ResolutionDepsEnd;

            fn new(_: $crate::ResolutionDepsEnd) -> Self {
                unreachable!("base types are pre-inserted into the resolver")
            }
        }
        $r.insert($name);
        $crate::resolver!(@__entry $base $r $( $rest )+ );
    };

    // Regular entry, last (optional trailing comma).
    (@__entry $base:ident $r:ident $name:ident : $ty:ty $(,)? ) => {
        impl $crate::ResolveFrom<$base> for $ty {
            type Inputs = $crate::ResolutionDepsEnd;

            fn new(_: $crate::ResolutionDepsEnd) -> Self {
                unreachable!("base types are pre-inserted into the resolver")
            }
        }
        $r.insert($name);
    };
}
