/// Creates a [`Resolver`] with multiple base types.
///
/// The first argument is the name used for the resolver's base type (a local zero-sized struct
/// generated by the macro). The remaining arguments are `name: Type` pairs where `name` is a
/// variable in scope of type `Type`. These become root types in the dependency hierarchy — they
/// are pre-inserted into the resolver and available as dependencies for any type marked with
/// `#[resolvable]`.
///
/// # Example
///
/// ```ignore
/// let builtins = Builtins::new();
/// let telemetry = Telemetry::new();
///
/// let mut resolver = autoresolve::resolver!(MyBase,
///     builtins: Builtins,
///     telemetry: Telemetry,
/// );
///
/// let client = resolver.get::<Client>();
/// ```
#[macro_export]
macro_rules! resolver {
    ( $base:ident, $( $name:ident : $ty:ty ),+ $(,)? ) => {
        {
            struct $base;

            $(
                impl $crate::ResolveFrom<$base> for $ty {
                    type Inputs = $crate::ResolutionDepsEnd;

                    fn new(_: $crate::ResolutionDepsEnd) -> Self {
                        unreachable!("base types are pre-inserted into the resolver")
                    }
                }
            )+

            let mut r = $crate::Resolver::<$base>::new_empty();
            $(
                r.insert($name);
            )+
            r
        }
    };
}
