use crate::ScopedResolver;

/// Marker trait for scoped root structs declared via `#[base(scoped(...))]`.
///
/// Implementing this trait allows the struct to be passed to
/// [`SharedResolver::scoped()`](crate::SharedResolver::scoped), which automatically
/// inserts the struct's fields as root types in the scoped resolver.
///
/// This trait is generated by the `#[base(scoped(Parent))]` proc macro and should
/// not be implemented manually.
pub trait ScopedBase<T>: Sized {
    /// Destructures the scoped base struct, inserting each field into the scoped resolver.
    fn insert_into(self, resolver: &mut ScopedResolver<T>);
}
