parameters:
- name: registryUrl
  type: string
- name: registryName
  type: string
  default: CratesIoMirror

steps:
- pwsh: |
    $cfgDir = Join-Path $env:BUILD_SOURCESDIRECTORY '.cargo';`
    New-Item -ItemType Directory -Force -Path $cfgDir | Out-Null;`
    $cfgFile = Join-Path $cfgDir 'config.toml';`
    @'
    [registries]
    ${{ parameters.registryName }} = { index = "${{ parameters.registryUrl }}" }
    [source.crates-io]
    replace-with = "${{ parameters.registryName }}"
    '@ | Set-Content -LiteralPath $cfgFile -Encoding UTF8;`
    Write-Host "Created $cfgFile with ${{ parameters.registryName }} registry."
  displayName: 'Create .cargo/config.toml'