# Copyright (c) Microsoft Corporation.
# Licensed under the MIT License.

[package]
name = "internity_macros_impl"
version = "0.1.0"
description = "Procedural macro implementation for the internity crate."
readme = "README.md"
keywords = ["intern", "interner", "serde", "macro", "derive"]
categories = ["data-structures", "development-tools::procedural-macro-helpers"]

edition = { workspace = true }
rust-version = { workspace = true }
authors = { workspace = true }
license = { workspace = true }
homepage = { workspace = true }
include = { workspace = true }
repository = "https://github.com/microsoft/oxidizer/tree/main/crates/internity_macros_impl"

[package.metadata.anvil.miri]
exclude = true

[package.metadata.cargo_check_external_types]
allowed_external_types = [
    "proc_macro2::*",
    "syn::attr::*",
    "syn::error::*",
    "syn::path::*",
    "syn::ty::*",
]

[package.metadata.docs.rs]
all-features = true

[dependencies]
proc-macro2 = { workspace = true }
quote = { workspace = true }
syn = { workspace = true, features = ["full", "derive", "printing", "parsing", "extra-traits", "proc-macro", "clone-impls"] }

# >>> anvil-managed: anvil-lints
[lints]
workspace = true
# <<< anvil-managed: anvil-lints
