// Copyright (c) Microsoft Corporation.
// Licensed under the MIT License.

//! Deterministic source generation for the HTTP dispatch scaling fixture.

use std::fmt::Write as _;

const ROUTE_COUNTS: [usize; 3] = [16, 128, 1_024];
const ROCKET_BATCH_SIZE: usize = 64;

macro_rules! line {
    ($output:expr) => {
        $output.push('\n');
    };
    ($output:expr, $($arg:tt)*) => {
        writeln!($output, $($arg)*)
            .expect("writing generated Rust source to a String cannot fail");
    };
}

/// Produces the complete checked-in HTTP dispatch scaling fixture.
#[must_use]
pub(crate) fn generated_source() -> String {
    let mut output = String::new();
    line!(output, "// Copyright (c) Microsoft Corporation.");
    line!(output, "// Licensed under the MIT License.");
    line!(output);
    line!(output, "// @generated by scripts/generate_http_dispatch_scaling.rs; DO NOT EDIT.");
    line!(output, "// Regenerate from the repository root with:");
    line!(
        output,
        "// cargo +nightly -Zscript crates/routerama/scripts/generate_http_dispatch_scaling.rs"
    );
    line!(output);

    for route_count in ROUTE_COUNTS {
        emit_route_table(&mut output, route_count);
    }
    for route_count in ROUTE_COUNTS {
        emit_routerama_fixture(&mut output, route_count);
    }
    for route_count in ROUTE_COUNTS {
        emit_rocket_fixture(&mut output, route_count);
    }

    output.truncate(output.trim_end_matches('\n').len());
    output.push('\n');
    output
}

fn emit_route_table(output: &mut String, route_count: usize) {
    line!(output, "static ROUTES_{route_count}: [RouteSpec; {route_count}] = [");
    for index in 0..route_count {
        let set_segment = set_segment(route_count);
        let route_segment = route_segment(index);
        let path = route_path(route_count, index);
        let response = response(index);
        line!(output, "    RouteSpec {{");
        line!(output, "        path: \"{path}\",");
        line!(output, "        set_segment: \"{set_segment}\",");
        line!(output, "        route_segment: \"{route_segment}\",");
        line!(output, "        response: \"{response}\",");
        line!(output, "    }},");
    }
    line!(output, "];");
    line!(
        output,
        "const MISS_{route_count}: &str = \"/scale/{}/missing\";",
        set_segment(route_count)
    );
    line!(output);
}

fn emit_routerama_fixture(output: &mut String, route_count: usize) {
    let service = format!("RouteramaRoutes{route_count}");
    line!(output, "struct {service};");
    line!(output);
    line!(output, "#[allow(");
    line!(output, "    clippy::allow_attributes,");
    line!(output, "    unknown_lints,");
    line!(output, "    clippy::unused_async,");
    line!(output, "    clippy::unused_async_trait_impl,");
    if route_count >= 1024 {
        line!(output, "    clippy::large_stack_frames,");
        line!(
            output,
            "    reason = \"Routerama handlers stay direct; the 1,024-route fixture intentionally exceeds Clippy's generated stack-frame threshold; `clippy::unused_async_trait_impl` does not exist before clippy 0.1.98\""
        );
    } else {
        line!(
            output,
            "    reason = \"Routerama route handlers must be async; `clippy::unused_async_trait_impl` does not exist before clippy 0.1.98\""
        );
    }
    line!(output, ")]");
    line!(output, "#[routerama::route::router]");
    line!(output, "impl {service} {{");
    for index in 0..route_count {
        let path = route_path(route_count, index);
        let response = response(index);
        line!(output, "    #[route(GET, \"{path}\")]");
        line!(output, "    async fn route_{index:04}(&self) -> RouteramaScalingResponse {{");
        line!(output, "        routerama_scaling_response(\"{response}\")");
        line!(output, "    }}");
        line!(output);
    }
    line!(output, "}}");
    line!(
        output,
        "define_routerama_factory!(build_routerama_{route_count}_factory, {service}, Routes{route_count});"
    );
    line!(output);
}

fn emit_rocket_fixture(output: &mut String, route_count: usize) {
    for index in 0..route_count {
        line!(
            output,
            "define_rocket_route!(rocket_{route_count}_{index:04}, \"{}\", \"{}\");",
            route_path(route_count, index),
            response(index)
        );
    }
    line!(output);
    for (batch, batch_start) in (0..route_count).step_by(ROCKET_BATCH_SIZE).enumerate() {
        let batch_end = (batch_start + ROCKET_BATCH_SIZE).min(route_count);
        line!(output, "#[expect(");
        line!(output, "    clippy::redundant_type_annotations,");
        line!(output, "    reason = \"Rocket's routes macro emits explicit internal types\"");
        line!(output, ")]");
        line!(output, "fn rocket_routes_{route_count}_batch_{batch:02}() -> Vec<rocket::Route> {{");
        line!(output, "    rocket::routes![");
        for index in batch_start..batch_end {
            line!(output, "        rocket_{route_count}_{index:04},");
        }
        line!(output, "    ]");
        line!(output, "}}");
        line!(output);
    }
    line!(output, "#[expect(");
    line!(output, "    clippy::redundant_type_annotations,");
    line!(output, "    reason = \"Rocket's catchers macro emits explicit internal types\"");
    line!(output, ")]");
    line!(output, "fn rocket_routes_{route_count}() -> rocket::Rocket<rocket::Build> {{");
    line!(output, "    let application = rocket_scaling_application();");
    for (batch, _) in (0..route_count).step_by(ROCKET_BATCH_SIZE).enumerate() {
        line!(
            output,
            "    let application = application.mount(\"/\", rocket_routes_{route_count}_batch_{batch:02}());"
        );
    }
    line!(output, "    application.register(");
    line!(output, "        \"/\",");
    line!(output, "        rocket::catchers![rocket_scaling_not_found],");
    line!(output, "    )");
    line!(output, "}}");
    line!(output);
}

fn set_segment(route_count: usize) -> String {
    format!("routes-{route_count:04}")
}

fn route_segment(index: usize) -> String {
    format!("route-{index:04}")
}

fn route_path(route_count: usize, index: usize) -> String {
    format!("/scale/{}/{}", set_segment(route_count), route_segment(index))
}

fn response(index: usize) -> String {
    format!("route-{index:04}")
}
