// Copyright (c) Microsoft Corporation.
// Licensed under the MIT License.

//! Deterministic source generation for the HTTP dispatch scaling fixture.

use std::fmt::Write as _;

const ROUTE_COUNTS: [usize; 3] = [16, 128, 1_024];
const ROCKET_BATCH_SIZE: usize = 64;

#[expect(dead_code, reason = "the generator script and freshness test use complementary fixture metadata")]
pub(crate) struct GeneratedLiteralFixture {
    pub(crate) route_count: usize,
    pub(crate) path: &'static str,
    pub(crate) source: String,
}

macro_rules! line {
    ($output:expr) => {
        $output.push('\n');
    };
    ($output:expr, $($arg:tt)*) => {
        writeln!($output, $($arg)*)
            .expect("writing generated Rust source to a String cannot fail");
    };
}

/// Produces the complete checked-in HTTP dispatch scaling fixture.
#[must_use]
pub(crate) fn generated_source() -> String {
    let mut output = String::new();
    line!(output, "// Copyright (c) Microsoft Corporation.");
    line!(output, "// Licensed under the MIT License.");
    line!(output);
    line!(output, "// @generated by scripts/generate_http_dispatch_scaling.rs; DO NOT EDIT.");
    line!(output, "// Regenerate from the repository root with:");
    line!(
        output,
        "// cargo +nightly -Zscript crates/routerama/scripts/generate_http_dispatch_scaling.rs"
    );
    line!(output);

    for route_count in ROUTE_COUNTS {
        emit_route_table(&mut output, route_count);
    }

    for route_count in ROUTE_COUNTS {
        emit_routerama_fixture(&mut output, route_count);
    }
    for route_count in ROUTE_COUNTS {
        emit_rocket_fixture(&mut output, route_count);
    }

    output.truncate(output.trim_end_matches('\n').len());
    output.push('\n');
    output
}

/// Produces literal-only Routerama controls isolated by route-set size.
#[must_use]
pub(crate) fn generated_literal_fixtures() -> [GeneratedLiteralFixture; 3] {
    ROUTE_COUNTS.map(|route_count| GeneratedLiteralFixture {
        route_count,
        path: match route_count {
            16 => "benches/generated/literal_controls_16.rs",
            128 => "benches/generated/literal_controls_128.rs",
            1_024 => "benches/generated/literal_controls_1024.rs",
            _ => unreachable!("ROUTE_COUNTS contains only named Cargo targets"),
        },
        source: generated_literal_source(route_count),
    })
}

fn generated_literal_source(route_count: usize) -> String {
    let mut output = String::new();
    line!(output, "// Copyright (c) Microsoft Corporation.");
    line!(output, "// Licensed under the MIT License.");
    line!(output);
    line!(output, "// @generated by scripts/generate_http_dispatch_scaling.rs; DO NOT EDIT.");
    line!(
        output,
        "// Literal-only compile/size control with {route_count} routes per topology."
    );
    line!(output);
    line!(output, "pub(crate) const ROUTE_COUNT: usize = {route_count};");
    line!(output);
    emit_literal_resolver(&mut output, route_count, "WideFanout", wide_path);
    emit_literal_resolver(&mut output, route_count, "DeepChain", deep_path);
    emit_literal_resolver(&mut output, route_count, "TerminalSuffix", terminal_path);
    line!(output, "pub(crate) struct Routers {{");
    line!(output, "    wide_fanout: WideFanoutResolver,");
    line!(output, "    deep_chain: DeepChainResolver,");
    line!(output, "    terminal_suffix: TerminalSuffixResolver,");
    line!(output, "}}");
    line!(output);
    line!(output, "impl Routers {{");
    line!(output, "    pub(crate) fn new() -> Self {{");
    line!(output, "        Self {{");
    line!(output, "            wide_fanout: WideFanout::resolver(),");
    line!(output, "            deep_chain: DeepChain::resolver(),");
    line!(output, "            terminal_suffix: TerminalSuffix::resolver(),");
    line!(output, "        }}");
    line!(output, "    }}");
    line!(output);
    line!(output, "    #[expect(");
    line!(output, "        clippy::panic,");
    line!(
        output,
        "        reason = \"an out-of-range generated fixture selector is a benchmark invariant violation\""
    );
    line!(output, "    )]");
    line!(
        output,
        "    pub(crate) fn run(&self, shape: usize, scenario: usize) -> Option<usize> {{"
    );
    line!(output, "        let index = match scenario {{");
    line!(output, "            0 => 0,");
    line!(output, "            1 => ROUTE_COUNT / 2,");
    line!(output, "            2 => ROUTE_COUNT - 1,");
    line!(output, "            3 => ROUTE_COUNT,");
    line!(output, "            _ => panic!(\"literal-control scenario is out of range\"),");
    line!(output, "        }};");
    line!(output, "        match shape {{");
    line!(output, "            0 => self");
    line!(output, "                .wide_fanout");
    line!(output, "                .resolve(\"GET\", WIDE_FANOUT_PATHS[index])");
    line!(output, "                .ok()");
    line!(output, "                .map(|route| route as usize),");
    line!(output, "            1 => self");
    line!(output, "                .deep_chain");
    line!(output, "                .resolve(\"GET\", DEEP_CHAIN_PATHS[index])");
    line!(output, "                .ok()");
    line!(output, "                .map(|route| route as usize),");
    line!(output, "            2 => self");
    line!(output, "                .terminal_suffix");
    line!(output, "                .resolve(\"GET\", TERMINAL_SUFFIX_PATHS[index])");
    line!(output, "                .ok()");
    line!(output, "                .map(|route| route as usize),");
    line!(output, "            _ => panic!(\"literal-control shape is out of range\"),");
    line!(output, "        }}");
    line!(output, "    }}");
    line!(output, "}}");
    line!(output);
    line!(output, "pub(crate) fn assert_equivalent(routers: &Routers) {{");
    line!(output, "    for shape in 0..3 {{");
    line!(output, "        for scenario in 0..4 {{");
    line!(output, "            let expected = match scenario {{");
    line!(output, "                0 => Some(0),");
    line!(output, "                1 => Some(ROUTE_COUNT / 2),");
    line!(output, "                2 => Some(ROUTE_COUNT - 1),");
    line!(output, "                3 => None,");
    line!(output, "                _ => unreachable!(),");
    line!(output, "            }};");
    line!(output, "            assert_eq!(routers.run(shape, scenario), expected);");
    line!(output, "        }}");
    line!(output, "    }}");
    line!(output, "}}");

    output
}

fn emit_literal_resolver(output: &mut String, route_count: usize, name: &str, path: fn(usize) -> String) {
    let upper = shouty(name);
    line!(output, "#[::routerama::resolve::resolver]");
    line!(output, "#[derive(Debug)]");
    line!(output, "enum {name} {{");
    for index in 0..route_count {
        line!(output, "    #[route(GET, \"{}\")]", path(index));
        line!(output, "    Route{index:04},");
    }
    line!(output, "}}");
    line!(output);
    line!(output, "static {upper}_PATHS: [&str; {}] = [", route_count + 1);
    for index in 0..route_count {
        line!(output, "    \"{}\",", path(index));
    }
    line!(output, "    \"{}\",", literal_miss(name));
    line!(output, "];");
    line!(output);
}

fn wide_path(index: usize) -> String {
    format!("/literal-{index:04}")
}

fn deep_path(index: usize) -> String {
    format!("/deep/01/02/03/04/05/06/07/08/09/10/11/12/13/14/15/16/route-{index:04}")
}

fn terminal_path(index: usize) -> String {
    format!("/api/v1/resources/shared-prefix/entry-{index:04}-terminal.json")
}

fn literal_miss(name: &str) -> String {
    match name {
        "WideFanout" => "/literal-missing".to_owned(),
        "DeepChain" => "/deep/01/02/03/04/05/06/07/08/09/10/11/12/13/14/15/16/missing".to_owned(),
        "TerminalSuffix" => "/api/v1/resources/shared-prefix/entry-missing-terminal.json".to_owned(),
        _ => unreachable!("only the three literal-control shapes are generated"),
    }
}

fn shouty(name: &str) -> String {
    let mut output = String::new();
    for (index, character) in name.chars().enumerate() {
        if index != 0 && character.is_ascii_uppercase() {
            output.push('_');
        }
        output.push(character.to_ascii_uppercase());
    }
    output
}

fn emit_route_table(output: &mut String, route_count: usize) {
    line!(output, "static ROUTES_{route_count}: [RouteSpec; {route_count}] = [");
    for index in 0..route_count {
        let set_segment = set_segment(route_count);
        let route_segment = route_segment(index);
        let path = route_path(route_count, index);
        let response = response(index);
        line!(output, "    RouteSpec {{");
        line!(output, "        path: \"{path}\",");
        line!(output, "        set_segment: \"{set_segment}\",");
        line!(output, "        route_segment: \"{route_segment}\",");
        line!(output, "        response: \"{response}\",");
        line!(output, "    }},");
    }
    line!(output, "];");
    line!(
        output,
        "const MISS_{route_count}: &str = \"/scale/{}/missing\";",
        set_segment(route_count)
    );
    line!(output);
}

fn emit_routerama_fixture(output: &mut String, route_count: usize) {
    let service = format!("RouteramaRoutes{route_count}");
    line!(output, "struct {service};");
    line!(output);
    line!(output, "#[allow(");
    line!(output, "    clippy::allow_attributes,");
    line!(output, "    unknown_lints,");
    line!(output, "    clippy::unused_async,");
    line!(output, "    clippy::unused_async_trait_impl,");
    if route_count >= 1024 {
        line!(output, "    clippy::large_stack_frames,");
        line!(
            output,
            "    reason = \"Routerama handlers stay direct; the 1,024-route fixture intentionally exceeds Clippy's generated stack-frame threshold; `clippy::unused_async_trait_impl` does not exist before clippy 0.1.98\""
        );
    } else {
        line!(
            output,
            "    reason = \"Routerama route handlers must be async; `clippy::unused_async_trait_impl` does not exist before clippy 0.1.98\""
        );
    }
    line!(output, ")]");
    line!(output, "#[routerama::route::router]");
    line!(output, "impl {service} {{");
    for index in 0..route_count {
        let path = route_path(route_count, index);
        let response = response(index);
        line!(output, "    #[route(GET, \"{path}\")]");
        line!(output, "    async fn route_{index:04}(&self) -> RouteramaScalingResponse {{");
        line!(output, "        routerama_scaling_response(\"{response}\")");
        line!(output, "    }}");
        line!(output);
    }
    line!(output, "}}");
    line!(
        output,
        "define_routerama_factory!(build_routerama_{route_count}_factory, {service}, Routes{route_count});"
    );
    line!(output);
}

fn emit_rocket_fixture(output: &mut String, route_count: usize) {
    for index in 0..route_count {
        line!(
            output,
            "define_rocket_route!(rocket_{route_count}_{index:04}, \"{}\", \"{}\");",
            route_path(route_count, index),
            response(index)
        );
    }
    line!(output);
    for (batch, batch_start) in (0..route_count).step_by(ROCKET_BATCH_SIZE).enumerate() {
        let batch_end = (batch_start + ROCKET_BATCH_SIZE).min(route_count);
        line!(output, "#[expect(");
        line!(output, "    clippy::redundant_type_annotations,");
        line!(output, "    reason = \"Rocket's routes macro emits explicit internal types\"");
        line!(output, ")]");
        line!(output, "fn rocket_routes_{route_count}_batch_{batch:02}() -> Vec<rocket::Route> {{");
        line!(output, "    rocket::routes![");
        for index in batch_start..batch_end {
            line!(output, "        rocket_{route_count}_{index:04},");
        }
        line!(output, "    ]");
        line!(output, "}}");
        line!(output);
    }
    line!(output, "#[expect(");
    line!(output, "    clippy::redundant_type_annotations,");
    line!(output, "    reason = \"Rocket's catchers macro emits explicit internal types\"");
    line!(output, ")]");
    line!(output, "fn rocket_routes_{route_count}() -> rocket::Rocket<rocket::Build> {{");
    line!(output, "    let application = rocket_scaling_application();");
    for (batch, _) in (0..route_count).step_by(ROCKET_BATCH_SIZE).enumerate() {
        line!(
            output,
            "    let application = application.mount(\"/\", rocket_routes_{route_count}_batch_{batch:02}());"
        );
    }
    line!(output, "    application.register(");
    line!(output, "        \"/\",");
    line!(output, "        rocket::catchers![rocket_scaling_not_found],");
    line!(output, "    )");
    line!(output, "}}");
    line!(output);
}

fn set_segment(route_count: usize) -> String {
    format!("routes-{route_count:04}")
}

fn route_segment(index: usize) -> String {
    format!("route-{index:04}")
}

fn route_path(route_count: usize, index: usize) -> String {
    format!("/scale/{}/{}", set_segment(route_count), route_segment(index))
}

fn response(index: usize) -> String {
    format!("route-{index:04}")
}
