// Copyright (c) Microsoft Corporation.
// Licensed under the MIT License.

//! Deterministic source generation for constant-route-count response-body
//! variant fixtures.

use std::fmt::Write as _;

const ROUTE_COUNT: usize = 16;
const VARIANT_COUNTS: [usize; 3] = [1, 4, 16];

#[expect(dead_code, reason = "the script and freshness test consume complementary fixture metadata")]
pub(crate) struct GeneratedFixture {
    pub(crate) variant_count: usize,
    pub(crate) path: &'static str,
    pub(crate) source: String,
}

macro_rules! line {
    ($output:expr) => {
        $output.push('\n');
    };
    ($output:expr, $($arg:tt)*) => {
        writeln!($output, $($arg)*).expect("writing generated Rust source to a String cannot fail");
    };
}

/// Produces all checked-in response-body variant fixtures.
#[must_use]
pub(crate) fn generated_fixtures() -> [GeneratedFixture; 3] {
    VARIANT_COUNTS.map(|variant_count| GeneratedFixture {
        variant_count,
        path: match variant_count {
            1 => "benches/routerama_response_body_variants_1.rs",
            4 => "benches/routerama_response_body_variants_4.rs",
            16 => "benches/routerama_response_body_variants_16.rs",
            _ => unreachable!("VARIANT_COUNTS contains only named Cargo targets"),
        },
        source: generated_source(variant_count),
    })
}

#[expect(
    clippy::too_many_lines,
    reason = "keeping each generated standalone control in one ordered template makes cross-target drift visible"
)]
fn generated_source(variant_count: usize) -> String {
    let mut output = String::new();
    let body_type_label = if variant_count == 1 { "body type" } else { "body types" };
    line!(output, "// Copyright (c) Microsoft Corporation.");
    line!(output, "// Licensed under the MIT License.");
    line!(output);
    line!(output, "// @generated by scripts/generate_response_body_variants.rs; DO NOT EDIT.");
    line!(
        output,
        "// Constant controls: {ROUTE_COUNT} routes and {variant_count} distinct handler {body_type_label}."
    );
    line!(output);
    line!(
        output,
        "#![allow(missing_docs, reason = \"generated compile-size fixture needs no API documentation\")]"
    );
    line!(
        output,
        "#![expect(clippy::panic, reason = \"a pending or failed in-memory fixture is a benchmark invariant violation\")]"
    );
    line!(output);
    line!(output, "use std::convert::Infallible;");
    line!(output, "use std::pin::{{Pin, pin}};");
    line!(output, "use std::task::{{Context, Poll, Waker}};");
    line!(output);
    line!(output, "use bytes::Bytes;");
    line!(output, "use http_body::{{Body as HttpBody, Frame, SizeHint}};");
    line!(output, "use routerama::response::{{Body, Response}};");
    line!(output, "use routerama::route::Request;");
    line!(output);
    line!(output, "struct VariantBody<const ID: usize>(Body);");
    line!(output);
    line!(output, "impl<const ID: usize> HttpBody for VariantBody<ID> {{");
    line!(output, "    type Data = Bytes;");
    line!(output, "    type Error = Infallible;");
    line!(output);
    line!(
        output,
        "    fn poll_frame(mut self: Pin<&mut Self>, cx: &mut Context<'_>) -> Poll<Option<Result<Frame<Self::Data>, Self::Error>>> {{"
    );
    line!(output, "        Pin::new(&mut self.0).poll_frame(cx)");
    line!(output, "    }}");
    line!(output);
    line!(output, "    fn is_end_stream(&self) -> bool {{");
    line!(output, "        self.0.is_end_stream()");
    line!(output, "    }}");
    line!(output);
    line!(output, "    fn size_hint(&self) -> SizeHint {{");
    line!(output, "        self.0.size_hint()");
    line!(output, "    }}");
    line!(output, "}}");
    line!(output);
    line!(output, "struct VariantService;");
    line!(output);
    line!(output, "#[allow(");
    line!(output, "    clippy::allow_attributes,");
    line!(output, "    unknown_lints,");
    line!(output, "    clippy::unused_async,");
    line!(output, "    clippy::unused_async_trait_impl,");
    line!(
        output,
        "    reason = \"router handlers must be async; `clippy::unused_async_trait_impl` does not exist before clippy 0.1.98\""
    );
    line!(output, ")]");
    line!(output, "#[routerama::route::router]");
    line!(output, "impl VariantService {{");
    for route in 0..ROUTE_COUNT {
        let body_variant = route % variant_count;
        line!(output, "    #[route(GET, \"/variants/route-{route:02}\")]");
        line!(
            output,
            "    async fn route_{route:02}(&self) -> Response<VariantBody<{body_variant}>> {{"
        );
        line!(
            output,
            "        Response::new(VariantBody(Body::from(Bytes::from_static(b\"variant-route-{route:02}\"))))"
        );
        line!(output, "    }}");
        line!(output);
    }
    output.truncate(output.trim_end_matches('\n').len());
    line!(output);
    line!(output, "}}");
    line!(output);
    line!(output, "static SERVICE: VariantService = VariantService;");
    line!(output);
    line!(output, "fn run_ready<F: std::future::Future>(future: F) -> F::Output {{");
    line!(output, "    let mut future = pin!(future);");
    line!(output, "    let mut context = Context::from_waker(Waker::noop());");
    line!(output, "    match future.as_mut().poll(&mut context) {{");
    line!(output, "        Poll::Ready(output) => output,");
    line!(
        output,
        "        Poll::Pending => panic!(\"the generated route fixture must be immediately ready\"),"
    );
    line!(output, "    }}");
    line!(output, "}}");
    line!(output);
    line!(output, "fn observe<B>(body: B) -> (usize, u64)");
    line!(output, "where");
    line!(output, "    B: HttpBody<Data = Bytes>,");
    line!(output, "    B::Error: std::fmt::Debug,");
    line!(output, "{{");
    line!(output, "    let mut body = pin!(body);");
    line!(output, "    let mut context = Context::from_waker(Waker::noop());");
    line!(output, "    let mut length = 0;");
    line!(output, "    let mut hash = 0xcbf2_9ce4_8422_2325_u64;");
    line!(output, "    loop {{");
    line!(output, "        match body.as_mut().poll_frame(&mut context) {{");
    line!(output, "            Poll::Ready(Some(Ok(frame))) => {{");
    line!(output, "                if let Ok(data) = frame.into_data() {{");
    line!(output, "                    length += data.len();");
    line!(output, "                    for byte in data {{");
    line!(output, "                        hash ^= u64::from(byte);");
    line!(output, "                        hash = hash.wrapping_mul(0x0000_0100_0000_01b3);");
    line!(output, "                    }}");
    line!(output, "                }}");
    line!(output, "            }}");
    line!(
        output,
        "            Poll::Ready(Some(Err(error))) => panic!(\"fixture body failed: {}\"),",
        "{error:?}"
    );
    line!(output, "            Poll::Ready(None) => return (length, hash),");
    line!(
        output,
        "            Poll::Pending => panic!(\"the generated body fixture must be immediately ready\"),"
    );
    line!(output, "        }}");
    line!(output, "    }}");
    line!(output, "}}");
    line!(output);
    line!(output, "fn main() {{");
    line!(output, "    let path = std::hint::black_box(\"/variants/route-15\");");
    line!(output, "    let mut request = Request::new(());");
    line!(
        output,
        "    *request.uri_mut() = path.parse().expect(\"the generated fixture path is a valid URI\");"
    );
    line!(output, "    let response = run_ready(SERVICE.route(request, &()));");
    line!(output, "    let status = response.status().as_u16();");
    line!(output, "    std::hint::black_box((status, observe(response.into_body())));");
    line!(output, "}}");

    output
}
