#!/bin/sh
# GENERATED BY cargo-anvil. DO NOT EDIT DIRECTLY.
set -eu

if [ "$(id -u)" -ne 0 ]; then
    if [ -z "${HOME:-}" ] || [ "$HOME" = "/" ]; then
        HOME="/tmp/anvil-user"
        export HOME
    fi

    user_cargo_home="$HOME/.cargo"
    mkdir -p "$user_cargo_home"
    for file in config.toml .crates.toml .crates2.json; do
        if [ -r "$CARGO_HOME/$file" ]; then
            cp -f "$CARGO_HOME/$file" "$user_cargo_home/$file"
        fi
    done
    export CARGO_HOME="$user_cargo_home"
    ln -sfn /usr/local/cargo/registry "$CARGO_HOME/registry"
    ln -sfn /usr/local/cargo/git "$CARGO_HOME/git"
fi

exec "$@"
