#!/usr/bin/env bash
# GENERATED BY cargo-anvil. DO NOT EDIT DIRECTLY.
set -euo pipefail

if ! repo_root="$(git rev-parse --show-toplevel 2>/dev/null)"; then
    echo 'anvil-container must run from a Git repository.' >&2
    exit 1
fi

toolchain_path="$repo_root/rust-toolchain.toml"
if [[ ! -f "$toolchain_path" ]]; then
    echo 'anvil-container requires a repository-owned rust-toolchain.toml.' >&2
    exit 1
fi

container_dir="$repo_root/.anvil/container"
container_recipe="justfiles/anvil/container.just"
default_base_image="$(sed -n 's/^ARG BASE_IMAGE=//p' "$container_dir/Containerfile" | head -n 1)"
if [[ -z "$default_base_image" ]]; then
    echo 'anvil-container: Containerfile must define ARG BASE_IMAGE=<digest-pinned-image>.' >&2
    exit 1
fi
base_image="${ANVIL_CONTAINER_BASE_IMAGE:-$default_base_image}"
if [[ ! "$base_image" =~ @sha256:[0-9a-fA-F]{64}$ ]]; then
    echo 'anvil-container: ANVIL_CONTAINER_BASE_IMAGE must be pinned by sha256 digest (image@sha256:<64 hex characters>).' >&2
    exit 1
fi
inputs=(rust-toolchain.toml)
while IFS= read -r path; do
    relative="${path#"$repo_root"/}"
    # The container entry recipe drives execution on the host; it is not
    # image content, so it must not participate in image identity.
    if [[ "$relative" != "$container_recipe" ]]; then
        inputs+=("$relative")
    fi
done < <(find "$repo_root/justfiles/anvil" -type f -name '*.just' -print)

for path in "$container_dir"/*; do
    [[ -f "$path" ]] || continue
    case "${path##*/}" in
        image-id.ps1 | image-id.sh | README.md \
            | run-in-container.ps1 | run-in-container.sh \
            | customize.sh | customize.ps1) continue ;;
    esac
    inputs+=("${path#"$repo_root"/}")
done

if command -v sha256sum >/dev/null 2>&1; then
    hash_command=(sha256sum)
elif command -v shasum >/dev/null 2>&1; then
    hash_command=(shasum -a 256)
else
    echo 'anvil-container: sha256sum or shasum is required.' >&2
    exit 1
fi

write_normalized_file() {
    local path="$1"
    local line status
    while true; do
        line=""
        if IFS= read -r line <&3; then
            status=0
        else
            status=$?
        fi
        if ((status != 0)) && [[ -z "$line" ]]; then
            break
        fi
        printf '%s' "${line%$'\r'}"
        if ((status == 0)); then
            printf '\n'
        else
            break
        fi
    done 3<"$path"
}

{
    printf 'ANVIL_CONTAINER_BASE_IMAGE\n%s\n' "$base_image"
    while IFS= read -r relative; do
        path="$repo_root/$relative"
        if [[ ! -f "$path" ]]; then
            echo "Container image input is missing: $relative" >&2
            exit 1
        fi
        printf '%s\n' "$relative"
        write_normalized_file "$path"
        printf '\n'
    done < <(printf '%s\n' "${inputs[@]}" | LC_ALL=C sort -u)
} | "${hash_command[@]}" | awk '{print $1}'
