#!/usr/bin/env bash
# GENERATED BY cargo-anvil. DO NOT EDIT DIRECTLY.
set -euo pipefail

if [[ -n "${ANVIL_IN_CONTAINER:-}" ]]; then
    if (($# == 0)); then exec bash; else exec just "$@"; fi
fi

for recipe_arg in "$@"; do
    if [[ ! "$recipe_arg" =~ ^_?anvil-[A-Za-z0-9-]+$ ]]; then
        echo "anvil-container: expected each argument to be an anvil-* recipe, got '$recipe_arg'." >&2
        exit 2
    fi
done

anvil_recipe_needs_github_token() {
    case "$1" in
        anvil-aprz | anvil-scheduled | _anvil-scheduled | anvil-scheduled-advisories \
            | anvil-full | _anvil-full) return 0 ;;
        *) return 1 ;;
    esac
}

version_at_least() {
    local found="${1%%[-+]*}"
    local required="${2%%[-+]*}"
    local found_major found_minor found_patch found_extra
    local required_major required_minor required_patch required_extra
    IFS=. read -r found_major found_minor found_patch found_extra <<<"$found"
    IFS=. read -r required_major required_minor required_patch required_extra <<<"$required"
    found_patch="${found_patch:-0}"
    required_patch="${required_patch:-0}"
    for component in \
        "$found_major" "$found_minor" "$found_patch" \
        "$required_major" "$required_minor" "$required_patch"
    do
        case "$component" in
            '' | *[!0-9]*) return 2 ;;
        esac
    done
    if ((found_major != required_major)); then ((found_major > required_major)); return; fi
    if ((found_minor != required_minor)); then ((found_minor > required_minor)); return; fi
    ((found_patch >= required_patch))
}

command -v docker >/dev/null 2>&1 || {
    echo "anvil-container: Docker Engine is required. See .anvil/container/README.md." >&2
    exit 1
}

version="$(docker version --format '{{.Server.Version}}' 2>/dev/null)" || {
    echo "anvil-container: Docker Engine is unavailable. Start the Docker service and ensure the current user can access it." >&2
    exit 1
}
minimum="23.0.0"
if ! version_at_least "$version" "$minimum"; then
    echo "anvil-container: Docker Engine $minimum or newer is required (found $version)." >&2
    exit 1
fi
host_arch="$(uname -m 2>/dev/null || true)"
case "$host_arch" in
    x86_64 | amd64 | '') ;;
    *) echo "anvil-container: warning: $host_arch requires emulation for linux/amd64; builds and checks may be substantially slower." >&2 ;;
esac

if ! repo_root="$(git rev-parse --show-toplevel 2>/dev/null)"; then
    echo 'anvil-container must run from a Git repository.' >&2
    exit 1
fi
script_dir="$repo_root/.anvil/container"
default_base_image="$(sed -n 's/^ARG BASE_IMAGE=//p' "$script_dir/Containerfile" | head -n 1)"
if [[ -z "$default_base_image" ]]; then
    echo 'anvil-container: Containerfile must define ARG BASE_IMAGE=<digest-pinned-image>.' >&2
    exit 1
fi
base_image="${ANVIL_CONTAINER_BASE_IMAGE:-$default_base_image}"
if [[ ! "$base_image" =~ @sha256:[0-9a-fA-F]{64}$ ]]; then
    echo 'anvil-container: ANVIL_CONTAINER_BASE_IMAGE must be pinned by sha256 digest (image@sha256:<64 hex characters>).' >&2
    exit 1
fi
image_id="$(bash "$script_dir/image-id.sh")"
image_base="${ANVIL_CONTAINER_IMAGE:-anvil-dev}"
image="${image_base}:${image_id}"
if command -v sha256sum >/dev/null 2>&1; then
    repo_id="$(printf '%s' "$repo_root" | sha256sum | cut -c1-12)"
elif command -v shasum >/dev/null 2>&1; then
    repo_id="$(printf '%s' "$repo_root" | shasum -a 256 | cut -c1-12)"
else
    echo 'anvil-container: sha256sum or shasum is required.' >&2
    exit 1
fi
target_volume="anvil-target-${repo_id}-${image_id:0:12}"

needs_github_token=false
for recipe_arg in "$@"; do
    if anvil_recipe_needs_github_token "$recipe_arg"; then
        needs_github_token=true
        break
    fi
done
runs_only_github_check=false
if (($# == 1)) && [[ "$1" == "anvil-aprz" ]]; then
    runs_only_github_check=true
fi
github_token=""

# Customization contract: check warm/cold state before sourcing so
# customization needed only for image construction can be skipped on a warm
# run, then expose read-only inputs. See docs/design/containers.md.
if docker image inspect "$image" >/dev/null 2>&1; then
    image_exists=true
else
    image_exists=false
fi

readonly ANVIL_CONTAINER_REPO_ROOT="$repo_root"
readonly ANVIL_CONTAINER_DIR="$script_dir"
readonly ANVIL_CONTAINER_RESOLVED_IMAGE="$image"
readonly ANVIL_CONTAINER_IMAGE_EXISTS="$image_exists"
declare -a ANVIL_CONTAINER_REQUESTED_RECIPES=("$@")
readonly ANVIL_CONTAINER_REQUESTED_RECIPES

# Customization outputs, initialized before sourcing so a missing customize.sh
# leaves every phase a documented no-op.
ANVIL_CONTAINER_BUILD_ARGS=()
ANVIL_CONTAINER_PREPARE_ARGS=()
ANVIL_CONTAINER_PREPARE_COMMAND=()
ANVIL_CONTAINER_RUN_ARGS=()
ANVIL_CONTAINER_NEEDS_GITHUB_TOKEN="$needs_github_token"
ANVIL_CONTAINER_CLEANUP=:
github_token_file=""
cleanup() {
    if [[ -n "$github_token_file" ]]; then rm -f -- "$github_token_file"; fi
    "$ANVIL_CONTAINER_CLEANUP"
}
trap cleanup EXIT

customize_script="$script_dir/customize.sh"
legacy_customize_script="$repo_root/justfiles/anvil/container/customize.sh"
if [[ ! -f "$customize_script" && -f "$legacy_customize_script" ]]; then
    echo "anvil-container: warning: ignoring justfiles/anvil/container/customize.sh; container assets moved to .anvil/container/. Move the file to .anvil/container/customize.sh to keep it active." >&2
fi
if [[ -f "$customize_script" ]]; then
    # shellcheck source=/dev/null
    source "$customize_script"
fi

# Bash 3.2 has neither namerefs (the nameref flag on `local`/`declare`, Bash
# 4.3+) nor safe `set -u` expansion of empty-but-
# declared arrays (fixed in Bash 4.4). Elements are passed positionally
# instead of by nameref, and every expansion of a possibly-empty array uses
# the `${arr[@]+"${arr[@]}"}` idiom: unset/empty-under-old-Bash arrays vanish
# entirely instead of raising "unbound variable", while non-empty arrays
# still expand element-for-element.
anvil_container_validate_array() {
    local name="$1"
    shift
    local declaration value
    declaration="$(declare -p "$name" 2>/dev/null || true)"
    if [[ ! "$declaration" =~ ^declare\ -[^[:space:]]*a[^[:space:]]*\  ]]; then
        echo "anvil-container: $name must be a string array." >&2
        exit 1
    fi
    for value in "$@"; do
        if [[ -z "$value" ]]; then
            echo "anvil-container: $name entries must be non-empty strings." >&2
            exit 1
        fi
    done
}
anvil_container_validate_build_args() {
    local expect_secret_value=false value
    for value in "$@"; do
        if "$expect_secret_value"; then
            expect_secret_value=false
            continue
        fi
        case "$value" in
            --secret) expect_secret_value=true ;;
            --secret=*) ;;
            *)
                echo 'anvil-container: ANVIL_CONTAINER_BUILD_ARGS accepts only BuildKit --secret arguments; static build behavior must use hashed container files.' >&2
                exit 1
                ;;
        esac
    done
    if "$expect_secret_value"; then
        echo 'anvil-container: ANVIL_CONTAINER_BUILD_ARGS requires a value after --secret.' >&2
        exit 1
    fi
}
anvil_container_validate_array ANVIL_CONTAINER_BUILD_ARGS ${ANVIL_CONTAINER_BUILD_ARGS[@]+"${ANVIL_CONTAINER_BUILD_ARGS[@]}"}
anvil_container_validate_array ANVIL_CONTAINER_PREPARE_ARGS ${ANVIL_CONTAINER_PREPARE_ARGS[@]+"${ANVIL_CONTAINER_PREPARE_ARGS[@]}"}
anvil_container_validate_array ANVIL_CONTAINER_PREPARE_COMMAND ${ANVIL_CONTAINER_PREPARE_COMMAND[@]+"${ANVIL_CONTAINER_PREPARE_COMMAND[@]}"}
anvil_container_validate_array ANVIL_CONTAINER_RUN_ARGS ${ANVIL_CONTAINER_RUN_ARGS[@]+"${ANVIL_CONTAINER_RUN_ARGS[@]}"}
anvil_container_validate_build_args ${ANVIL_CONTAINER_BUILD_ARGS[@]+"${ANVIL_CONTAINER_BUILD_ARGS[@]}"}
case "$ANVIL_CONTAINER_NEEDS_GITHUB_TOKEN" in
    true) needs_github_token=true ;;
    false) ;;
    *)
        echo 'anvil-container: ANVIL_CONTAINER_NEEDS_GITHUB_TOKEN must be true or false.' >&2
        exit 1
        ;;
esac
if ((${#ANVIL_CONTAINER_PREPARE_ARGS[@]} > 0)) && ((${#ANVIL_CONTAINER_PREPARE_COMMAND[@]} == 0)); then
    echo 'anvil-container: ANVIL_CONTAINER_PREPARE_ARGS requires ANVIL_CONTAINER_PREPARE_COMMAND.' >&2
    exit 1
fi
cleanup_kind="$(type -t "$ANVIL_CONTAINER_CLEANUP" 2>/dev/null || true)"
if [[ "$cleanup_kind" != "function" && "$cleanup_kind" != "builtin" ]]; then
    echo "anvil-container: ANVIL_CONTAINER_CLEANUP must name a callable function (got '$ANVIL_CONTAINER_CLEANUP')." >&2
    exit 1
fi

if "$needs_github_token"; then
    gh_command=""
    if command -v gh >/dev/null 2>&1; then
        gh_command=gh
    elif command -v gh.exe >/dev/null 2>&1; then
        gh_command=gh.exe
    fi
    github_token="${GITHUB_TOKEN:-}"
    if [[ -z "$github_token" && -n "$gh_command" ]]; then
        github_token="$("$gh_command" auth token --hostname github.com 2>/dev/null | tr -d '\r' || true)"
    fi
    if [[ -z "$github_token" ]]; then
        if [[ -z "$gh_command" ]]; then
            echo 'anvil-container: GitHub authentication is required for anvil-aprz. Install the GitHub CLI and run `gh auth login --hostname github.com`, or set GITHUB_TOKEN before rerunning.' >&2
            exit 1
        fi
        if [[ ! -t 0 ]]; then
            echo 'anvil-container: GitHub authentication is required for anvil-aprz. Run `gh auth login --hostname github.com` or set GITHUB_TOKEN before rerunning.' >&2
            exit 1
        fi
        echo 'anvil-container: anvil-aprz requires GitHub authentication to avoid the 60 requests/hour unauthenticated API limit.' >&2
        read -r -p 'Run `gh auth login --hostname github.com` in another terminal, then press Enter to continue (Ctrl+C to cancel) '
        github_token="$("$gh_command" auth token --hostname github.com 2>/dev/null | tr -d '\r' || true)"
        if [[ -z "$github_token" ]]; then
            echo 'anvil-container: GitHub authentication is still unavailable. Complete `gh auth login --hostname github.com`, then rerun.' >&2
            exit 1
        fi
    fi
fi

if ! "$image_exists"; then
    if [[ "${ANVIL_CONTAINER_NO_REBUILD:-}" == "1" ]]; then
        echo "anvil-container: image $image is missing and ANVIL_CONTAINER_NO_REBUILD=1." >&2
        exit 1
    else
        docker build \
            --platform linux/amd64 \
            --tag "$image" \
            --file "$script_dir/Containerfile" \
            --build-arg "ANVIL_IMAGE_ID=$image_id" \
            --build-arg "BASE_IMAGE=$base_image" \
            ${ANVIL_CONTAINER_BUILD_ARGS[@]+"${ANVIL_CONTAINER_BUILD_ARGS[@]}"} \
            "$repo_root"
    fi
fi

container_uid="$(id -u)"
container_gid="$(id -g)"
registry_volume="anvil-cargo-registry-${repo_id}"
git_volume="anvil-cargo-git-${repo_id}"
for volume in "$registry_volume" "$git_volume" "$target_volume"; do
    docker volume create "$volume" >/dev/null
done
mount_args=(
    --mount "type=bind,source=$repo_root,target=/workspace"
    --mount "type=volume,source=$registry_volume,target=/usr/local/cargo/registry"
    --mount "type=volume,source=$git_volume,target=/usr/local/cargo/git"
    --mount "type=volume,source=$target_volume,target=/workspace/target"
)
docker run --rm --pull=never \
    --platform linux/amd64 \
    --user 0:0 \
    "${mount_args[@]}" \
    "$image" sh -c \
    "chown $container_uid:$container_gid /usr/local/cargo/registry /usr/local/cargo/git /workspace/target"

run_args=(
    run --rm --pull=never
    --platform linux/amd64
    --user "$container_uid:$container_gid"
    --env ANVIL_IN_CONTAINER=1
    --env HOME=/tmp/anvil-user
    "${mount_args[@]}"
    --workdir /workspace
)
prepare_run_args=("${run_args[@]}")
run_args+=(${ANVIL_CONTAINER_RUN_ARGS[@]+"${ANVIL_CONTAINER_RUN_ARGS[@]}"})
for name in PR_TITLE BASE_REF ANVIL_INCLUDE_MODIFIED ANVIL_INCLUDE_AFFECTED ANVIL_INCLUDE_REQUIRED GITHUB_BASE_REF SYSTEM_PULLREQUEST_TARGETBRANCH; do
    if value="$(printenv "$name")"; then run_args+=(--env "$name=$value"); fi
done
if ((${#ANVIL_CONTAINER_PREPARE_COMMAND[@]} > 0)); then
    docker "${prepare_run_args[@]}" \
        ${ANVIL_CONTAINER_PREPARE_ARGS[@]+"${ANVIL_CONTAINER_PREPARE_ARGS[@]}"} \
        "$image" \
        "${ANVIL_CONTAINER_PREPARE_COMMAND[@]}"
fi

if [[ -n "$github_token" ]]; then
    github_token_file="$(mktemp "${TMPDIR:-/tmp}/anvil-github-token.XXXXXXXX")"
    chmod 600 "$github_token_file"
    printf '%s' "$github_token" > "$github_token_file"
    unset github_token
    github_run_args=(
        "${run_args[@]}"
        --mount "type=bind,source=$github_token_file,target=/run/secrets/anvil-github-token,readonly"
    )
    if "$runs_only_github_check"; then
        run_args=("${github_run_args[@]}")
    else
        docker "${github_run_args[@]}" "$image" just anvil-aprz
        run_args+=(--env ANVIL_APRZ_ALREADY_RAN=1)
    fi
fi

if (($# == 0)); then
    docker "${run_args[@]}" --interactive --tty "$image" bash
    exit $?
fi
docker "${run_args[@]}" "$image" just "$@"
