// Copyright (c) Microsoft Corporation.
// Licensed under the MIT License.

//! Build-time generated fixtures exercised by this crate's benchmarks and the
//! `rest_over_grpc` end-to-end / correctness tests.
//!
//! - [`bench_router`] / [`coverage`] — static routers emitted by
//!   `rest_over_grpc::build::generate_router` in `build.rs`; each exposes a
//!   `resolve(method, path)` function like the one the generated `Transcoder`
//!   uses internally.
//! - [`tonic_bridge`] / [`custom`] — the two handler-modality service fixtures
//!   (greeter via the `tonic` bridge, library via a direct `prost` handler),
//!   generated end to end so the integration tests can drive a real compiled
//!   `Transcoder`. These mirror the `rest_over_grpc_examples` crate's modules but
//!   are copied here so this crate stays independent of it.

#![allow(clippy::allow_attributes, reason = "generated code carries #[allow] attributes to suppress lints")]

pub mod custom;
pub mod tonic_bridge;

/// The large GitHub-like router driving the `grs_router_vs_matchit` benchmark.
pub mod bench_router {
    #![allow(
        clippy::all,
        clippy::pedantic,
        clippy::nursery,
        clippy::restriction,
        reason = "code generated by rest_over_grpc::build"
    )]

    include!(concat!(env!("OUT_DIR"), "/bench_router.rs"));
}

/// A small router exercising tricky routing cases, used by the correctness tests.
pub mod coverage {
    #![allow(
        clippy::all,
        clippy::pedantic,
        clippy::nursery,
        clippy::restriction,
        reason = "code generated by rest_over_grpc::build"
    )]

    include!(concat!(env!("OUT_DIR"), "/coverage_router.rs"));
}
