// Copyright (c) Microsoft Corporation.
// Licensed under the MIT License.

//! The "tonic bridge" modality: wiring a `tonic`-generated gRPC server into a
//! REST API.
//!
//! This is the common case: you implement your service only against `tonic`'s
//! generated server trait, and `rest_over_grpc::build` emits a blanket `impl`
//! that makes it a `rest_over_grpc` service too, so one implementation serves
//! both gRPC and REST. (To hand-write the service trait instead, see the
//! [`custom`](crate::custom) module.)
//!
//! [`GreeterService`] is the tonic-only handler shared by the runnable
//! `examples/tonic_bridge/` and the end-to-end `tests/bridge.rs`.

/// The generated greeter service: tonic messages + server trait, pbjson serde,
/// and the `rest_over_grpc` REST trait + transcoder + tonic bridge.
pub mod greeter {
    #![allow(
        clippy::all,
        clippy::pedantic,
        clippy::nursery,
        clippy::restriction,
        missing_docs,
        rustdoc::all,
        reason = "code generated by tonic + pbjson + rest_over_grpc::build"
    )]

    include!(concat!(env!("OUT_DIR"), "/tonic_bridge/greeter.rs"));
    include!(concat!(env!("OUT_DIR"), "/tonic_bridge/greeter.serde.rs"));
    include!(concat!(env!("OUT_DIR"), "/tonic_bridge/greeter.rest.rs"));
}

// Generated paths expect the proto package as a sibling module.
#[allow(
    clippy::all,
    clippy::pedantic,
    clippy::nursery,
    clippy::restriction,
    missing_docs,
    rustdoc::all,
    reason = "code generated by rest_over_grpc::build"
)]
mod transcoder {
    use super::greeter;
    include!(concat!(env!("OUT_DIR"), "/tonic_bridge/transcoder.rest.rs"));
}

use std::pin::Pin;

use futures_util::stream::{self, Stream};
use greeter::{HelloReply, HelloRequest, greeter_server};
pub use transcoder::Transcoder;

/// A greeter implemented purely against `tonic`'s generated `greeter_server::Greeter`
/// trait — it never mentions `rest_over_grpc`.
///
/// The generated blanket `impl` bridges it to the REST service trait, so a
/// [`Transcoder::new(GreeterService)`](Transcoder) transcodes REST/JSON requests
/// without any extra code.
#[derive(Debug, Default, Clone, Copy)]
pub struct GreeterService;

#[tonic::async_trait]
impl greeter_server::Greeter for GreeterService {
    async fn say_hello(&self, request: tonic::Request<HelloRequest>) -> Result<tonic::Response<HelloReply>, tonic::Status> {
        let name = request.into_inner().name;
        if name == "missing" {
            return Err(tonic::Status::not_found("no greeting for that name"));
        }
        Ok(tonic::Response::new(HelloReply {
            message: format!("Hello, {name}!"),
        }))
    }

    type StreamGreetingsStream = Pin<Box<dyn Stream<Item = Result<HelloReply, tonic::Status>> + Send + 'static>>;

    async fn stream_greetings(
        &self,
        request: tonic::Request<HelloRequest>,
    ) -> Result<tonic::Response<Self::StreamGreetingsStream>, tonic::Status> {
        let name = request.into_inner().name;
        let items = stream::iter(vec![
            Ok(HelloReply {
                message: format!("Hello, {name}!"),
            }),
            Ok(HelloReply {
                message: format!("Bye, {name}!"),
            }),
        ]);
        Ok(tonic::Response::new(Box::pin(items)))
    }
}
