// Copyright (c) Microsoft Corporation.
// Licensed under the MIT License.

// GENERATED FILE — do not edit by hand.
//
// The router used by the `build_script` example, produced by `routerama`'s
// `Generator` (the `build` feature) from this route set (all `GET`
// unless noted):
//
//     ListBooks    GET  /books
//     CreateBook   POST /books
//     GetBook      GET  /books/{book}
//     ListReviews  GET  /books/{book}/reviews
//     GetReview    GET  /books/{book}/reviews/{review}
//     ArchiveBook  POST /books/{book}:archive
//     SearchBooks  GET  /search
//
// In a real crate this is emitted from `build.rs` into `OUT_DIR` and `include!`d
// (see the crate-level docs); it is committed here only so the example is
// self-contained.
/// A resolved route, one variant per route name. Returned by the inherent
/// [`resolve`](Self::resolve) associated function.
///
/// A route that captures `{variable}` path segments is a struct variant
/// carrying them as `&'p str` fields (borrowed from the request path); a
/// route with no variables is a unit variant. Matching on it is an `O(1)`
/// jump table. Generated by `routerama_build`.
#[derive(
    ::core::clone::Clone,
    ::core::marker::Copy,
    ::core::fmt::Debug,
    ::core::cmp::PartialEq,
    ::core::cmp::Eq,
    ::core::cmp::PartialOrd,
    ::core::cmp::Ord,
    ::core::hash::Hash
)]
#[allow(
    non_camel_case_types,
    missing_docs,
    clippy::all,
    clippy::pedantic,
    clippy::nursery,
    clippy::restriction,
    dead_code,
    unused,
    reason = "code generated by routerama_build"
)]
pub enum Route<'p> {
    ListBooks,
    CreateBook,
    GetBook { book: &'p str },
    ListReviews { book: &'p str },
    GetReview { book: &'p str, review: &'p str },
    ArchiveBook { book: &'p str },
    SearchBooks,
}
#[allow(
    clippy::all,
    clippy::pedantic,
    clippy::nursery,
    clippy::restriction,
    dead_code,
    unused,
    reason = "code generated by routerama_build"
)]
impl<'p> Route<'p> {
    /// This route's name as the string it was declared with, independent
    /// of any captured variable values.
    #[must_use]
    pub const fn name(&self) -> &'static str {
        match *self {
            Route::ListBooks => "ListBooks",
            Route::CreateBook => "CreateBook",
            Route::GetBook { .. } => "GetBook",
            Route::ListReviews { .. } => "ListReviews",
            Route::GetReview { .. } => "GetReview",
            Route::ArchiveBook { .. } => "ArchiveBook",
            Route::SearchBooks => "SearchBooks",
        }
    }
    ///Resolves an HTTP `method` + `path` to the matching `Route`, capturing any path variables in the matched variant's fields. Returns `None` if no route matches. Generated by `routerama_build`.
    #[allow(
        clippy::all,
        clippy::pedantic,
        clippy::nursery,
        clippy::restriction,
        dead_code,
        unused,
        reason = "code generated by routerama_build"
    )]
    #[must_use]
    pub fn resolve<__P>(
        method: impl ::core::convert::AsRef<str>,
        path: &'p __P,
    ) -> ::core::option::Option<Route<'p>>
    where
        __P: ::core::convert::AsRef<str> + ?::core::marker::Sized,
    {
        let method: &str = ::core::convert::AsRef::<str>::as_ref(&method);
        let path: &'p str = ::core::convert::AsRef::<str>::as_ref(path);
        let (__body, __verb) = ::routerama::codegen_helpers::split_verb(path);
        let mut __starts = [0usize; 4];
        let mut __ends = [0usize; 4];
        let __count = ::routerama::codegen_helpers::scan_segments(__body, &mut __starts, &mut __ends);
        if __count > 0 {
            let __seg: &str = &__body[__starts[0]..__ends[0]];
            match __seg {
                "books" => {
                    if __count > 1 {
                        if __ends[1] > __starts[1] {
                            if __count > 2 {
                                let __seg: &str = &__body[__starts[2]..__ends[2]];
                                match __seg {
                                    "reviews" => {
                                        if __count > 3 {
                                            if __ends[3] > __starts[3] {
                                                if __count == 4 {
                                                    match method {
                                                        "GET" => {
                                                            match __verb {
                                                                ::core::option::Option::None => {
                                                                    return ::core::option::Option::Some(Route::GetReview {
                                                                        book: &__body[__starts[1]..__ends[1]],
                                                                        review: &__body[__starts[3]..__ends[3]],
                                                                    });
                                                                }
                                                                _ => {}
                                                            }
                                                        }
                                                        _ => {}
                                                    }
                                                }
                                            }
                                        }
                                        if __count == 3 {
                                            match method {
                                                "GET" => {
                                                    match __verb {
                                                        ::core::option::Option::None => {
                                                            return ::core::option::Option::Some(Route::ListReviews {
                                                                book: &__body[__starts[1]..__ends[1]],
                                                            });
                                                        }
                                                        _ => {}
                                                    }
                                                }
                                                _ => {}
                                            }
                                        }
                                    }
                                    _ => {}
                                }
                            }
                            if __count == 2 {
                                match method {
                                    "GET" => {
                                        match __verb {
                                            ::core::option::Option::None => {
                                                return ::core::option::Option::Some(Route::GetBook {
                                                    book: &__body[__starts[1]..__ends[1]],
                                                });
                                            }
                                            _ => {}
                                        }
                                    }
                                    "POST" => {
                                        match __verb {
                                            ::core::option::Option::Some("archive") => {
                                                return ::core::option::Option::Some(Route::ArchiveBook {
                                                    book: &__body[__starts[1]..__ends[1]],
                                                });
                                            }
                                            _ => {}
                                        }
                                    }
                                    _ => {}
                                }
                            }
                        }
                    }
                    if __count == 1 {
                        match method {
                            "GET" => {
                                match __verb {
                                    ::core::option::Option::None => {
                                        return ::core::option::Option::Some(Route::ListBooks);
                                    }
                                    _ => {}
                                }
                            }
                            "POST" => {
                                match __verb {
                                    ::core::option::Option::None => {
                                        return ::core::option::Option::Some(Route::CreateBook);
                                    }
                                    _ => {}
                                }
                            }
                            _ => {}
                        }
                    }
                }
                "search" => {
                    if __count == 1 {
                        match method {
                            "GET" => {
                                match __verb {
                                    ::core::option::Option::None => {
                                        return ::core::option::Option::Some(Route::SearchBooks);
                                    }
                                    _ => {}
                                }
                            }
                            _ => {}
                        }
                    }
                }
                _ => {}
            }
        }
        ::core::option::Option::None
    }
}
#[allow(
    clippy::all,
    clippy::pedantic,
    clippy::nursery,
    clippy::restriction,
    dead_code,
    unused,
    reason = "code generated by routerama_build"
)]
impl<'p> ::core::fmt::Display for Route<'p> {
    fn fmt(&self, f: &mut ::core::fmt::Formatter<'_>) -> ::core::fmt::Result {
        f.write_str(self.name())
    }
}
#[allow(
    clippy::all,
    clippy::pedantic,
    clippy::nursery,
    clippy::restriction,
    dead_code,
    unused,
    reason = "code generated by routerama_build"
)]
impl<'p> ::core::convert::AsRef<str> for Route<'p> {
    fn as_ref(&self) -> &str {
        self.name()
    }
}
#[allow(
    clippy::all,
    clippy::pedantic,
    clippy::nursery,
    clippy::restriction,
    dead_code,
    unused,
    reason = "code generated by routerama_build"
)]
impl<'p> ::routerama::codegen_helpers::Route<'p> for Route<'p> {
    #[inline]
    fn resolve<__P>(
        method: impl ::core::convert::AsRef<str>,
        path: &'p __P,
    ) -> ::core::option::Option<Self>
    where
        __P: ::core::convert::AsRef<str> + ?::core::marker::Sized,
    {
        Route::resolve(method, path)
    }
    #[inline]
    fn name(&self) -> &'static str {
        Route::name(self)
    }
}
