// Copyright (c) Microsoft Corporation.
// Licensed under the MIT License.

// GENERATED FILE — do not edit by hand.
//
// The resolver used by the `build_script` example, produced by `routerama`'s
// `Generator` (the `build` feature) from this route set (all `GET` unless noted):
//
//     ListBooks    GET  /books
//     CreateBook   POST /books
//     GetBook      GET  /books/{book}
//     ListReviews  GET  /books/{book}/reviews
//     GetReview    GET  /books/{book}/reviews/{review}
//     ArchiveBook  POST /books/{book}:archive
//     SearchBooks  GET  /search
//
// In a real crate this is emitted from `build.rs` into `OUT_DIR` and `include!`d
// (see the crate-level docs); it is committed here only so the example is
// self-contained.

/// A resolved route, one variant per route name. Produced by the
/// `resolve` method of the generated resolver (its `Resolver` impl).
///
/// A route that captures `{variable}` path segments is a struct variant
/// carrying them as `&'p str` fields (borrowed from the request path); a
/// route with no variables is a unit variant. Matching on it is an `O(1)`
/// jump table. Generated by `routerama_build`.
#[derive(
    ::core::clone::Clone,
    ::core::marker::Copy,
    ::core::fmt::Debug,
    ::core::cmp::PartialEq,
    ::core::cmp::Eq,
    ::core::cmp::PartialOrd,
    ::core::cmp::Ord,
    ::core::hash::Hash
)]
#[allow(
    non_camel_case_types,
    missing_docs,
    clippy::all,
    clippy::pedantic,
    clippy::nursery,
    clippy::restriction,
    dead_code,
    unused,
    reason = "code generated by routerama_build"
)]
pub enum Route<'p> {
    ListBooks,
    CreateBook,
    GetBook { book: &'p str },
    ListReviews { book: &'p str },
    GetReview { book: &'p str, review: &'p str },
    ArchiveBook { book: &'p str },
    SearchBooks,
}
/// A zero-sized [`Resolver`](routerama::Resolver) that resolves a request to a [`Route`]. Composes with a dynamic resolver via `EitherResolver`. Generated by `routerama_build`.
#[derive(
    ::core::clone::Clone,
    ::core::marker::Copy,
    ::core::fmt::Debug,
    ::core::default::Default
)]
#[allow(
    clippy::all,
    clippy::pedantic,
    clippy::nursery,
    clippy::restriction,
    dead_code,
    unused,
    reason = "code generated by routerama_build"
)]
pub struct RouteResolver;
#[allow(
    clippy::all,
    clippy::pedantic,
    clippy::nursery,
    clippy::restriction,
    dead_code,
    unused,
    reason = "code generated by routerama_build"
)]
impl ::routerama::codegen_helpers::Resolver for RouteResolver {
    type Match<'p> = Route<'p>;
    #[inline]
    fn resolve<'p, __P>(
        &'p self,
        method: impl ::core::convert::AsRef<str>,
        path: &'p __P,
    ) -> ::core::option::Option<Route<'p>>
    where
        __P: ::core::convert::AsRef<str> + ?::core::marker::Sized,
    {
        let method: &str = ::core::convert::AsRef::<str>::as_ref(&method);
        let path: &'p str = ::core::convert::AsRef::<str>::as_ref(path);
        let (__body, __verb) = ::routerama::codegen_helpers::split_verb(path);
        let mut __starts = [0usize; 4];
        let mut __ends = [0usize; 4];
        let __count = ::routerama::codegen_helpers::scan_segments(
            __body,
            &mut __starts,
            &mut __ends,
        );
        if __count > 0 {
            let __seg: &[u8] = ::routerama::codegen_helpers::seg_bytes(
                __body,
                __starts[0],
                __ends[0],
            );
            match __seg {
                b"books" => {
                    if __count > 1 {
                        if __ends[1] > __starts[1] {
                            if __count > 2 {
                                let __seg: &[u8] = ::routerama::codegen_helpers::seg_bytes(
                                    __body,
                                    __starts[2],
                                    __ends[2],
                                );
                                match __seg {
                                    b"reviews" => {
                                        if __count > 3 {
                                            if __ends[3] > __starts[3] {
                                                if __count == 4 {
                                                    match method {
                                                        "GET" => {
                                                            match __verb {
                                                                ::core::option::Option::None => {
                                                                    return ::core::option::Option::Some(Route::GetReview {
                                                                        book: ::routerama::codegen_helpers::substr(
                                                                            __body,
                                                                            __starts[1],
                                                                            __ends[1],
                                                                        ),
                                                                        review: ::routerama::codegen_helpers::substr(
                                                                            __body,
                                                                            __starts[3],
                                                                            __ends[3],
                                                                        ),
                                                                    });
                                                                }
                                                                _ => {}
                                                            }
                                                        }
                                                        _ => {}
                                                    }
                                                }
                                            }
                                        }
                                        if __count == 3 {
                                            match method {
                                                "GET" => {
                                                    match __verb {
                                                        ::core::option::Option::None => {
                                                            return ::core::option::Option::Some(Route::ListReviews {
                                                                book: ::routerama::codegen_helpers::substr(
                                                                    __body,
                                                                    __starts[1],
                                                                    __ends[1],
                                                                ),
                                                            });
                                                        }
                                                        _ => {}
                                                    }
                                                }
                                                _ => {}
                                            }
                                        }
                                    }
                                    _ => {}
                                }
                            }
                            if __count == 2 {
                                match method {
                                    "GET" => {
                                        match __verb {
                                            ::core::option::Option::None => {
                                                return ::core::option::Option::Some(Route::GetBook {
                                                    book: ::routerama::codegen_helpers::substr(
                                                        __body,
                                                        __starts[1],
                                                        __ends[1],
                                                    ),
                                                });
                                            }
                                            _ => {}
                                        }
                                    }
                                    "POST" => {
                                        match __verb {
                                            ::core::option::Option::Some("archive") => {
                                                return ::core::option::Option::Some(Route::ArchiveBook {
                                                    book: ::routerama::codegen_helpers::substr(
                                                        __body,
                                                        __starts[1],
                                                        __ends[1],
                                                    ),
                                                });
                                            }
                                            _ => {}
                                        }
                                    }
                                    _ => {}
                                }
                            }
                        }
                    }
                    if __count == 1 {
                        match method {
                            "GET" => {
                                match __verb {
                                    ::core::option::Option::None => {
                                        return ::core::option::Option::Some(Route::ListBooks);
                                    }
                                    _ => {}
                                }
                            }
                            "POST" => {
                                match __verb {
                                    ::core::option::Option::None => {
                                        return ::core::option::Option::Some(Route::CreateBook);
                                    }
                                    _ => {}
                                }
                            }
                            _ => {}
                        }
                    }
                }
                b"search" => {
                    if __count == 1 {
                        match method {
                            "GET" => {
                                match __verb {
                                    ::core::option::Option::None => {
                                        return ::core::option::Option::Some(Route::SearchBooks);
                                    }
                                    _ => {}
                                }
                            }
                            _ => {}
                        }
                    }
                }
                _ => {}
            }
        }
        ::core::option::Option::None
    }
}
#[allow(
    clippy::all,
    clippy::pedantic,
    clippy::nursery,
    clippy::restriction,
    dead_code,
    unused,
    reason = "code generated by routerama_build"
)]
impl<'p> ::routerama::codegen_helpers::RouteMatch<'p> for Route<'p> {
    #[inline]
    fn name(&self) -> &str {
        match *self {
            Route::ListBooks => "ListBooks",
            Route::CreateBook => "CreateBook",
            Route::GetBook { .. } => "GetBook",
            Route::ListReviews { .. } => "ListReviews",
            Route::GetReview { .. } => "GetReview",
            Route::ArchiveBook { .. } => "ArchiveBook",
            Route::SearchBooks => "SearchBooks",
        }
    }
    #[inline]
    fn capture(&self, __key: &str) -> ::core::option::Option<&'p str> {
        match self {
            Route::ListBooks => ::core::option::Option::None,
            Route::CreateBook => ::core::option::Option::None,
            Route::GetBook { book: __cap_book } => {
                match __key {
                    "book" => ::core::option::Option::Some(*__cap_book),
                    _ => ::core::option::Option::None,
                }
            }
            Route::ListReviews { book: __cap_book } => {
                match __key {
                    "book" => ::core::option::Option::Some(*__cap_book),
                    _ => ::core::option::Option::None,
                }
            }
            Route::GetReview { book: __cap_book, review: __cap_review } => {
                match __key {
                    "book" => ::core::option::Option::Some(*__cap_book),
                    "review" => ::core::option::Option::Some(*__cap_review),
                    _ => ::core::option::Option::None,
                }
            }
            Route::ArchiveBook { book: __cap_book } => {
                match __key {
                    "book" => ::core::option::Option::Some(*__cap_book),
                    _ => ::core::option::Option::None,
                }
            }
            Route::SearchBooks => ::core::option::Option::None,
        }
    }
}
