// Copyright (c) Microsoft Corporation.
// Licensed under the MIT License.

//! End-to-end sample exercising the gRPC→REST transcoding pipeline.
//!
//! - [`pb`] holds the `prost`-generated message types plus their `pbjson`
//!   proto3-canonical serde implementations (generated from `proto/library.proto`).
//! - [`service`] holds the build-time generated REST router, service trait, and
//!   async dispatcher (generated by `rest_over_grpc_build`).

#![allow(clippy::allow_attributes, reason = "generated code carries #[allow] attributes to suppress lints")]

/// The `prost` + `pbjson` generated protobuf message types.
pub mod pb {
    #![allow(
        clippy::all,
        clippy::pedantic,
        clippy::nursery,
        clippy::restriction,
        missing_docs,
        rustdoc::all,
        reason = "code generated by prost + pbjson"
    )]

    include!(concat!(env!("OUT_DIR"), "/library.rs"));
    include!(concat!(env!("OUT_DIR"), "/library.serde.rs"));
}

/// The build-time generated REST router, service trait, and dispatcher.
pub mod service {
    include!(concat!(env!("OUT_DIR"), "/router.rs"));
}

/// A large build-time generated static router used by the `router_vs_axum`
/// benchmark. Generated from the shared `bench_routes.rs` table; exposes a
/// `resolve(method, path)` function equivalent to the one in [`service`].
pub mod bench_router {
    #![allow(
        clippy::all,
        clippy::pedantic,
        clippy::nursery,
        clippy::restriction,
        reason = "code generated by rest_over_grpc_build"
    )]

    include!(concat!(env!("OUT_DIR"), "/bench_router.rs"));
}

/// A small generated router exercising tricky routing cases (literal-vs-wildcard
/// backtracking, custom verbs, nested field paths, `**` capture, prefix overlap),
/// used by the correctness tests.
pub mod coverage {
    #![allow(
        clippy::all,
        clippy::pedantic,
        clippy::nursery,
        clippy::restriction,
        reason = "code generated by rest_over_grpc_build"
    )]

    include!(concat!(env!("OUT_DIR"), "/coverage_router.rs"));
}

use pb::{CreateShelfRequest, GetShelfRequest, ListShelvesRequest, ListShelvesResponse, Shelf};
use rest_over_grpc::Status;

/// A tiny in-memory implementation of the generated [`service::Library`] trait,
/// shared by the integration tests.
#[derive(Debug, Default, Clone)]
pub struct InMemoryLibrary;

impl service::Library for InMemoryLibrary {
    async fn get_shelf(&self, request: GetShelfRequest) -> Result<Shelf, Status> {
        if request.shelf == "missing" {
            return Err(Status::not_found("no such shelf"));
        }
        Ok(Shelf {
            name: format!("shelves/{}", request.shelf),
            theme: "history".to_owned(),
        })
    }

    async fn create_shelf(&self, request: CreateShelfRequest) -> Result<Shelf, Status> {
        let mut created = request.shelf.ok_or_else(|| Status::invalid_argument("shelf is required"))?;
        "shelves/created".clone_into(&mut created.name);
        Ok(created)
    }

    async fn list_shelves(&self, request: ListShelvesRequest) -> Result<ListShelvesResponse, Status> {
        let all = [
            Shelf {
                name: "shelves/1".to_owned(),
                theme: "history".to_owned(),
            },
            Shelf {
                name: "shelves/2".to_owned(),
                theme: "science".to_owned(),
            },
        ];
        let shelves = all
            .into_iter()
            .filter(|s| request.filter.is_empty() || s.theme == request.filter)
            .collect();
        Ok(ListShelvesResponse { shelves })
    }
}
