[package]
name = "isolated_domains"
description = "This crate provides a set of tools to work with isolated data domains."
edition.workspace = true
rust-version.workspace = true
authors.workspace = true
license-file.workspace = true
readme.workspace = true
homepage.workspace = true
repository.workspace = true
keywords.workspace = true
categories.workspace = true
publish.workspace = true
version.workspace = true

[dependencies]
mutants = { workspace = true }

[dev-dependencies]
oxidizer_testing = { path = "../oxidizer_testing" }
oxidizer_rt = { path = "../oxidizer_rt" }

[lints]
workspace = true
