# Copyright (c) Microsoft Corporation.
# Licensed under the MIT License.

[package]
name = "allocation_hints"
version = "0.1.0"
description = "Passive allocator-independent scoped allocation hints."
readme = "README.md"
keywords = ["allocator", "heap", "memory", "bump"]
categories = ["memory-management"]
links = "allocation_hints_runtime"

edition.workspace = true
rust-version.workspace = true
authors.workspace = true
license.workspace = true
homepage.workspace = true
include.workspace = true
repository = "https://github.com/microsoft/oxidizer/tree/main/crates/allocation_hints"

[dependencies]
performables.workspace = true
pin-project-lite.workspace = true

[lints]
workspace = true
