name: Update Changelog

permissions:
  contents: write
  pull-requests: write

on:
  push:
    tags:
      - '*-v[0-9]+.[0-9]+.[0-9]+'

jobs:
  update-changelog:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install git-cliff
        uses: taiki-e/install-action@v2
        with:
          tool: git-cliff@2.10.1

      - name: Parse Tag
        id: parse_tag
        run: |
          set -eo pipefail

          # Remove the 'refs/tags/' prefix
          tag="${{ github.ref_name }}"

          # Extract the part before the final '-vX.Y.Z'
          crate_name=$(echo "$tag" | sed -E 's/(.*)-v[0-9]+\.[0-9]+\.[0-9]+/\1/')

          # Security: Validate the crate name to prevent path traversal
          if [[ "$crate_name" == "" || "$crate_name" == *..* || "$crate_name" == */* ]]; then
            echo "::error::Invalid crate name derived from tag: '$crate_name'"
            exit 1
          fi

          echo "crate_name=${crate_name}" >> "$GITHUB_OUTPUT"
          echo "crate_path=crates/${crate_name}" >> "$GITHUB_OUTPUT"

      - name: Update Changelog
        run: |
          git-cliff --output "${{ steps.parse_tag.outputs.crate_path }}/CHANGELOG.md" --latest

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v6
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: 'task: Update changelog for ${{ steps.parse_tag.outputs.crate_name }}'
          title: 'task: Updating changelog for crate ${{ steps.parse_tag.outputs.crate_name }}'
          add-paths: |
            ${{ steps.parse_tag.outputs.crate_path }}/CHANGELOG.md
          branch: 'task/update-changelog-${{ steps.parse_tag.outputs.crate_name }}'
          base: main
          author: GitHub Action <actions@github.com>
          committer: GitHub Action <actions@github.com>