[package]
name = "oxidizer_rt_testing"
description = "This crate is a private dependency of the `oxidizer` crate. You should never add this as a direct dependency. The entire API surface is unstable."
version.workspace = true
edition.workspace = true
rust-version.workspace = true
authors.workspace = true
license-file.workspace = true
readme.workspace = true
homepage.workspace = true
repository.workspace = true
keywords.workspace = true
categories.workspace = true
publish = false

[features]

[dependencies]
oneshot = { workspace = true }

[dev-dependencies]
mutants = { workspace = true }

[lints]
workspace = true
